### ISSUE TITLE
References: Segmentation train.py throws error

### ISSUE THREAD

**Issue by gaussiangit** [pytorch/vision#1105]
Hi, 
When I try to train deeplabv3 using train script given under references/Segmentation. I encountered following error. Can anyone help ? 

  File "train.py", line 227, in <module>
    main(args)
  File "train.py", line 164, in main
    train_one_epoch(model, criterion, optimizer, data_loader, lr_scheduler, device, epoch, args.print_freq)
  File "train.py", line 81, in train_one_epoch
    for image, target in metric_logger.log_every(data_loader, print_freq, header):
  File "/home/user/semantictorch/utils.py", line 184, in log_every
    for obj in iterable:
  File "/home/user/miniconda3/envs/pytorchts/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/user/miniconda3/envs/pytorchts/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/user/miniconda3/envs/pytorchts/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/user/miniconda3/envs/pytorchts/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/user/miniconda3/envs/pytorchts/lib/python3.6/site-packages/torchvision/datasets/coco.py", line 114, in __getitem__
    img, target = self.transforms(img, target)
TypeError: __call__() takes 2 positional arguments but 3 were given

**Comment by fmassa** [comment]
Did you change the code to adapt the transforms?

**Comment by gaussiangit** [comment]
> Did you change the code to adapt the transforms?

Thank you for quick reply. I am working with the coco. I have been using given default transforms. Thought it should work. I will look into transforms to adapt accordingly.

**Comment by fmassa** [comment]
@gaussiangit if you didn't change anything, then this error is unexpected.

It looks like you are using different transforms from the ones implemented in https://github.com/pytorch/vision/blob/master/references/segmentation/transforms.py

Can you double-check?

**Comment by gaussiangit** [comment]
> @gaussiangit if you didn't change anything, then this error is unexpected.
> 
> It looks like you are using different transforms from the ones implemented in https://github.com/pytorch/vision/blob/master/references/segmentation/transforms.py
> 
> Can you double-check?
Yes you were right. Apologies. I oversight the transform in one of the files. Thank you.
