### ISSUE TITLE
Error when loading pretrained VGG19

### ISSUE THREAD

**Issue by ntomita** [pytorch/vision#112]
I encountered an error when loading a pretrained vgg19 model. I tried other networks like Alexnet and they're seemed fine.

I use torch==0.1.10, torchvision==0.1.7, just updated from master branch. Also, it's under Python3.6 on latest macOS.

Do anyone have any idea how this happened and can be fixed? An error message seems like complaining incompatible un-pickling.

> >>> model = models.vgg19(True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/torchvision/models/vgg.py", line 141, in vgg19
    model.load_state_dict(model_zoo.load_url(model_urls['vgg19']))
  File "/usr/local/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 57, in load_url
    return torch.load(cached_file)
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 222, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 370, in _load
    result = unpickler.load()
AttributeError: Can't get attribute '_rebuild_tensor' on <module 'torch._utils' from '/usr/local/lib/python3.6/site-packages/torch/_utils.py'>

**Comment by ntomita** [comment]
I also note that loading vgg11 and vgg13 is fine. vgg16 and vgg19 produces the error.

**Comment by soumith** [comment]
what version of torch are you on?

**Comment by ntomita** [comment]
I'm using torch==0.1.10, this is the newest one, right?

**Comment by soumith** [comment]
yes it is, I'll investigate and fix these checkpoints on Monday. thanks for letting me know.

**Comment by ntomita** [comment]
Thanks!

**Comment by soumith** [comment]
this will be fixed after updating to the pytorch release v0.1.11 on wednesday.

**Comment by ntomita** [comment]
Thank you very much for your quick response! I'm looking forward to it.

**Comment by Cadene** [comment]
I encouter the same error for vgg16.

```
CUDA_VISIBLE_DEVICES=2 python main.py /local/cadene/data --arch vgg16 -b 20 --lr 1e-4 --pretrained
=> using pre-trained model 'vgg16'
Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to /home/cadene/.torch/models/vgg16-397923af.pth
100.0%
Traceback (most recent call last):
  File "main.py", line 335, in <module>
    main()
  File "main.py", line 120, in main
    model = models.__dict__[args.arch](pretrained=True)
  File "build/bdist.linux-x86_64/egg/torchvision/models/vgg.py", line 124, in vgg16
    model.load_state_dict(model_zoo.load_url(model_urls['vgg16']))
  File "/home/cadene/anaconda3/envs/default/lib/python2.7/site-packages/torch/utils/model_zoo.py", line 57, in load_url
    return torch.load(cached_file)
  File "/home/cadene/anaconda3/envs/default/lib/python2.7/site-packages/torch/serialization.py", line 222, in load
    return _load(f, map_location, pickle_module)
  File "/home/cadene/anaconda3/envs/default/lib/python2.7/site-packages/torch/serialization.py", line 370, in _load
    result = unpickler.load()
AttributeError: 'module' object has no attribute '_rebuild_tensor'
```

**Comment by lanpa** [comment]
@Cadene I solved the same problem by installing newest pytorch and torchvision from source.

**Comment by alykhantejani** [comment]
@Cadene is this still an issue for you when using the latest pytorch?

**Comment by alykhantejani** [comment]
This appears to work with the latest version of PyTorch so closing this issue. Let me know if you are still having issues.

**Comment by varghesealex90** [comment]
Getting an error when import inception model. Any fixes. Same with densenet. However all models of resnet loading without any issues

**Comment by varghesealex90** [comment]
> inception = torchvision.models.inception_v3()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'inception_v3'

**Comment by alykhantejani** [comment]
@varghesealex90 this works fine in the latest version of `torchvision`. What version are you running as inception_v3 was added in 0.1.8

**Comment by varghesealex90** [comment]
could you tell me on how to get the torchvision version. 

torch__version__ returns 0.2.0.3

**Comment by varghesealex90** [comment]
oki fixed it . closing the issue

**Comment by varghesealex90** [comment]
Hi;

I am encountering a new problem. I am unable to load the pre-trained network.

import torchvision

a= torchvision.models.denset121(pretrained=True)
Downloading: "https://download.pytorch.org/models/densenet121-241335ed.pth" to /home/brats/.torch/models/densenet121-241335ed.pth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/torchvision/models/densenet.py", line 28, in densenet121
    model.load_state_dict(model_zoo.load_url(model_urls['densenet121']))
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/model_zoo.py", line 57, in load_url
    _download_url_to_file(url, cached_file, hash_prefix)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/model_zoo.py", line 62, in _download_url_to_file
    u = urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>

**Comment by varghesealex90** [comment]
import torchvision.models
from torchvision.models.vgg import model_urls

model_urls['densenet121'] = model_urls['densenet121'].replace('https://', 'http://')
densenet121= torchvision.models.densenet121(pretrained=True)

**Comment by alykhantejani** [comment]
@varghesealex90 the model for densenet121 in master is located at `https://download.pytorch.org/models/densenet121-a639ec97.pth` which is not the one you are downloading.

In any case, this seems to work fine on my end but may be related to [server name identification](https://stackoverflow.com/questions/31649390/python-requests-ssl-handshake-failure). Can you let me know what python version you are using?

**Comment by varghesealex90** [comment]
I am using python 2.7.6 , I fixed the issue by converting https to http

**Comment by alykhantejani** [comment]
@varghesealex90 I can reproduce this issue in `python 2.6.7` and can be solved by using server name identification support which was added to python 2.7.9+ so you have two options:
1) install the dependencies as described [here](https://stackoverflow.com/questions/18578439/using-requests-with-tls-doesnt-give-sni-support/18579484#18579484).
2) upgrade your python version.
