### ISSUE TITLE
The onnx of resnet failed parsed by TensorRT5.0

### ISSUE THREAD

**Issue by apache2046** [pytorch/vision#1133]
when using tensorRT 5.0 to load the onnx file exported by pytorch, it will report a error like this:

```
While parsing node number 16 [Gather -> "33"]:
ERROR: /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.0/parsers/onnxOpenSource/ModelImporter.cpp:142 In function importNode:
[8] No importer registered for op: Gather
ERROR: failed to parse onnx file
```

resnet, squeezenet, vgg, inception, googlenet, densenet, alexnet of the torchvision all have this problem

**Comment by apache2046** [comment]
A fix method is #1134

**Comment by fmassa** [comment]
Fixed via https://github.com/pytorch/vision/pull/1134

**Comment by lyp-deeplearning** [comment]
@fmassa @apache2046 when i use the  x = torch.flatten(x, 1) to generate my new resnet model,there is a new problem happended when i export my model to onnx format:
`Traceback (most recent call last):
  File "export_onnx.py", line 53, in <module>
    main()
  File "export_onnx.py", line 47, in main
    torch.onnx.export(car.model,input,"gender_thin2.onnx",verbose=True)
  File "/home/yusheng.zeng/softmare/Anaconda2.7/lib/python2.7/site-packages/torch/onnx/__init__.py", line 27, in export
    return utils.export(*args, **kwargs)
  File "/home/yusheng.zeng/softmare/Anaconda2.7/lib/python2.7/site-packages/torch/onnx/utils.py", line 104, in export
    operator_export_type=operator_export_type)
  File "/home/yusheng.zeng/softmare/Anaconda2.7/lib/python2.7/site-packages/torch/onnx/utils.py", line 287, in _export
    proto, export_map = graph._export_onnx(params, _onnx_opset_version, defer_weight_export, operator_export_type)
RuntimeError: ONNX export failed: Couldn't export operator aten::flatten
`
this seems like flatten operation is not exited in torch.onnx module, so what can i do?
