### ISSUE TITLE
Resnet fpn backbone does not work for resnet18 and resnet34

### ISSUE THREAD

**Issue by truskovskiyk** [pytorch/vision#1146]
Hello, I have a bug with 
`torchvision==0.3.0`

This code works fine
```
import torch
from torchvision.models.detection.backbone_utils import resnet_fpn_backbone

resnet152_fpn = resnet_fpn_backbone(backbone_name='resnet152', pretrained=False).eval()
x = torch.rand(1, 3, 800, 800)
resnet152_fpn(x)


resnet101_fpn = resnet_fpn_backbone(backbone_name='resnet101', pretrained=False).eval()
x = torch.rand(1, 3, 800, 800)
resnet101_fpn(x)


resnet50_fpn = resnet_fpn_backbone(backbone_name='resnet50', pretrained=False).eval()
x = torch.rand(1, 3, 800, 800)
resnet50_fpn(x)
```

But 
```
resnet34_fpn = resnet_fpn_backbone(backbone_name='resnet34', pretrained=False).eval()
x = torch.rand(1, 3, 800, 800)
resnet34_fpn(x)


resnet18_fpn = resnet_fpn_backbone(backbone_name='resnet18', pretrained=False).eval()
x = torch.rand(1, 3, 800, 800)
resnet18_fpn(x)
```

fails with 

```
Traceback (most recent call last):
  File "issue_reproduce.py", line 20, in <module>
    resnet34_fpn(x)
  File "/Users/kyryl/vn/common/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/kyryl/vn/common/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/Users/kyryl/vn/common/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/kyryl/vn/common/lib/python3.6/site-packages/torchvision/ops/feature_pyramid_network.py", line 83, in forward
    last_inner = self.inner_blocks[-1](x[-1])
  File "/Users/kyryl/vn/common/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/kyryl/vn/common/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 256 2048 1 1, expected input[1, 512, 25, 25] to have 2048 channels, but got 512 channels instead
```

The reason is that this line 
https://github.com/pytorch/vision/blob/master/torchvision/models/detection/backbone_utils.py#L54
produces `in_channels_list` as list `[256, 512, 1024, 2048]`
but for `resnet18` and `resnet34` `in_channels_list` should be `[64, 128, 256, 512]`.
I have fixed this internally and would be happy to sent PR with tests to torchvision repo

cc: @fmassa

**Comment by fmassa** [comment]
Fixed via #1147
