### ISSUE TITLE
ONNX export failed: Couldn't export operator aten::flatten

### ISSUE THREAD

**Issue by lyp-deeplearning** [pytorch/vision#1232]
@ezyang @smartkiwi when i use the x = torch.flatten(x, 1) to generate my new resnet model,there is a new problem happended when i export my model to onnx format:
Traceback (most recent call last): File "export_onnx.py", line 53, in <module> main() File "export_onnx.py", line 47, in main torch.onnx.export(car.model,input,"gender_thin2.onnx",verbose=True) File "/home/yusheng.zeng/softmare/Anaconda2.7/lib/python2.7/site-packages/torch/onnx/__init__.py", line 27, in export return utils.export(*args, **kwargs) File "/home/yusheng.zeng/softmare/Anaconda2.7/lib/python2.7/site-packages/torch/onnx/utils.py", line 104, in export operator_export_type=operator_export_type) File "/home/yusheng.zeng/softmare/Anaconda2.7/lib/python2.7/site-packages/torch/onnx/utils.py", line 287, in _export proto, export_map = graph._export_onnx(params, _onnx_opset_version, defer_weight_export, operator_export_type) RuntimeError: ONNX export failed: Couldn't export operator aten::flatten 
this seems like flatten operation is not exited in torch.onnx module, so what can i do?

**Comment by lara-hdr** [comment]
What version of Pytorch are you using?
torch.flatten should be supported since https://github.com/pytorch/pytorch/pull/16240.

**Comment by fmassa** [comment]
Closing as `flatten` is supported in a newer version of ONNX
