### ISSUE TITLE
undefined symbol: THPVariable_Wrap

### ISSUE THREAD

**Issue by as754770178** [pytorch/vision#1235]
I install `vision` from source. when I exec `vision/test/test_models.py`, the program report error.

```
Error
Traceback (most recent call last):
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/home/xtz/code/vision/test/test_models.py", line 144, in do_test
    self._test_detection_model(model_name)
  File "/home/xtz/code/vision/test/test_models.py", line 54, in _test_detection_model
    out = model(model_input)
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/torchvision/models/detection/generalized_rcnn.py", line 51, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/torchvision/models/detection/rpn.py", line 411, in forward
    boxes, scores = self.filter_proposals(proposals, objectness, images.image_sizes, num_anchors_per_level)
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/torchvision/models/detection/rpn.py", line 336, in filter_proposals
    keep = box_ops.batched_nms(boxes, scores, lvl, self.nms_thresh)
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/torchvision/ops/boxes.py", line 72, in batched_nms
    keep = nms(boxes_for_nms, scores, iou_threshold)
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/torchvision/ops/boxes.py", line 32, in nms
    _C = _lazy_import()
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/torchvision/extension.py", line 12, in _lazy_import
    from torchvision import _C as C
ImportError: /home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/torchvision/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: THPVariable_Wrap


```

**Comment by fmassa** [comment]
@as754770178 are you using PyTorch 1.2 that was released, or a nightly build?

Note that `torchvision` 0.4 *requires* PyTorch 1.2, and not the nightly

**Comment by as754770178** [comment]
my vision is `torchvision-0.5.0a0+8635be9-py3.7-linux-x86_64.egg`

**Comment by as754770178** [comment]
Thanks

**Comment by fmassa** [comment]
Did you fix your problem? (Sorry for the delay in replying, I was on holidays)

**Comment by as754770178** [comment]
I don't resolve. And I want to know correspondence between torch and vision.
toch:1.2.0 -> vision 0.4.0
toch:1.1.0 -> vision 0.3.0
Is this right?

**Comment by fmassa** [comment]
Yes, this is right and should work.

Can you start from a clean conda environment, and install pytorch and torchvision from conda?

**Comment by as754770178** [comment]
I successful install, but I want to compile from torch:master and vision:master. I just want to try it.

**Comment by fmassa** [comment]
please clean your previously installed libraries and try compiling from master. The error is indicating that you are using a different version of pytorch to compile torchvision and to run it.
