### ISSUE TITLE
Latest Pre-train VGG Corrupted

### ISSUE THREAD

**Issue by yobajnin** [pytorch/vision#125]
At least the vgg19xxx.pth and vggxxx.16 - did not try the others.

**Comment by soumith** [comment]
can you elaborate on what you mean by corrupted?

**Comment by yobajnin** [comment]
Sorry, here's the details -

vgg19-dcbb9e9d.pth is not a tar/pax file:

pax -v -f vgg19-dcbb9e9d.pth
pax: Cannot identify format. Searching...
pax: cpio file name length 29486 is out of range
...

whereas the older version:
pax -v -f vgg19-341d7465.pth
----------  1 root     root            28 Dec 31  1969 ././@PaxHeader
-rw-------  1 12254    users          116 Dec 31  1969 sys_info
----------  1 root     root            28 Dec 31  1969 ././@PaxHeader
...

which is causing the error on load:
Traceback (most recent call last):
  File "/usr/lib/python3.5/tarfile.py", line 182, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: 'ons\nOrde'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/tarfile.py", line 2279, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.5/tarfile.py", line 1083, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/usr/lib/python3.5/tarfile.py", line 1025, in frombuf
    chksum = nti(buf[148:156])
  File "/usr/lib/python3.5/tarfile.py", line 184, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nn_style.py", line 89, in <module>
    NNStyle(args).run()
  File "nn_style.py", line 37, in run
    vgg = self._load_vgg()
  File "nn_style.py", line 55, in _load_vgg
    return models.vgg19( pretrained=True,  ).features.cuda()
  File "/nn/src/lib/pytorch_vision/torchvision/models/vgg.py", line 141, in vgg19
    model.load_state_dict(model_zoo.load_url(model_urls['vgg19']))
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/model_zoo.py", line 57, in load_url
    return torch.load(cached_file)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 248, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 314, in _load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "/usr/lib/python3.5/tarfile.py", line 1575, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python3.5/tarfile.py", line 1605, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.5/tarfile.py", line 1470, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python3.5/tarfile.py", line 2291, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

**Comment by soumith** [comment]
are you on the latest pytorch? v0.1.10 ?

**Comment by yobajnin** [comment]
That was it - I was on an older version of pytorch.  Works now - thanks.
