### ISSUE TITLE
MultiScaleRoIAlign creates a type mismatch when using mixed precision training with Apex

### ISSUE THREAD

**Issue by Anjum48** [pytorch/vision#1335]
## To Reproduce

1. Use this tutorial https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html
2. Initialize the model & optimizer using `model, optimizer = apex.amp.initialize(model, optimizer, opt_level="O1")` 
3. Modify `engine.py` to use a scaled loss:
```
optimizer.zero_grad()
# losses.backward()

with amp.scale_loss(losses, optimizer) as scaled_loss:
    scaled_loss.backward()
```

## Expected behavior
There is a type mismatch here: https://github.com/pytorch/vision/blob/master/torchvision/ops/poolers.py#L161 with `per_level_feature` being `float16` and `rois_per_level` being `float32`

I made a workaround like this:
```
if per_level_feature.dtype != rois_per_level.dtype:
    rois_per_level = rois_per_level.type(per_level_feature.dtype)
```
But I suspect there is a more robust way or ensuring the ROI data types are consistent

**Comment by fmassa** [comment]
@Anjum48 I've sent a PR in https://github.com/pytorch/vision/pull/1341 to try to fix this, can you let me know if it works for you?

**Comment by Anjum48** [comment]
Thanks for the quick PR! I'm still getting a similar error to before:

```
Traceback (most recent call last):
  File "/home/anjum/PycharmProjects/kaggle/open_images_2019/object_detection/resnet.py", line 278, in <module>
    main(args)
  File "/home/anjum/PycharmProjects/kaggle/open_images_2019/object_detection/resnet.py", line 174, in main
    train_one_epoch(model, optimizer, train_loader, device, epoch, print_freq=100)
  File "/home/anjum/PycharmProjects/kaggle/open_images_2019/references/detection/engine.py", line 31, in train_one_epoch
    loss_dict = model(images, targets)
  File "/home/anjum/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anjum/anaconda3/lib/python3.7/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/home/anjum/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anjum/anaconda3/lib/python3.7/site-packages/torchvision/models/detection/generalized_rcnn.py", line 52, in forward
    detections, detector_losses = self.roi_heads(features, proposals, images.image_sizes, targets)
  File "/home/anjum/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anjum/anaconda3/lib/python3.7/site-packages/torchvision/models/detection/roi_heads.py", line 540, in forward
    box_features = self.box_roi_pool(features, proposals, image_shapes)
  File "/home/anjum/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anjum/anaconda3/lib/python3.7/site-packages/torchvision/ops/poolers.py", line 166, in forward
    spatial_scale=scale, sampling_ratio=self.sampling_ratio
  File "/home/anjum/anaconda3/lib/python3.7/site-packages/torchvision/ops/roi_align.py", line 69, in roi_align
    return _RoIAlignFunction.apply(input, rois, output_size, spatial_scale, sampling_ratio)
  File "/home/anjum/anaconda3/lib/python3.7/site-packages/torchvision/ops/roi_align.py", line 24, in forward
    output_size[0], output_size[1], sampling_ratio)
RuntimeError: Expected tensor for argument #1 'input' to have the same type as tensor for argument #2 'rois'; but type Variable[CUDAHalfType] does not equal Variable[CUDAFloatType] (while checking arguments for ROIAlign_forward_cuda) (checkSameType at /opt/conda/conda-bld/pytorch_1565272271120/work/aten/src/ATen/TensorUtils.cpp:140)
```
Adding my workaround above helps it get working again.

**Comment by Anjum48** [comment]
Does this tensor need it's `dtype` set in the same manner? https://github.com/pytorch/vision/blob/master/torchvision/ops/poolers.py#L101

**Comment by fmassa** [comment]
@Anjum48 that part doesn't need a dtype I think, because we convert it to a python number just afterwards.

I'll try debugging it further then, but thanks for the heads up that this wasn't enough

**Comment by fmassa** [comment]
Found a fix, will be pushing it to that PR shortly
