### ISSUE TITLE
Scripting torchvision.models.detection.maskrcnn_resnet50_fpn failed

### ISSUE THREAD

**Issue by chifredhong** [pytorch/vision#1548]
When I convert mask rcnn in torchvision,
```
import torch
import torchvision
from torchvision import transforms
from PIL import Image
import json
import cv2
import torch.onnx
 
model = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True)
model.eval() 
 
example = torch.rand(1,3, 300, 400)

traced_script_module = torch.jit.trace(model, example)
output = traced_script_module(torch.ones(1,3, 300, 400))
traced_script_module.save("model.pt")
```
then,get errors bellow
```
/home/chifred/.local/lib/python3.5/site-packages/torch/tensor.py:442: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  'incorrect results).', category=RuntimeWarning)
/home/chifred/.local/lib/python3.5/site-packages/torchvision/ops/poolers.py:122: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  scale = 2 ** torch.tensor(approx_scale).log2().round().item()
Traceback (most recent call last):
  File "convert_mask_rcnn.py", line 26, in <module>
    traced_script_module = torch.jit.trace(model, example)
  File "/home/chifred/.local/lib/python3.5/site-packages/torch/jit/__init__.py", line 880, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/home/chifred/.local/lib/python3.5/site-packages/torch/jit/__init__.py", line 1020, in trace_module
    module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, _force_outplace)
  File "/home/chifred/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/chifred/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 525, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/chifred/.local/lib/python3.5/site-packages/torchvision/models/detection/generalized_rcnn.py", line 52, in forward
    detections, detector_losses = self.roi_heads(features, proposals, images.image_sizes, targets)
  File "/home/chifred/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/chifred/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 525, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/chifred/.local/lib/python3.5/site-packages/torchvision/models/detection/roi_heads.py", line 631, in forward
    box_features = self.box_roi_pool(features, proposals, image_shapes)
  File "/home/chifred/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/chifred/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 525, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/chifred/.local/lib/python3.5/site-packages/torchvision/ops/poolers.py", line 155, in forward
    self.setup_scales(x, image_shapes)
  File "/home/chifred/.local/lib/python3.5/site-packages/torchvision/ops/poolers.py", line 129, in setup_scales
    scales = [self.infer_scale(feat, original_input_shape) for feat in features]
  File "/home/chifred/.local/lib/python3.5/site-packages/torchvision/ops/poolers.py", line 129, in <listcomp>
    scales = [self.infer_scale(feat, original_input_shape) for feat in features]
  File "/home/chifred/.local/lib/python3.5/site-packages/torchvision/ops/poolers.py", line 122, in infer_scale
    scale = 2 ** torch.tensor(approx_scale).log2().round().item()
RuntimeError: log2_vml_cpu not implemented for 'Long'
```
my torch and torchvision verison is **1.4.0.dev20191031+cpu, 0.5.0.dev20191031+cpu**

**Comment by fmassa** [comment]
Hi,

This will be fixed once https://github.com/pytorch/vision/pull/1407 gets merged. In the meantime, let's keep the discussion in https://github.com/pytorch/vision/issues/1002
