### ISSUE TITLE
GeneralizedRCNNTransform doesn't work with four-channel inputs

### ISSUE THREAD

**Issue by ZhiangChen** [pytorch/vision#1630]
When I modify the input channel of FasterRCNN from 3 to 4, GeneralizedRCNNTransform doesn't work.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/generalized_rcnn.py", line 47, in forward
    images, targets = self.transform(images, targets)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/transform.py", line 40, in forward
    image = self.normalize(image)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/transform.py", line 55, in normalize
    return (image - mean[:, None, None]) / std[:, None, None]
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0
```

**Comment by ZhiangChen** [comment]
I solved this problem by setting the same dimension for `image_std` and `image_mean`.

**Comment by fmassa** [comment]
That's indeed the correct solution. Let us know if you have further issues
