### ISSUE TITLE
RuntimeError after moving fasterrcnn_resnet50_fpn to CPU from GPU

### ISSUE THREAD

**Issue by anhydrous99** [pytorch/vision#1738]
Hello, when using the fasterrcnn_resnet50_fpn model, I noticed I got an error when training on the GPU then running it, in eval mode, on the CPU.
```
Traceback (most recent call last):
  File "/home/ubrdog/PycharmProjects/FacialDetection/bug_replication.py", line 17, in <module>
    out_data2 = model(dummy_data)
  File "/home/ubrdog/miniconda3/envs/FacialDetection/lib/python3.7/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubrdog/miniconda3/envs/FacialDetection/lib/python3.7/site-packages/torchvision-0.5.0a0+61763fa-py3.7-linux-x86_64.egg/torchvision/models/detection/generalized_rcnn.py", line 70, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/ubrdog/miniconda3/envs/FacialDetection/lib/python3.7/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubrdog/miniconda3/envs/FacialDetection/lib/python3.7/site-packages/torchvision-0.5.0a0+61763fa-py3.7-linux-x86_64.egg/torchvision/models/detection/rpn.py", line 472, in forward
    proposals = self.box_coder.decode(pred_bbox_deltas.detach(), anchors)
  File "/home/ubrdog/miniconda3/envs/FacialDetection/lib/python3.7/site-packages/torchvision-0.5.0a0+61763fa-py3.7-linux-x86_64.egg/torchvision/models/detection/_utils.py", line 187, in decode
    rel_codes.reshape(box_sum, -1), concat_boxes
  File "/home/ubrdog/miniconda3/envs/FacialDetection/lib/python3.7/site-packages/torchvision-0.5.0a0+61763fa-py3.7-linux-x86_64.egg/torchvision/models/detection/_utils.py", line 218, in decode_single
    pred_ctr_x = dx * widths[:, None] + ctr_x[:, None]
RuntimeError: expected device cpu but got device cuda:0
```
Here is some code to replicate it:
```
import torch
import torchvision
cpu_device = torch.device('cpu')
cuda_device = torch.device('cuda:0')
model = torchvision.models.detection.fasterrcnn_resnet50_fpn()
model.to(cuda_device)

dummy_data = torch.rand(1, 3, 256, 256, device=cuda_device)
dummy_target = [{'boxes': torch.rand(2, 4, device=cuda_device), 'labels': torch.ones(2, device=cuda_device, dtype=torch.int64)}]
out_data1 = model(dummy_data, dummy_target)
model.eval()

dummy_data = dummy_data.to(cpu_device)
model = model.to(cpu_device)
out_data2 = model(dummy_data)
```
A quick workaround I found is to move the cell_anchors in the anchor generator to the CPU.
```
model.rpn.anchor_generator.cell_anchors = [cell_anchor.to(cpu_device) for cell_anchor in model.rpn.anchor_generator.cell_anchors]
```
I am using the master branch for both torchvision & pytorch on linux.
Thank you.

**Comment by fmassa** [comment]
Thanks for the bug report!

This should be fixed in https://github.com/pytorch/vision/pull/1745
