### ISSUE TITLE
Failed to load fasterrcnn_resnet50_fpn by libtorch

### ISSUE THREAD

**Issue by ljd16** [pytorch/vision#1849]
There is no detailed documentation on loading fasterrcnn_resnet50_fpn by libtorch.
I change the c++ code by following [[1407]](https://github.com/pytorch/vision/pull/1407#issuecomment-562096191)
```
#include <torch/script.h> // One-stop header.
#include <iostream>
#include <memory>

#include <iostream>
#include "torch/script.h"
#include "torch/torch.h"
#include "torchvision/vision.h"
#include "torchvision/ROIAlign.h"
#include "torchvision/ROIPool.h"
#include "torchvision/empty_tensor_op.h"
#include "torchvision/nms.h"
#include <cuda.h>

using namespace std;

static auto registry =
        torch::RegisterOperators()
                .op("torchvision::nms", &nms)
                .op("torchvision::roi_align(Tensor input, Tensor rois, float spatial_scale, int pooled_height, int pooled_width, int sampling_ratio) -> Tensor",
                    &roi_align)
                .op("torchvision::roi_pool", &roi_pool)
                .op("torchvision::_new_empty_tensor_op", &new_empty_tensor);


int main(int argc, const char* argv[]) {
  if (argc != 2) {
    std::cerr << "usage: example-app <path-to-exported-script-module>\n";
    return -1;
  }


  torch::jit::script::Module module;
  try {
    // Deserialize the ScriptModule from a file using torch::jit::load().
    module = torch::jit::load(argv[1]);
  }
  catch (const c10::Error& e) {
    std::cerr << "error loading the model\n";
    return -1;
  }
```

- errors

```
CMakeFiles/example-app.dir/example-app.cpp.o: In function `ROIAlign_forward(at::Tensor const&, at::Tensor const&, double, long, long, long)':
example-app.cpp:(.text+0x128f): undefined reference to `ROIAlign_forward_cpu(at::Tensor const&, at::Tensor const&, float, int, int, int)'
CMakeFiles/example-app.dir/example-app.cpp.o: In function `ROIAlign_backward(at::Tensor const&, at::Tensor const&, float, int, int, int, int, int, int, int)':
example-app.cpp:(.text+0x14bd): undefined reference to `ROIAlign_backward_cpu(at::Tensor const&, at::Tensor const&, float, int, int, int, int, int, int, int)'
CMakeFiles/example-app.dir/example-app.cpp.o: In function `ROIPool_forward(at::Tensor const&, at::Tensor const&, double, long, long)':
example-app.cpp:(.text+0x1796): undefined reference to `ROIPool_forward_cpu(at::Tensor const&, at::Tensor const&, float, int, int)'
CMakeFiles/example-app.dir/example-app.cpp.o: In function `ROIPool_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, float, int, int, int, int, int, int)':
example-app.cpp:(.text+0x19cc): undefined reference to `ROIPool_backward_cpu(at::Tensor const&, at::Tensor const&, at::Tensor const&, float, int, int, int, int, int, int)'
CMakeFiles/example-app.dir/example-app.cpp.o: In function `nms(at::Tensor const&, at::Tensor const&, double)':
example-app.cpp:(.text+0x1d40): undefined reference to `nms_cpu(at::Tensor const&, at::Tensor const&, float)'
collect2: error: ld returned 1 exit status
CMakeFiles/example-app.dir/build.make:110: recipe for target 'example-app' failed
make[2]: *** [example-app] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/example-app.dir/all' failed
make[1]: *** [CMakeFiles/example-app.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error **2**
```

- *.h files

```
#include "torchvision/vision.h"
#include "torchvision/ROIAlign.h"
#include "torchvision/ROIPool.h"
#include "torchvision/empty_tensor_op.h"
#include "torchvision/nms.h"
```

These *.h files are copied from https://github.com/pytorch/vision/tree/v0.5.0/torchvision/csrc

- model saved code

```
import torch
import numpy as np
from PIL import Image
from torchvision import transforms
from torchvision.models.detection import fasterrcnn_resnet50_fpn

model = fasterrcnn_resnet50_fpn(pretrained=True)
im =Image.open('Himalayan-seated.jpg')
transform = transforms.Compose([
    transforms.Resize((500, 500)),
    transforms.ToTensor(),])
im_input = transform(im).unsqueeze(0)
model.eval()
predictions = model(im_input)

torch._C._jit_set_profiling_executor(False)
traced_model = torch.jit.script(model)

torch.jit.save(traced_model, 'rcnn.pt')
load_model = torch.jit.load('rcnn.pt')
```

- CMakeLists.txt

```
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH=/path/to/libtorch ..
cmake --build . --config Release
```

- envs

```
libtorch: https://download.pytorch.org/libtorch/nightly/cu101/libtorch-shared-with-deps-latest.zip
PyTorch version: 1.5.0.dev20200204
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.6.2

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: 10.1.243

Nvidia driver version: 430.40
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.3

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.5.0.dev20200204
[pip] torchvision==0.6.0a0+7741c84
[conda] blas                      1.0                         mkl    defaults
[conda] mkl                       2019.4                      243    defaults
[conda] mkl-service               2.3.0            py38he904b0f_0    defaults
[conda] mkl_fft                   1.0.15           py38ha843d7b_0    defaults
[conda] mkl_random                1.1.0            py38h962f231_0    defaults
[conda] pytorch                   1.5.0.dev20200204 py3.8_cuda10.1.243_cudnn7.6.3_0    pytorch-nightly
[conda] torchvision               0.6.0.dev20200204      py38_cu101    pytorch-nightly
```

**Comment by bmanga** [comment]
@ljd16 have you tried installing the library and using the config package? You shouldn't need to copy the header files manually.

Here's a list of commands that should work (on linux):
* Ensure you have python development libraries (eg. `sudo apt install python3-dev`)
* Install [pybind11](https://github.com/pybind/pybind11) (not needed after #1850)
* Build and install torchvision:
```
git clone https://github.com/pytorch/vision.git
cd vision
mkdir build && cd build
cmake -DCMAKE_PREFIX_PATH=/path/to/libtorch -DCMAKE_INSTALL_PREFIX=/where/to/install/torchvision -DCMAKE_BUILD_TYPE=Release [-DWITH_CUDA=ON] ..
cmake --build . [-j n]
cmake --install .
```
* In your project's CMakeLists.txt:
```
[...]
find_package(TorchVision REQUIRED)
target_link_libraries(target-name PUBLIC TorchVision::TorchVision)
[...]
```
* When invoking cmake in your project's build folder:
```
cmake -DCMAKE_PREFIX_PATH="/path/to/libtorch;/where/to/install/torchvision" [other options] ..
```

**Comment by ljd16** [comment]
Thanks for you reply.
This is works on cpu, but still exists error on gpu.
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Not compiled with GPU support
The above operation failed in interpreter.
Traceback (most recent call last):
Serialized   File "code/__torch__/torchvision/ops/boxes.py", line 41
    _11 = torch.slice(offsets, 0, 0, 9223372036854775807, 1)
    boxes_for_nms = torch.add(boxes, torch.unsqueeze(_11, 1), alpha=1)
    _9 = __torch__.torchvision.ops.boxes.nms(boxes_for_nms, scores, iou_threshold, )
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
  return _9
def box_area(boxes: Tensor) -> Tensor:
  File "/home/leijd/anaconda3/envs/py37torch14/lib/python3.8/site-packages/torchvision/ops/boxes.py", line 36
        by NMS, sorted in decreasing order of scores
    """
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
           ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
Serialized   File "code/__torch__/torchvision/ops/boxes.py", line 54, in nms
    scores: Tensor,
    iou_threshold: float) -> Tensor:
  _18 = ops.torchvision.nms(boxes, scores, iou_threshold)
        ~~~~~~~~~~~~~~~~~~~ <--- HERE
  return _18

Aborted (core dumped)
```

- torchvision's CMakeLists.txt and `cmake version 3.13.0`

```
+set(pybind11_DIR /path/to/pybind11/share/cmake/pybind11)

@@ -47,7 +49,8 @@ install(FILES ${CMAKE_CURRENT_BINARY_DIR}/TorchVisionConfig.cmake
   DESTINATION ${TORCHVISION_CMAKECONFIG_INSTALL_DIR})

 install(TARGETS ${PROJECT_NAME}
-  EXPORT TorchVisionTargets)
+  EXPORT TorchVisionTargets
+  DESTINATION lib)
```
- Build and install torchvision:
```
git clone https://github.com/pytorch/vision.git
cd vision
cd build && rm * -rf
cmake -DCMAKE_PREFIX_PATH=/path/to/libtorch -DCMAKE_INSTALL_PREFIX=/path/to/torchvision -DCMAKE_BUILD_TYPE=Release -DWITH_CUDA=ON ..
cmake --build . -j 20
cmake --install .
make install
```
- project's CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(custom_ops)

set(pybind11_DIR /path/to/pybind11/share/cmake/pybind11)

find_package(Torch REQUIRED)
find_package(TorchVision REQUIRED)

add_executable(example-app example-app.cpp)
target_link_libraries(example-app "${TORCH_LIBRARIES}" TorchVision::TorchVision)
set_property(TARGET example-app PROPERTY CXX_STANDARD 14)
```
- envs:
```
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.13.0

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: 10.1.243

Nvidia driver version: 430.40
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.3

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] blas                      1.0                         mkl    defaults
[conda] mkl                       2019.4                      243    defaults
[conda] mkl-service               2.3.0            py38he904b0f_0    defaults
[conda] mkl_fft                   1.0.15           py38ha843d7b_0    defaults
[conda] mkl_random                1.1.0            py38h962f231_0    defaults
[conda] pytorch                   1.4.0           py3.8_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.5.0                py38_cu101    pytorch
```

**Comment by bmanga** [comment]
@ljd16 can you try adding `add_compile_definitions(WITH_CUDA)` to your project's cmake?

**Comment by ljd16** [comment]
Great, it works!

**Comment by fmassa** [comment]
@bmanga @ljd16 could you send a PR to torchvision adding instructions on how to compile the code which uses faster rcnn such that it works on libtorch?

**Comment by bmanga** [comment]
@fmassa I can volunteer to update the README. Maybe it makes sense to wait until #1850 and #1843 are merged before doing that though?

**Comment by fmassa** [comment]
@bmanga sounds good, I think indeed that updating the README once we merge those PRs is better
