### ISSUE TITLE
cannot import name 'Basetransform' from 'data' (/root/Training_SSD/data/__init__.py)

### ISSUE THREAD

**Issue by Umairali2562** [pytorch/vision#1890]
HI i need some help here please if you could 

i am running ubuntu 19 on raspberry pi 3B+  

root@ubuntu:~/Training_SSD# uname -a
Linux ubuntu 5.3.0-1017-raspi2 #19-Ubuntu SMP Thu Jan 16 18:25:50 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

previously i had 71.arm because i had installed raspbeian sketched  and it was so much pain to install  torch and torchvision on it , so i installed ubuntu instead since it provides 64 arch , and i tried every possible means to install torch and torchvision , from  pip, pip3 , conda etc everything ..

but none work so few days ago i found some whl files here 

https://github.com/nmilosev/pytorch-arm-builds

and by using this tutorial 
https://www.youtube.com/watch?v=Ymugp9kRRT0

i was succesfully able to install it but now when i try to run my ssd.py it gives me this error 

 ```
root@ubuntu:~/Training_SSD# python3 ok.py
 Traceback (most recent call last):
   File "ok.py", line 4, in <module>
     from data import Basetransform, VOC_CLASSES as labelmap
   File "/root/Training_SSD/data/__init__.py", line 1, in <module>
     from .voc0712 import VOCDetection, AnnotationTransform, detection_collate, VOC_CLASSES
   File "/root/Training_SSD/data/voc0712.py", line 14, in <module>
     import torchvision.transforms as transforms
   File "/root/.local/lib/python3.7/site-packages/torchvision/__init__.py", line 2, in <module>
     from torchvision import datasets
   File "/root/.local/lib/python3.7/site-packages/torchvision/datasets/__init__.py", line 9, in <module>
     from .fakedata import FakeData
   File "/root/.local/lib/python3.7/site-packages/torchvision/datasets/fakedata.py", line 3, in <module>
     from .. import transforms
   File "/root/.local/lib/python3.7/site-packages/torchvision/transforms/__init__.py", line 1, in <module>
     from .transforms import *
   File "/root/.local/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 17, in <module>
    from . import functional as F
   File "/root/.local/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 5, in <module>
     from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
 ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/usr/local/lib/python3.7/dist-packages/PIL/__init__.py)
 root@ubuntu:~/Training_SSD#    from .voc0712 import VOCDetection, AnnotationTransform, detection_collate, VOC_CLASSES
 from: can't read /var/mail/.voc0712
 root@ubuntu:~/Training_SSD#   File "/root/Training_SSD/data/voc0712.py", line 14, in <module>
 -bash: syntax error near unexpected token `newline'
```
 
 

SO i fixed by installing the old version of pillow 

after seeing the issue #1846 

but now it's giving me a new error :+1: 

```
root@ubuntu:~/Training_SSD# python3 ok.py
Traceback (most recent call last):
  File "ok.py", line 4, in <module>
    from data import Basetransform, VOC_CLASSES as labelmap
ImportError: cannot import name 'Basetransform' from 'data' (/root/Training_SSD/data/__init__.py)

```

Would someone help ? Thanks in advance

**Comment by fmassa** [comment]
Hi,

I think that this error that you are getting is not in torchvision, as
```
Traceback (most recent call last):
  File "ok.py", line 4, in <module>
    from data import Basetransform, VOC_CLASSES as labelmap
ImportError: cannot import name 'Basetransform' from 'data' (/root/Training_SSD/data/__init__.py)
```
is not present in torchvision

As such, I'm closing the issue but let us know if you have further questions

**Comment by Umairali2562** [comment]
it did resolved when updated my ubuntu and restart it .
