### ISSUE TITLE
Win10 Python2.7  RuntimeError: generic_type: cannot initialize type "TensorProtoDataType": an object with that name is already defined

### ISSUE THREAD

**Issue by ZTZ-99** [pytorch/vision#1897]
我在Win10平台上用MSVC14.20为Python2.7构建了torchvision v0.3.0，但是在执行import torchvision时，出现以下错误：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win-amd64\egg\torchvision\__init__.py", line 9, in <module>

  File "build\bdist.win-amd64\egg\torchvision\version.py", line 3, in <module>
  File "build\bdist.win-amd64\egg\torchvision\_C.py", line 7, in <module>
  File "build\bdist.win-amd64\egg\torchvision\_C.py", line 6, in __bootstrap__
RuntimeError: generic_type: cannot initialize type "TensorProtoDataType": an object with that name is already defined
再次执行import torchvision，错误改变：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win-amd64\egg\torchvision\__init__.py", line 1, in <module>
    __all__ = list("Qt" + body for body in
ImportError: cannot import name models
我尝试更换版本，此问题依然存在。

**Comment by peterjc123** [comment]
It is because a bug that it is accidentally depending on the `_C` function at the PyTorch side. Please try this patch: https://github.com/pytorch/vision/pull/1779/files.

**Comment by datumbox** [comment]
This issue appears to be stale, so I'm closing it. If you think it should remain open, feel free to reopen it.
