### ISSUE TITLE
Mask RCNN ONNX export  KeyError: '_new_empty_tensor_op'

### ISSUE THREAD

**Issue by engineer1109** [pytorch/vision#1910]
System Ubuntu 18.04
Torch 1.4.0
Torchvision 0.5.0  pip installed

I have tried the examples you give in the tutorial:
`import torch`
`import torchvision`
`model = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True)`
`model.eval()`
`model=model.cuda()`
`test_data = torch.rand(1,3,300,400).cuda()`
`traced_model = torch.jit.trace(model, test_data)`

But got this error:

/usr/local/lib/python3.6/dist-packages/torch/tensor.py:461: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  'incorrect results).', category=RuntimeWarning)
/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/roi_heads.py:392: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(M + 2 * padding).to(torch.float32) / torch.tensor(M).to(torch.float32)
/usr/local/lib/python3.6/dist-packages/torch/onnx/symbolic_opset9.py:1951: UserWarning: Exporting aten::index operator of advanced indexing in opset 11 is achieved by combination of multiple ONNX operators, including Reshape, Transpose, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
  "If indices include negative values, the exported graph will produce incorrect results.")
/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py:716: UserWarning: ONNX export failed on custom operator torchvision::_new_empty_tensor_op because torch.onnx.symbolic_opset11._new_empty_tensor_op does not exist. Have you registered your symbolic function with torch.onnx.register_custom_op_symbolic(symbolic_name, symbolic_fn)?
  .format(ns, op_name, opset_version, op_name))
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    torch.onnx.export(model, x, "mask_rcnn.onnx", opset_version = 11)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 416, in _export
    fixed_batch_size=fixed_batch_size)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 296, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 135, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/__init__.py", line 179, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 717, in _run_symbolic_function
    symbolic_fn = sym_registry.get_registered_op(op_name, ns, opset_version)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/symbolic_registry.py", line 91, in get_registered_op
    return _registry[(domain, version)][opname]
KeyError: '_new_empty_tensor_op'

**Comment by engineer1109** [comment]
fastrcnn export onnx is ok.  strange.

**Comment by fmassa** [comment]
Hi,

We support exporting the models to torchscript via `torch.jit.script`, but not via `torch.jit.trace`.

Converting the models via ONNX doesn't use the standard `torch.jit.trace` code-path, and should work fine.

Let us know if you have further questions.

**Comment by engineer1109** [comment]
@fmassa,
You mean the tutorials document is fake?
https://pytorch.org/docs/master/torchvision/models.html#object-detection-instance-segmentation-and-person-keypoint-detection

**Comment by fmassa** [comment]
@engineer1109 could you expand on why you think it's fake?

We do support torchscript via `torch.jit.script`, and we do support exporting to ONNX via `torch.onnx.export`.

**Comment by engineer1109** [comment]
@fmassa sorry,  I paste the code wrongly.
It is the "torch.onnx.export(model, x, "mask_rcnn.onnx", opset_version = 11)" failed.
Not matter about trace.

File "test.py", line 9, in
torch.onnx.export(model, x, "mask_rcnn.onnx", opset_version = 11)

model = torchvision.models.detection.keypointrcnn_resnet50_fpn(pretrained=True)
model.eval()
x = [torch.rand(3, 300, 400), torch.rand(3, 500, 400)]
predictions = model(x)

# optionally, if you want to export the model to ONNX:
torch.onnx.export(model, x, "keypoint_rcnn.onnx", opset_version = 11)

**Comment by fmassa** [comment]
@engineer1109 Can you paste what the error message that you get is?

**Comment by robotrovsky** [comment]
@fmassa i have the same problem following example code from torchvision/models/detection/mask_rcnn.py:

```

model = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True)
model.eval()
x = [torch.rand(3, 300, 400), torch.rand(3, 500, 400)]
predictions = model(x)

# optionally, if you want to export the model to ONNX:
torch.onnx.export(model, x, "mask_rcnn.onnx", opset_version = 11)
```

Results in:

```
KeyError                                  Traceback (most recent call last)
<ipython-input-25-f50771bd7b1a> in <module>
      5 
      6 # optionally, if you want to export the model to ONNX:
----> 7 torch.onnx.export(model, x, "mask_rcnn.onnx", opset_version = 11)

~/.local/lib/python3.6/site-packages/torch/onnx/__init__.py in export(model, args, f, export_params, verbose, training, input_names, output_names, aten, export_raw_ir, operator_export_type, opset_version, _retain_param_name, do_constant_folding, example_outputs, strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
    146                         operator_export_type, opset_version, _retain_param_name,
    147                         do_constant_folding, example_outputs,
--> 148                         strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
    149 
    150 

~/.local/lib/python3.6/site-packages/torch/onnx/utils.py in export(model, args, f, export_params, verbose, training, input_names, output_names, aten, export_raw_ir, operator_export_type, opset_version, _retain_param_name, do_constant_folding, example_outputs, strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
     64             _retain_param_name=_retain_param_name, do_constant_folding=do_constant_folding,
     65             example_outputs=example_outputs, strip_doc_string=strip_doc_string,
---> 66             dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
     67 
     68 

~/.local/lib/python3.6/site-packages/torch/onnx/utils.py in _export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, export_type, example_outputs, propagate, opset_version, _retain_param_name, do_constant_folding, strip_doc_string, dynamic_axes, keep_initializers_as_inputs, fixed_batch_size)
    414                                                         example_outputs, propagate,
    415                                                         _retain_param_name, do_constant_folding,
--> 416                                                         fixed_batch_size=fixed_batch_size)
    417 
    418         # TODO: Don't allocate a in-memory string for the protobuf

~/.local/lib/python3.6/site-packages/torch/onnx/utils.py in _model_to_graph(model, args, verbose, training, input_names, output_names, operator_export_type, example_outputs, propagate, _retain_param_name, do_constant_folding, _disable_torch_constant_prop, fixed_batch_size)
    294     graph = _optimize_graph(graph, operator_export_type,
    295                             _disable_torch_constant_prop=_disable_torch_constant_prop,
--> 296                             fixed_batch_size=fixed_batch_size, params_dict=params_dict)
    297 
    298     if isinstance(model, torch.jit.ScriptModule) or isinstance(model, torch.jit.ScriptFunction):

~/.local/lib/python3.6/site-packages/torch/onnx/utils.py in _optimize_graph(graph, operator_export_type, _disable_torch_constant_prop, fixed_batch_size, params_dict)
    133         torch._C._jit_pass_erase_number_types(graph)
    134 
--> 135         graph = torch._C._jit_pass_onnx(graph, operator_export_type)
    136         torch._C._jit_pass_lint(graph)
    137 

~/.local/lib/python3.6/site-packages/torch/onnx/__init__.py in _run_symbolic_function(*args, **kwargs)
    177 def _run_symbolic_function(*args, **kwargs):
    178     from torch.onnx import utils
--> 179     return utils._run_symbolic_function(*args, **kwargs)
    180 
    181 

~/.local/lib/python3.6/site-packages/torch/onnx/utils.py in _run_symbolic_function(g, n, inputs, env, operator_export_type)
    715                               "torch.onnx.register_custom_op_symbolic(symbolic_name, symbolic_fn)?"
    716                               .format(ns, op_name, opset_version, op_name))
--> 717             symbolic_fn = sym_registry.get_registered_op(op_name, ns, opset_version)
    718             attrs = {k: n[k] for k in n.attributeNames()}
    719             return symbolic_fn(g, *inputs, **attrs)

~/.local/lib/python3.6/site-packages/torch/onnx/symbolic_registry.py in get_registered_op(opname, domain, version)
     89         warnings.warn("ONNX export failed. The ONNX domain and/or version are None.")
     90     global _registry
---> 91     return _registry[(domain, version)][opname]

KeyError: '_new_empty_tensor_op'
```

**Comment by fmassa** [comment]
@robotrovsky can you try updating pytorch and torchvision to a nightly version, I think there might be a clash somewhere in your environment.

**Comment by ResByte** [comment]
Hi @fmassa ,
I am having the same issue but errors have changed, I have update torch and torchvision to nightly. 

**versions**
```
torch: 1.6.0.dev20200331
torchvision: 0.6.0a0+5eb9f77
```

**code:**
```python
model = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True)
model.eval()
inputs = [torch.rand(3, 300, 300)]
predictions = model(inputs)
# convert to ONNX
torch.onnx.export(model, inputs, "model.onnx",
                  do_constant_folding=True,
                  opset_version=11  # opset_version 11 required for Mask R-CNN
                  )
```


**error log**: 
```
/opt/conda/conda-bld/pytorch_1585638457306/work/aten/src/ATen/native/BinaryOps.cpp:81: UserWarning: Integer division of tensors using div or / is deprecated, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.
/opt/conda/lib/python3.7/site-packages/torch/tensor.py:467: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  'incorrect results).', category=RuntimeWarning)
/opt/conda/lib/python3.7/site-packages/torchvision/models/detection/roi_heads.py:381: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(M + 2 * padding).to(torch.float32) / torch.tensor(M).to(torch.float32)
/opt/conda/lib/python3.7/site-packages/torch/onnx/symbolic_opset9.py:2120: UserWarning: Exporting aten::index operator of advanced indexing in opset 11 is achieved by combination of multiple ONNX operators, including Reshape, Transpose, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
  "If indices include negative values, the exported graph will produce incorrect results.")
/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py:800: UserWarning: ONNX export failed on primitive operator Uninitialized; please report a bug
  warnings.warn("ONNX export failed on primitive operator {}; please report a bug".format(op_name))
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-754e2b5cf14a> in <module>
      2 torch.onnx.export(model, inputs, "model.onnx",
      3                   do_constant_folding=True,
----> 4                   opset_version=11  # opset_version 11 required for Mask R-CNN
      5                   )

/opt/conda/lib/python3.7/site-packages/torch/onnx/__init__.py in export(model, args, f, export_params, verbose, training, input_names, output_names, aten, export_raw_ir, operator_export_type, opset_version, _retain_param_name, do_constant_folding, example_outputs, strip_doc_string, dynamic_axes, keep_initializers_as_inputs, custom_opsets, enable_onnx_checker, use_external_data_format)
    170                         do_constant_folding, example_outputs,
    171                         strip_doc_string, dynamic_axes, keep_initializers_as_inputs,
--> 172                         custom_opsets, enable_onnx_checker, use_external_data_format)
    173 
    174 

/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py in export(model, args, f, export_params, verbose, training, input_names, output_names, aten, export_raw_ir, operator_export_type, opset_version, _retain_param_name, do_constant_folding, example_outputs, strip_doc_string, dynamic_axes, keep_initializers_as_inputs, custom_opsets, enable_onnx_checker, use_external_data_format)
     90             dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs,
     91             custom_opsets=custom_opsets, enable_onnx_checker=enable_onnx_checker,
---> 92             use_external_data_format=use_external_data_format)
     93 
     94 

/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py in _export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, export_type, example_outputs, propagate, opset_version, _retain_param_name, do_constant_folding, strip_doc_string, dynamic_axes, keep_initializers_as_inputs, fixed_batch_size, custom_opsets, add_node_names, enable_onnx_checker, use_external_data_format)
    509                                                             example_outputs, propagate,
    510                                                             _retain_param_name, val_do_constant_folding,
--> 511                                                             fixed_batch_size=fixed_batch_size)
    512 
    513             # TODO: Don't allocate a in-memory string for the protobuf

/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py in _model_to_graph(model, args, verbose, input_names, output_names, operator_export_type, example_outputs, propagate, _retain_param_name, do_constant_folding, _disable_torch_constant_prop, fixed_batch_size)
    366     graph = _optimize_graph(graph, operator_export_type,
    367                             _disable_torch_constant_prop=_disable_torch_constant_prop,
--> 368                             fixed_batch_size=fixed_batch_size, params_dict=params_dict)
    369 
    370     if isinstance(model, torch.jit.ScriptModule) or isinstance(model, torch.jit.ScriptFunction):

/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py in _optimize_graph(graph, operator_export_type, _disable_torch_constant_prop, fixed_batch_size, params_dict)
    175         torch._C._jit_pass_erase_number_types(graph)
    176 
--> 177         graph = torch._C._jit_pass_onnx(graph, operator_export_type)
    178         torch._C._jit_pass_lint(graph)
    179 

/opt/conda/lib/python3.7/site-packages/torch/onnx/__init__.py in _run_symbolic_function(*args, **kwargs)
    201 def _run_symbolic_function(*args, **kwargs):
    202     from torch.onnx import utils
--> 203     return utils._run_symbolic_function(*args, **kwargs)
    204 
    205 

/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py in _run_symbolic_function(g, n, inputs, env, operator_export_type)
    791                 for b in n.blocks():
    792                     new_block = new_node.addBlock()
--> 793                     torch._C._jit_pass_onnx_block(b, new_block, operator_export_type, env)
    794                 return new_op_outputs
    795             else:

/opt/conda/lib/python3.7/site-packages/torch/onnx/__init__.py in _run_symbolic_function(*args, **kwargs)
    201 def _run_symbolic_function(*args, **kwargs):
    202     from torch.onnx import utils
--> 203     return utils._run_symbolic_function(*args, **kwargs)
    204 
    205 

/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py in _run_symbolic_function(g, n, inputs, env, operator_export_type)
    799                 if not is_exportable:
    800                     warnings.warn("ONNX export failed on primitive operator {}; please report a bug".format(op_name))
--> 801                 symbolic_fn = sym_registry.get_registered_op(symbolic_name, '', opset_version)
    802                 attrs = {k: n[k] for k in n.attributeNames()}
    803                 return symbolic_fn(g, *inputs, **attrs)

/opt/conda/lib/python3.7/site-packages/torch/onnx/symbolic_registry.py in get_registered_op(opname, domain, version)
    107         else:
    108             msg += "Please open a bug to request ONNX export support for the missing operator."
--> 109         raise RuntimeError(msg)
    110     return _registry[(domain, version)][opname]

RuntimeError: Exporting the operator prim_Uninitialized to ONNX opset version 11 is not supported. Please open a bug to request ONNX export support for the missing operator.

```

**Comment by fmassa** [comment]
@ResByte thanks for the feedback. @neginraoof do you know what this might be?

**Comment by ResByte** [comment]
@fmassa can I suggest to mark this issue open or link it related one?

**Comment by fmassa** [comment]
@ResByte can you create a new issue? Your error seems unrelated to the original issue

**Comment by ResByte** [comment]
thanks, raised a new issue here #2111 , please have a look.
