### ISSUE TITLE
NameError: name 'long' is not defined

### ISSUE THREAD

**Issue by dthboyd** [pytorch/vision#202]
show(make_grid(imglist, padding=100))

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-106-e27809616e9d> in <module>()
----> 1 show(make_grid(imglist, padding=100))
      2 

//anaconda/lib/python3.5/site-packages/torchvision-0.1.8-py3.5.egg/torchvision/utils.py in make_grid(tensor, nrow, padding, normalize, range, scale_each)
     26         tensorlist = tensor
     27         numImages = len(tensorlist)
---> 28         size = torch.Size(torch.Size([long(numImages)]) + tensorlist[0].size())
     29         tensor = tensorlist[0].new(size)
     30         for i in irange(numImages):

NameError: name 'long' is not defined

​

**Comment by soumith** [comment]
try this: `pip install https://github.com/pytorch/vision/archive/master.zip`

**Comment by dthboyd** [comment]
pip install https://github.com/pytorch/vision/archive/master.zip
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: pip==8.1.2
