### ISSUE TITLE
Use torch.jit.scripts to save the quantized inception_v3 error

### ISSUE THREAD

**Issue by aksenventwo** [pytorch/vision#2100]
## To Reproduce

```python
import torch
import torchvision.models.quantization as models

model = models.inception_v3(pretrained=True, progress=True, quantize=False)
model.to('cpu')
model.eval()
   
# Fuse Conv, bn and relu
model.fuse_model()
torch.jit.save(torch.jit.script(model), 'inception_v3_quantized_float.pth')
```

```shell
Traceback (most recent call last):
  File "resnt18.py", line 193, in <module>
    torch.jit.save(torch.jit.script(myModel), saved_model_dir + scripted_float_model_file)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1255, in script
    return torch.jit._recursive.recursive_script(obj)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 534, in recursive_script
    return create_script_module(nn_module, infer_methods_to_compile(nn_module))
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 296, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 340, in create_script_module_impl
    create_methods_from_stubs(concrete_type, stubs)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 259, in create_methods_from_stubs
    concrete_type._create_methods(defs, rcbs, defaults)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 574, in compile_unbound_method
    create_methods_from_stubs(concrete_type, (stub,))
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 259, in create_methods_from_stubs
    concrete_type._create_methods(defs, rcbs, defaults)
RuntimeError:
Module 'QuantizableInception3' has no attribute 'AuxLogits' :
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/inception.py", line 161
        aux_defined = self.training and self.aux_logits
        if aux_defined:
            aux = self.AuxLogits(x)
                  ~~~~~~~~~~~~~~ <--- HERE
        else:
            aux = None
'QuantizableInception3._forward' is being compiled since it was called from 'QuantizableInception3.forward'
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/quantization/inception.py", line 196
        x = self._transform_input(x)
        x = self.quant(x)
        x, aux = self._forward(x)
        ~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        x = self.dequant(x)
        aux_defined = self.training and self.aux_logits

```

## Expected behavior

Successfully saved

## Environment

Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026
CMake version: version 3.14.7

Python version: 3.6
Versions of relevant libraries:
[pip3] numpy==1.18.0
[pip3] pytorch2sg==0.1.0
[pip3] torch==1.4.0
[pip3] torchvision==0.5.0
[conda] Could not collect

**Comment by fmassa** [comment]
Hi,

Thanks for the report!

This has been fixed in for GoogleNet in https://github.com/pytorch/vision/pull/1949, but not for Inception I believe.

cc @eellison
