### ISSUE TITLE
size -> size() ?

### ISSUE THREAD

**Issue by makslevental** [pytorch/vision#2103]
traceback

```
Traceback (most recent call last):
  File "/Users/maksim/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/193.6911.25/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<string>", line 3, in <module>
  File "/Users/maksim/dev_projects/denoising-fluorescence/denoising/venv/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 247, in __call__
    return F.center_crop(img, self.size)
  File "/Users/maksim/dev_projects/denoising-fluorescence/denoising/venv/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 382, in center_crop
    image_width, image_height = img.size
TypeError: cannot unpack non-iterable builtin_function_or_method object
>>> img.size()
torch.Size([1, 1, 2160, 2560])
```

line with bug

https://github.com/pytorch/vision/blob/master/torchvision/transforms/functional.py#L374

my version numbers

```
torch==1.4.0
torchvision==0.5.0
```

**Comment by makslevental** [comment]
oh wait this is probably because i'm trying to crop a tensor. whoops. sorry!
