### ISSUE TITLE
Is segmentation necessary for keypoint r-cnn custom data training

### ISSUE THREAD

**Issue by esgnn** [pytorch/vision#2238]
I am trying to train with a custom dataset which has boxes, labels and keypoints. As far as I can tell from [keypoint_rcnn.py](https://github.com/pytorch/vision/blob/master/torchvision/models/detection/keypoint_rcnn.py) this is all I need. 
 ```
   During training, the model expects both the input tensors, as well as a targets (list of dictionary),
    containing:
        - boxes (FloatTensor[N, 4]): the ground-truth boxes in [x1, y1, x2, y2] format, with values of x
          between 0 and W and values of y between 0 and H
        - labels (Int64Tensor[N]): the class label for each ground-truth box
        - keypoints (FloatTensor[N, K, 3]): the K keypoints location for each of the N instances, in the
          format [x, y, visibility], where visibility=0 means that the keypoint is not visible.
```
However, when I try to train using [train.py](https://github.com/pytorch/vision/blob/master/references/detection/train.py) I receive the following error 

(I am using Colab and coco_utils.py and transforms.py path was at default directory)

```
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataset.py", line 257, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/content/coco_utils.py", line 219, in __getitem__
    img, target = self._transforms(img, target)
  File "/content/transforms.py", line 23, in __call__
    image, target = t(image, target)
  File "/content/coco_utils.py", line 59, in __call__
    anno = [obj for obj in anno if obj['iscrowd'] == 0]
  File "/content/coco_utils.py", line 59, in <listcomp>
    anno = [obj for obj in anno if obj['iscrowd'] == 0]
KeyError: 'iscrowd'
```
I added iscrowd and it threw error on segmentation. 
**My question:**
Do we really need segmentation and iscrowd to train? Is it ok to just remove parts related to those features?

**Comment by fmassa** [comment]
The model doesn't require segmentation maps, but the rest of the training code makes the assumption that it is present, see https://github.com/pytorch/vision/blob/7ffc9520a847bd94a61247f1bdc19a00e4165440/references/detection/coco_utils.py#L71-L72

You can safely remove those for your use-case.
