### ISSUE TITLE
'['ninja', '-v']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by puraminy** [pytorch/vision#2360]
## 🐛 Bug

When I tried to install the vision from source I got the following error:

`subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 255, in <module>
    'clean': clean,
  File "/home/ahmad/miniconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "/home/ahmad/miniconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/ahmad/miniconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/ahmad/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ahmad/miniconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/ahmad/miniconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/ahmad/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/ahmad/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ahmad/miniconda3/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 173, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/ahmad/miniconda3/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 159, in call_command
    self.run_command(cmdname)
  File "/home/ahmad/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/ahmad/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ahmad/miniconda3/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/ahmad/miniconda3/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/ahmad/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/ahmad/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ahmad/miniconda3/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/home/ahmad/miniconda3/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/ahmad/miniconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 644, in build_extensions
    build_ext.build_extensions(self)
  File "/home/ahmad/miniconda3/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/ahmad/miniconda3/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/ahmad/miniconda3/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/ahmad/miniconda3/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/ahmad/miniconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 473, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/ahmad/miniconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1228, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/ahmad/miniconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1524, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
`

## To Reproduce

1. Installing Pytorch from source (with cuda 10.2, python 3.7)
1. Cloning vision
1. python setup.py install

## Environment
OS: Ubuntu 20.04 LTS
GCC version: (Ubuntu 8.4.0-3ubuntu2) 8.4.0
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce GT 740M
Nvidia driver version: 440.33.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.7.0a0+502ec8f
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.0.130                      0  
[conda] magma-cuda102             2.5.2                         1    pytorch
[conda] mkl                       2020.1                      217  
[conda] mkl-include               2020.1                      217  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.1.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.18.5           py37ha1c710e_0  
[conda] numpy-base                1.18.5           py37hde5b4d6_0  
[conda] torch                     1.7.0a0+502ec8f          pypi_0    pypi

**Comment by fmassa** [comment]
Hi,

I can't reproduce this issue locally.

Can you post the full log of the error? It should indicate which part of the C++ extensions is failing to compile.

Additionally, I would recommend using the nightly builds whenever possible.

**Comment by puraminy** [comment]
@fmassa 
Hi, I pasted more log of the error in my question. Also I cloned the nightly branch and I got the same error.

**Comment by fmassa** [comment]
@puraminy from the extra line you added, the issue seems to be with the ffmpeg compilation, but the exact error that you have is not present, so it's hard to say what's going on. Can you paste more of the error ?

If you don't need the ffmpeg extensions for video reading, you can either disable them by making this `if False:` in https://github.com/pytorch/vision/blob/fa6af6d1e6f050d0a930e6f59894b7dd40aa869c/setup.py#L177
or installing from a nightly.

**Comment by puraminy** [comment]
@fmassa I attached a log file of the error, I mean by redirecting `python setup.py install > er.log`
I will test what you said about ffmpeg

`
[er.log](https://github.com/pytorch/vision/files/4858359/er.log)
`

**Comment by puraminy** [comment]
@fmassa  I disabled the ffmpeg and it was installed

**Comment by fmassa** [comment]
@puraminy the log was very helpful, thanks a lot!

So it seems that we managed to find `ffmpeg` in your system, but `libavcodec/avcodec.h` was not in the location that it was expected to be found.

Can you share a bit more information about your system?
For example, what is the output of
```
which ffmpeg
```
and can you try to find in your system if `libavcodec/avcodec.h` is defined somewhere? From our current scripts to locate it, we thought it would be in `/usr/include`.

**Comment by puraminy** [comment]
@fmassa 

`which ffmpeg` returns

```
/usr/bin/ffmpeg
```
I also ran `locate avcodec.h` and it returned:

/home/ahmad/src/avidemux_2.7.4/avidemux_core/ffmpeg_package/patches```
/libavcodec_avcodec.h.patch
/home/ahmad/src/avidemux_2.7.4/avidemux_plugins/ADM_audioEncoders/lavcodec/audioencoder_lavcodec.h

```

The attached file is for `locate libavcodec`
[codec.log](https://github.com/pytorch/vision/files/4858984/codec.log)

**Comment by fmassa** [comment]
Ok, thanks for the information!

We will try to improve our ffmpeg finding and package the optimized `video_reader` together with torchvision, so that compiling from source will not be necessary except for developers.

cc @andfoy

**Comment by dbl001** [comment]
I'm getting the same error on Catalina after cloning the nightly build.
I set  'has_ffmpeg = False' in setup.py.
Any ideas?
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 478, in <module>
    'clean': clean,
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 538, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1359, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```
[err.log](https://github.com/pytorch/vision/files/6266459/err.log)

**Comment by shivangibithel** [comment]
changing line 956 of /home/jiapy/virtualEnv/py3.6torch1.1/lib/python3.6/site-packages/torch/utils/cpp_extension.py from
['ninja', '-v']
to
['ninja', '--version']
seems solved the problem.

**Comment by fmassa** [comment]
@bjuncek can you try seeing if the proposed fix from @shivangibithel fix the issues for you, and if yes send a PR?

**Comment by bjuncek** [comment]
On it:

So here is my experience on a Mac with latest torchvision:
1. install pytorch from source with no issues
2a. Install with no ffmpeg installs without any issue:
```
[...]
Finished processing dependencies for torchvision==0.11.0a0+d7fa36f

(2360) ➜  vision git:(master) which ffmpeg
ffmpeg not found
```
2b. Installing ffmpeg via conda
```
conda install -c conda-forge ffmpeg=4.2
(2360) ➜  vision git:(master) which ffmpeg
/Users/bjuncek/bin/miniconda3/envs/2360/bin/ffmpeg
```

Runs into the following error
<details><summary> see error </summary>
<p>
```
NVJPEG found: False
dyld: Library not loaded: @rpath/libopenh264.5.dylib
  Referenced from: /Users/bjuncek/bin/miniconda3/envs/2360/lib/libavcodec.58.54.100.dylib
  Reason: image not found
Traceback (most recent call last):
  File "setup.py", line 501, in <module>
    ext_modules=get_extensions(),
  File "setup.py", line 355, in get_extensions
    ffmpeg_version_str = str(subprocess.check_output(["ffmpeg", "-version"]))
  File "/Users/bjuncek/bin/miniconda3/envs/2360/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/Users/bjuncek/bin/miniconda3/envs/2360/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ffmpeg', '-version']' died with <Signals.SIGABRT: 6>.
```
</p>
</details>

This is due likely due to ffmpeg from conda forge on a mac being messed up as the same error pops up when simply running ffmpeg. 

3. When I change the line same line (although for me on today's build at line 1680) in  `site-packages/torch` as suggested nothing change. 


4. I proceed to change the `has_ffmpeg` in setup.py to match user's config, and now nothing will install (`clang` errors out). 

5. Reverting step 3 and everything builds like it should.


### So conclusions:
1. ffmpeg from conda-forge on macs is dubious at best; there is no simple build recipe without brew I don't think at the moment.
2. I cannot recreate the issue from @dbl001 . I've seen these errors though, usually when there is a mix of conda-pytorch and built-from-source torchvision. Nothing in the log points me directly to ffmpeg in this case
3. Solution from @shivangibithel actually breaks my install; I wouldn't advise pushing it to torch upstream.

**Comment by andfoy** [comment]
@bjuncek, does openh264 gets installed on your failure scenario?

**Comment by powlook** [comment]
I have got the same problem when I tried to run setup.py for mmdetection.
Below are the snippets of the error trace : 
=========================
/home/plyap/anaconda3/envs/wda2/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:194:30: note: declared here
  194 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
/home/plyap/data/wda_tracker/detectors/mmdetection/mmdet/ops/nms/src/nms_cuda.cpp:4:23: error: ‘AT_CHECK’ was not declared in this scope; did you mean ‘DCHECK’?
    4 | #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
      |                       ^~~~~~~~
/home/plyap/data/wda_tracker/detectors/mmdetection/mmdet/ops/nms/src/nms_cuda.cpp:4:23: note: in definition of macro ‘CHECK_CUDA’
    4 | #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
      |                       ^~~~~~~~
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/plyap/anaconda3/envs/wda2/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1723, in _run_ninja_build
    env=env)
  File "/home/plyap/anaconda3/envs/wda2/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

**Comment by Lucyliuwen** [comment]
> changing line 956 of /home/jiapy/virtualEnv/py3.6torch1.1/lib/python3.6/site-packages/torch/utils/cpp_extension.py from ['ninja', '-v'] to ['ninja', '--version'] seems solved the problem.

It works! python3.8

**Comment by oabuhamdan** [comment]
> changing line 956 of /home/jiapy/virtualEnv/py3.6torch1.1/lib/python3.6/site-packages/torch/utils/cpp_extension.py from ['ninja', '-v'] to ['ninja', '--version'] seems solved the problem.

Worked for me!

**Comment by M747** [comment]
> changing line 956 of /home/jiapy/virtualEnv/py3.6torch1.1/lib/python3.6/site-packages/torch/utils/cpp_extension.py from ['ninja', '-v'] to ['ninja', '--version'] seems solved the problem.

Thank U 💯  This solution is worked for me 👍

**Comment by HHLiufighting** [comment]
> changing line 956 of /home/jiapy/virtualEnv/py3.6torch1.1/lib/python3.6/site-packages/torch/utils/cpp_extension.py from ['ninja', '-v'] to ['ninja', '--version'] seems solved the problem.

ImportError: /root/.cache/torch_extensions/py310_cu121/nvdiffrast_plugin_gl/nvdiffrast_plugin_gl.so: cannot open shared object file: No such file or directory

**Comment by rrayy-25809** [comment]
> changing line 956 of /home/jiapy/virtualEnv/py3.6torch1.1/lib/python3.6/site-packages/torch/utils/cpp_extension.py from ['ninja', '-v'] to ['ninja', '--version'] seems solved the problem.

Thank u so much It is work for me!

btw if we have to change the code of pytorch by ourselves, why didn't they update to use "--version" instead of "-v"?
I am just curious about it
