### ISSUE TITLE
Unable to load fasterrcnn state_dict with custom num_classes

### ISSUE THREAD

**Issue by devarshi16** [pytorch/vision#2555]
## 🐛 Bug

torchvision.models.detection.fasterrcnn_resnet50_fpn() giving error when the parameter pretrained is set to True and num_classes parameter is also supplied(other than 91). 

## To Reproduce

```
>> from torchvision import models
>> my_model = models.detection.fasterrcnn_resnet50_fpn(pretrained=True,num_classes=50)
```
The error that it gives
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/miniconda2/envs/form_ocr/lib/python3.7/site-packages/torchvision/models/detection/faster_rcnn.py", line 354, in fasterrcnn_resnet50_fpn
    model.load_state_dict(state_dict)
  File "/home/username/miniconda2/envs/form_ocr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FasterRCNN:
	size mismatch for roi_heads.box_predictor.cls_score.weight: copying a param with shape torch.Size([91, 1024]) from checkpoint, the shape in current model is torch.Size([50, 1024]).
	size mismatch for roi_heads.box_predictor.cls_score.bias: copying a param with shape torch.Size([91]) from checkpoint, the shape in current model is torch.Size([50]).
	size mismatch for roi_heads.box_predictor.bbox_pred.weight: copying a param with shape torch.Size([364, 1024]) from checkpoint, the shape in current model is torch.Size([200, 1024]).
	size mismatch for roi_heads.box_predictor.bbox_pred.bias: copying a param with shape torch.Size([364]) from checkpoint, the shape in current model is torch.Size([200]).

```

## Expected behavior

I was hoping it would load the state_dict on the base model and then change the `model.roi_heads.box_predictor.cls_score` layer.
Something like this perhaps,
```
from torchvision import models
import torch.nn as nn

class RCNN_Model(nn.Module):
    def __init__(self,pretrained=True,out_classes=91):
        super(RCNN_Model,self).__init__()
        self.model = models.detection.fasterrcnn_resnet50_fpn(pretrained=pretrained)#,num_classes=out_classes)
        if out_classes!=91:
            self.model.roi_heads.box_predictor.cls_score = nn.Linear(in_features=1024,out_features=out_classes,bias=True)
            
    def forward(self,x):
        return self.model(x)
```

## Environment

```
PyTorch version: 1.5.1
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.13.3
[pip3] torch==1.0.1.post2
[pip3] torchvision==0.4.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               9.0                  h13b8566_0  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.14           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] numpy                     1.17.4                   pypi_0    pypi
[conda] numpy-base                1.17.2           py37hde5b4d6_0  
[conda] pytorch-nightly           1.0.0.dev20190328 py3.7_cuda9.0.176_cudnn7.4.2_0    pytorch
[conda] torch                     1.5.1                    pypi_0    pypi
[conda] torchvision               0.6.1                    pypi_0    pypi
```

**Comment by fmassa** [comment]
Hi,

This is expected and all models in torchvision (including the classification and segmentation models) follow the same behavior.

The reason is that the concept of what should be kept and what should be changed can be ill-defined, and in order to avoid confusion on the user-side we just let it explicit to the user to decide what to keep and what to re-initialize from scratch.

I'm closing this issue, but let us know if you disagree with the reasoning.
