### ISSUE TITLE
Mask R-CNN converted via JIT fails to load in PyTorch Android

### ISSUE THREAD

**Issue by prabhuomkar** [pytorch/vision#2559]
## 🐛 Bug

**ERROR**:
```
com.facebook.jni.CppException: 
Tried to access nonexistent attribute or method 'cell_anchors' of type '__torch__.torchvision.models.detection.rpn.___torch_mangle_242.AnchorGenerator'. Did you forget to initialize an attribute in __init__()?:
Serialized   File "code/__torch__/torchvision/models/detection/mask_rcnn/___torch_mangle_189.py", line 946
      _273 = torch.append(strides, [_270, _272])
    _274 = uninitialized(List[Tensor])
    _275 = torch.__isnot__(_263.cell_anchors, None)
                           ~~~~~~~~~~~~~~~~~ <--- HERE
    if _275:
      cell_anchors = _263.cell_anchors

    at org.pytorch.NativePeer.initHybrid(Native Method)
    at org.pytorch.NativePeer.<init>(NativePeer.java:24)
    at org.pytorch.Module.load(Module.java:23)
```

## To Reproduce

Conversion: 
```
model = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True)
scripted_module = torch.jit.script(model)
scripted_module.save("mask_rcnn.pt")
```
Android: 
```
val bitmap = ... # extracted from image view
val module = Module.load(uri)  # fails
val values = module.forward(IValue.from(bitmap))
```

## Expected behavior

Shouldn't fail with above error

## Environment

 - PyTorch / torchvision Version (e.g., 1.0 / 0.4.0): 1.6.0 / 0.7.0
 - OS (e.g., Linux): macOS
 - How you installed PyTorch / torchvision (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): NA
 - Python version: 3.8
 - CUDA/cuDNN version: NA
 - GPU models and configuration: NA
 - Any other relevant information: NA

## Additional context

JIT script works properly but fails during inference. Any idea how to fix this?

**Comment by vfdev-5** [comment]
@prabhuomkar I maybe wrong, but in your android code seems like the input is a tensor and not a list of tensors https://github.com/pytorch/vision/blob/master/torchvision/models/detection/mask_rcnn.py#L149 ?

**Comment by prabhuomkar** [comment]
> @prabhuomkar I maybe wrong, but in your android code seems like the input is a tensor and not a list of tensors https://github.com/pytorch/vision/blob/master/torchvision/models/detection/mask_rcnn.py#L149 ?

Hey, I mentioned `#fails` on wrong line of code. It fails when I try `Module.load()`

**Comment by fmassa** [comment]
Hi,

We currently don't support Faster / Mask R-CNN on mobile. The main blocker I believe is that we rely on custom operators, which to the best of my knowledge can't be yet exported to mobile.
Your error seems unrelated to this issue though.

cc @dreiss if you have further thoughts on this

**Comment by prabhuomkar** [comment]
Closing this because of no activity!
