### ISSUE TITLE
ValueError: bad value(s) in fds_to_keep

### ISSUE THREAD

**Issue by siyangbing** [pytorch/vision#2574]
Traceback (most recent call last):
  File "/home/sucom/hdd_1T/project/video_rec/my_video_rec/self_video_train.py", line 161, in <module>
    trainer.train(task)
  File "/home/sucom/.conda/envs/classy_vision/lib/python3.6/site-packages/classy_vision/trainer/local_trainer.py", line 27, in train
    super().train(task)
  File "/home/sucom/.conda/envs/classy_vision/lib/python3.6/site-packages/classy_vision/trainer/classy_trainer.py", line 45, in train
    task.on_phase_start()
  File "/home/sucom/.conda/envs/classy_vision/lib/python3.6/site-packages/classy_vision/tasks/classification_task.py", line 945, in on_phase_start
    self.advance_phase()
  File "/home/sucom/.conda/envs/classy_vision/lib/python3.6/site-packages/classy_vision/tasks/classification_task.py", line 847, in advance_phase
    self.create_data_iterator()
  File "/home/sucom/.conda/envs/classy_vision/lib/python3.6/site-packages/classy_vision/tasks/classification_task.py", line 900, in create_data_iterator
    self.data_iterator = iter(self.dataloaders[self.phase_type])
  File "/home/sucom/.conda/envs/classy_vision/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/sucom/.conda/envs/classy_vision/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 721, in __init__
    w.start()
  File "/home/sucom/.conda/envs/classy_vision/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/sucom/.conda/envs/classy_vision/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/sucom/.conda/envs/classy_vision/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/sucom/.conda/envs/classy_vision/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/sucom/.conda/envs/classy_vision/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 59, in _launch
    cmd, self._fds)
  File "/home/sucom/.conda/envs/classy_vision/lib/python3.6/multiprocessing/util.py", line 417, in spawnv_passfds
    False, False, None)
ValueError: bad value(s) in fds_to_keep

**Comment by siyangbing** [comment]
please help me. I can not find any issues about it

**Comment by pmeier** [comment]
Hi @siyangbing 

1. This is just the stack trace. Without the code it is nigh impossible to figure out what is wrong. Please compile a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example) that leads to this error.
2. This is an issue tracker and not a help form. Our primary means of support is our [discussion forum](https://discuss.pytorch.org/).
3. In the stack trace I can see no hint of `torchvision`. If it is a bug, the [`torch` issue tracker](https://github.com/pytorch/pytorch/issues/new/choose) might be a better fit for your problem. 

As such I'm closing. Feel free to re-open this if I got anything wrong.
