### ISSUE TITLE
Pytorch mobile app error

### ISSUE THREAD

**Issue by SungmanHong** [pytorch/vision#2666]
I have created .pt file and i just put input...

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.johnolafenwa.pytorchandroid, PID: 3030
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { act=inline-data flg=0x1 (has extras) }} to activity {com.johnolafenwa.pytorchandroid/com.johnolafenwa.pytorchandroid.MainActivity}: java.lang.IllegalStateException: Expected IValue type 2, actual type 7
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4610)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4652)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.IllegalStateException: Expected IValue type 2, actual type 7
        at org.pytorch.IValue.preconditionType(IValue.java:307)
        at org.pytorch.IValue.toTensor(IValue.java:240)
        at com.johnolafenwa.pytorchandroid.Classifier.predict(Classifier.java:58)
        at com.johnolafenwa.pytorchandroid.MainActivity.onActivityResult(MainActivity.java:59)
        at android.app.Activity.dispatchActivityResult(Activity.java:7762)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4603)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4652) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
I/Process: Sending signal. PID: 3030 SIG: 9

**Comment by prabhuomkar** [comment]
Your model->forward expects a `Tensor` but is receiving `Tuple`

Reference: 
[#L27](https://github.com/pytorch/pytorch/blob/4daa3dedbe4c2ed19936f55d354438b3048aa514/android/pytorch_android/src/main/java/org/pytorch/IValue.java#L27) and [#L33](https://github.com/pytorch/pytorch/blob/4daa3dedbe4c2ed19936f55d354438b3048aa514/android/pytorch_android/src/main/java/org/pytorch/IValue.java#L33)

Can you confirm if that's the issue? 
cc: @pmeier

**Comment by SungmanHong** [comment]
Yes, it was data type issue! It is confirmed.
So I changed datatype to tuple. and it worked successfully.

```
IValue inputs = IValue.from(tensor);
IValue[] outputs = model.forward(inputs).toTuple();
```

Also thanks for Ref#https://github.com/pytorch/pytorch/blob/4daa3dedbe4c2ed19936f55d354438b3048aa514/android/pytorch_android/src/main/java/org/pytorch/IValue.java

```
public class IValue {
  private static final int TYPE_CODE_NULL = 1;

  private static final int TYPE_CODE_TENSOR = 2;
  private static final int TYPE_CODE_BOOL = 3;
  private static final int TYPE_CODE_LONG = 4;
  private static final int TYPE_CODE_DOUBLE = 5;
  private static final int TYPE_CODE_STRING = 6;

  private static final int TYPE_CODE_TUPLE = 7;
  private static final int TYPE_CODE_BOOL_LIST = 8;
  private static final int TYPE_CODE_LONG_LIST = 9;
  private static final int TYPE_CODE_DOUBLE_LIST = 10;
  private static final int TYPE_CODE_TENSOR_LIST = 11;
  private static final int TYPE_CODE_LIST = 12;

  private static final int TYPE_CODE_DICT_STRING_KEY = 13;
  private static final int TYPE_CODE_DICT_LONG_KEY = 14;
```
Above thing may help for other people that has similar type mispo.
