### ISSUE TITLE
maskrcnn_resnet50_fpn forward pass in eval mode is giving error.

### ISSUE THREAD

**Issue by submagr** [pytorch/vision#3356]
## 🐛 Bug
[The example given in the description of maskrcnn_resnet50_fpn](https://github.com/pytorch/vision/blob/master/torchvision/models/detection/mask_rcnn.py#L306) is giving error.

## To Reproduce
```
import torchvision
import torch

model = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True)
model.eval()
x = [torch.rand(3, 300, 400), torch.rand(3, 500, 400)]
predictions = model(x)
```

Error:
```
Traceback (most recent call last):
  File "example.py", line 7, in <module>
    predictions = model(x)
  File "/Users/crv/Dev/telerobot/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/crv/Dev/telerobot/env/lib/python3.7/site-packages/torchvision/models/detection/generalized_rcnn.py", line 97, in forward
    if torch.isnan(features).any():
TypeError: isnan(): argument 'input' (position 1) must be Tensor, not collections.OrderedDict
```

## Expected behavior
It should have run properly.

## Environment
```
Collecting environment information...
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: macOS 10.15.7 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.29)
CMake version: version 3.19.1

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: 1.1.0
cuDNN version: /usr/local/cuda/lib/libcudnn.7.0.dylib
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.7.1
[pip3] torchvision==0.8.2
[conda] blas                      1.0                         mkl  
[conda] efficientnet-pytorch      0.6.3                    pypi_0    pypi
[conda] mkl                       2019.4                      233  
[conda] mkl-service               2.3.0            py37hfbe908c_0  
[conda] mkl_fft                   1.0.15           py37h5e564d8_0  
[conda] mkl_random                1.1.0            py37ha771720_0  
[conda] numpy                     1.18.1                   pypi_0    pypi
[conda] numpy-base                1.18.1           py37h6575580_1  
[conda] numpy-quaternion          2020.5.19.15.27.24          pypi_0    pypi
[conda] torch                     1.5.0                    pypi_0    pypi
```

## Additional context
This issue seems to be happening only on macos. I tried on an ubuntu machine with same torch and torchvision version number and the script is working fine.

**Comment by submagr** [comment]
In my local generalized_rcnn.py, there was a check torch.isnan(features) which was giving an error. Removing that seems to have fixed the issue. But still curious what's the proper way to fix this issue.


```
   def forward(self, images, targets=None):
        # type: (List[Tensor], Optional[List[Dict[str, Tensor]]]) -> Tuple[Dict[str, Tensor], List[Dict[str, Tensor]]]
        """
        Arguments:
            images (list[Tensor]): images to be processed
            targets (list[Dict[Tensor]]): ground-truth boxes present in the image (optional)

        Returns:
            result (list[BoxList] or dict[Tensor]): the output from the model.
                During training, it returns a dict[Tensor] which contains the losses.
                During testing, it returns list[BoxList] contains additional fields
                like `scores`, `labels` and `mask` (for Mask R-CNN models).

        """
        if self.training and targets is None:
            raise ValueError("In training mode, targets should be passed")
        if self.training:
            assert targets is not None
            for target in targets:
                boxes = target["boxes"]
                if isinstance(boxes, torch.Tensor):
                    if len(boxes.shape) != 2 or boxes.shape[-1] != 4:
                        raise ValueError("Expected target boxes to be a tensor"
                                         "of shape [N, 4], got {:}.".format(
                                             boxes.shape))
                else:
                    raise ValueError("Expected target boxes to be of type "
                                     "Tensor, got {:}.".format(type(boxes)))

        original_image_sizes = torch.jit.annotate(List[Tuple[int, int]], [])
        for img in images:
            val = img.shape[-2:]
            assert len(val) == 2
            original_image_sizes.append((val[0], val[1]))

        images, targets = self.transform(images, targets)

        # Check for degenerate boxes
        # TODO: Move this to a function
        if targets is not None:
            for target_idx, target in enumerate(targets):
                boxes = target["boxes"]
                degenerate_boxes = boxes[:, 2:] <= boxes[:, :2]
                if degenerate_boxes.any():
                    # print the first degenerate box
                    bb_idx = torch.where(degenerate_boxes.any(dim=1))[0][0]
                    degen_bb: List[float] = boxes[bb_idx].tolist()
                    raise ValueError("All bounding boxes should have positive height and width."
                                     " Found invalid box {} for target at index {}."
                                     .format(degen_bb, target_idx))

        features = self.backbone(images.tensors)
        if torch.isnan(features):
            print("features are nan")

        if isinstance(features, torch.Tensor):
            features = OrderedDict([('0', features)])
        proposals, proposal_losses = self.rpn(images, features, targets)
        detections, detector_losses = self.roi_heads(features, proposals, images.image_sizes, targets)
        detections = self.transform.postprocess(detections, images.image_sizes, original_image_sizes)

        losses = {}
        losses.update(detector_losses)
        losses.update(proposal_losses)

        if torch.jit.is_scripting():
            if not self._has_warned:
                warnings.warn("RCNN always returns a (Losses, Detections) tuple in scripting")
                self._has_warned = True
            return (losses, detections)
        else:
            return self.eager_outputs(losses, detections)
```

**Comment by datumbox** [comment]
@submagr Thanks for reporting.

I'm having hard time reproducing this. I also checked the lines at question on in the [v0.8.2](https://github.com/pytorch/vision/blob/v0.8.2/torchvision/models/detection/generalized_rcnn.py#L97) and there is no such a check as reported on the exception message. Perhaps you are working with a modified version of TorchVision? Perhaps it's worth checking out the latest master and checking if you still have issues there?
