### ISSUE TITLE
 Error when executing scripted FasterRCNN in training mode

### ISSUE THREAD

**Issue by BynaryCobweb** [pytorch/vision#3469]
## 🐛 Bug

Error when executing scripted FasterRCNN in training mode. This is probably due to function `torch.randperm` having a different behavior when executed by torchscript.

## To Reproduce

```python
import torch
import torchvision.models as M

class DetectionModel(torch.nn.Module):
    def __init__(self, model):
        super(DetectionModel, self).__init__()
        self.model = model

    def forward(self, x, bboxes = None, labels = None):
        # type: (Tensor, Optional[Tensor], Optional[Tensor]) -> Tuple[Dict[str, Tensor], List[Dict[str, Tensor]]]
        """
        Input format: one tensor of dimensions [batch size, channel count, width, height]
        """
        l_x = [x[i] for i in range(x.shape[0])]
        if self.training:
            assert bboxes is not None
            assert labels is not None
            l_targs = [{"boxes": bboxes[i], "labels": labels[i]} for i in range(x.shape[0])]
            losses, predictions = self.model(l_x, l_targs)
        else:
            losses, predictions = self.model(l_x)

        return losses, predictions

model = M.detection.fasterrcnn_resnet50_fpn()
detect_model = DetectionModel(model)
detect_model.train()
script_module = torch.jit.script(detect_model)
script_module.train()
out = script_module(
        torch.rand(1, 3, 224, 224),
        torch.Tensor([1, 1, 200, 200]).unsqueeze(0).unsqueeze(0),
        torch.full((1,1), 1).long()
)
print(out)
```
Gives error:
```
Traceback (most recent call last):
  File "bugtest.py", line 33, in <module>
    torch.full((1,1), 1).long()
  File "***/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "***/.local/lib/python3.6/site-packages/torchvision/models/detection/_utils.py", line 58, in forward
            perm2 = torch.randperm(negative.numel(), device=negative.device)[:num_neg]

            pos_idx_per_image = positive[perm1]
                                ~~~~~~~~~~~~~~~ <--- HERE
            neg_idx_per_image = negative[perm2]
RuntimeError: tensors used as indices must be long, byte or bool tensors
```

If I print `perm1` here, it seems like it's a float tensor, but torch.randperm is supposed to return a LongTensor  (see [documentation](https://pytorch.org/docs/stable/generated/torch.randperm.html) ).

## Environment

```
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.18.4

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: TITAN X (Pascal)
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti

Nvidia driver version: 455.23.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.7.1
[pip3] torchfile==0.1.0
[pip3] torchvision==0.8.2
[pip3] torchviz==0.0.1
```

**Comment by BynaryCobweb** [comment]
It seems like specifying the type in `torch.randperm` solves the problem:
```
            perm1 = torch.randperm(positive.numel(), dtype=torch.int64, device=positive.device)[:num_pos]
            perm2 = torch.randperm(negative.numel(), dtype=torch.int64, device=negative.device)[:num_neg]
```

**Comment by fmassa** [comment]
Hum, interesting.

@BynaryCobweb we can fix this in torchvision by explicitly mentioning the type, but I think that it would be worth opening an issue in PyTorch with a minimum reproducible example (which only uses randperm if possible)

**Comment by BynaryCobweb** [comment]
Done here https://github.com/pytorch/pytorch/issues/53015

**Comment by fmassa** [comment]
This has been fixed with https://github.com/pytorch/pytorch/pull/57105 thanks for the report!
