### ISSUE TITLE
ToTensor cannot handle PIL Image with mode '1'

### ISSUE THREAD

**Issue by IanChen83** [pytorch/vision#371]
https://github.com/pytorch/vision/blob/080b95437186c99d0b664fd69f18773e1c2a7d8f/torchvision/transforms/functional.py#L63 
If the image's mode is `1`, `image.tobytes` is called to convert image to bytes. However, this will return a Tensor object with element size 8x of the original image, and result in RuntimeError.

```
Traceback (most recent call last):
  File "test.py", line 106, in <module>
    (0.2156, 0.2111, 0.2125)),
  File "test.py", line 80, in __init__
    img, pk = pk_loader(f'{fpath}/{path}')
  File "test.py", line 64, in pk_loader
    m = ToTensor(data[channel])
  File "/usr/lib/python3.6/site-packages/torchvision/transforms.py", line 58, in __call__
    img = img.view(pic.size[1], pic.size[0], nchannel)
RuntimeError: invalid argument 2: size '[1461 x 512 x 1]' is invalid for input of with 93504 elements at /pytorch/torch/lib/TH/THStorage.c:41
```

**Comment by amorgun** [comment]
I faced the same problem with image mode 'F'.
Sample code:
```
import numpy as np
import torchvision.transforms.functional as V
data = np.random.rand(10, 10, 1).astype(np.float32)
V.to_tensor(V.to_pil_image(data))
```

Error:
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-113-0dca96e64534> in <module>()
      2 import torchvision.transforms.functional as V
      3 data = np.random.rand(10, 10, 1).astype(np.float32)
----> 4 V.to_tensor(V.to_pil_image(data))

.../lib/python3.6/site-packages/torchvision/transforms/functional.py in to_tensor(pic)
     69     else:
     70         nchannel = len(pic.mode)
---> 71     img = img.view(pic.size[1], pic.size[0], nchannel)
     72     # put it from HWC to CHW format
     73     # yikes, this transpose takes 80% of the loading time/CPU

RuntimeError: invalid argument 2: size '[10 x 10 x 1]' is invalid for input of with 400 elements at /pytorch/torch/lib/TH/THStorage.c:41
```

**Comment by amorgun** [comment]
I have found an ugly workaround:
```
import numpy as np
import torchvision.transforms.functional as V
data = np.random.rand(2, 2, 1).astype(np.float32)
V.to_tensor(
    np.asarray(V.to_pil_image(data))[:, :, None] * 255
)
```

**Comment by arturml** [comment]
I'm dealing with this issue working with masks for semantic segmentation. For some reason, some of the masks opened by `Image.open` are mode '1'. These are 1-bit images, so this line doesn't work:
```python
img = torch.ByteTensor(torch.ByteStorage.from_buffer(pic.tobytes()))
```
Since there's no 1-bit tensor, the only solution I can think of is adding another `elif` for mode '1' with a convert to mode 'L':
```python
elif pic.mode == '1':
    img = torch.ByteTensor(torch.ByteStorage.from_buffer(pic.convert('L').tobytes()))
```
I'll try to make this change and adjust the tests.

**Comment by fmassa** [comment]
Fixed via https://github.com/pytorch/vision/pull/471
