### ISSUE TITLE
torchvision.models.mnasnet1_3(pretrained=True)

### ISSUE THREAD

**Issue by tejan-rgb** [pytorch/vision#3722]
## 🐛 Bug

When ran ``` torchvision.models.mnasnet1_3(pretrained=True) ```
got:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tejanm/anaconda3/lib/python3.7/site-packages/torchvision/models/mnasnet.py", line 274, in mnasnet1_3
    _load_pretrained("mnasnet1_3", model, progress)
  File "/home/tejanm/anaconda3/lib/python3.7/site-packages/torchvision/models/mnasnet.py", line 212, in _load_pretrained
    "No checkpoint is available for model type {}".format(model_name))
ValueError: No checkpoint is available for model type mnasnet1_3
```

**Comment by oke-aditya** [comment]
Hi @tejan-rgb  this is known issue. MNasnet 0_75 and 1_3 weights are not available in torchvision yet. Hopefully soon #2707

**Comment by tejan-rgb** [comment]
okay.
