### ISSUE TITLE
Input size mismatch error when retraining inceptionV3 model

### ISSUE THREAD

**Issue by siva69** [pytorch/vision#396]
I'm facing trouble when training a model using pre-trained inceptionV3 for my own image data set. 

I'm loading images using data.Dataset loader and 'transforms' for image transformation. 

Here's my inceptionV3 model

`inceptionV3 = torchvision.models.inception_v3(pretrained=True)`
  `pretrained_model = nn.Sequential(*list(inceptionV3.children()))`
  `pretrained_model = nn.Sequential(*list(pretrained_features.children())[:-1])`
`  for param in pretrained_model.parameters():
        param.requires_grad = False`

Here's my transforms code

`data_transforms = transforms.Compose([`
            `transforms.Scale((299,299)),`
            `transforms.RandomHorizontalFlip(),`
            `transforms.ToTensor(),`
          `  transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])`
        `])`

I'm getting this error at the line 'out_features = pretrained_model(inputs)'

`Traceback (most recent call last):
  File "build_models.py", line 42, in <module>
    use_gpu=use_gpu)
  File "/home/ubuntu/apparel-styles/ml_src/classifiers.py", line 488, in create_attributes_model
    batch_size, num_workers, num_epochs, use_gpu=use_gpu)
  File "/home/ubuntu/apparel-styles/ml_src/classifiers.py", line 276, in train_model
    flatten_pretrained_out=flatten_pretrained_out)
  File "/home/ubuntu/apparel-styles/ml_src/classifiers.py", line 181, in train_attribute_model
    out_features = pretrained_model(inputs)
  File "/home/ubuntu/apparel-styles/env/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/apparel-styles/env/venv/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 68, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ubuntu/apparel-styles/env/venv/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 78, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ubuntu/apparel-styles/env/venv/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 67, in parallel_apply
    raise output
  File "/home/ubuntu/apparel-styles/env/venv/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 42, in _worker
    output = module(*input, **kwargs)
  File "/home/ubuntu/apparel-styles/env/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/apparel-styles/env/venv/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/ubuntu/apparel-styles/env/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/apparel-styles/env/venv/lib/python3.6/site-packages/torchvision/models/inception.py", line 312, in forward
    x = self.fc(x)
  File "/home/ubuntu/apparel-styles/env/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/apparel-styles/env/venv/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/ubuntu/apparel-styles/env/venv/lib/python3.6/site-packages/torch/nn/functional.py", line 835, in linear
    return torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch at /pytorch/torch/lib/THC/generic/THCTensorMathBlas.cu:243`

After getting this error, I tried to print the input size. It's value is

`print(inputs.shape)`

      torch.Size([256, 3, 299, 299])

**Comment by fmassa** [comment]
The problem might be that `inception` does not follow exactly a `Sequential` module because of the [`AuxLogits` classifier](https://github.com/pytorch/vision/blob/master/torchvision/models/inception.py#L109), which makes your model not match the original inception.
I think it might be easier in your case to just modify the `fc` layer to be of the dimension you want.

```python
inceptionV3 = torchvision.models.inception_v3(pretrained=True)
inceptionV3.fc = nn.Linear(2048, num_classes)
```
