### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by Bing1002** [pytorch/vision#436]
Hi, 

I have installed pytorch with GPU in my computer. It works now for pytorch.  When I installed torchvision and it said I installed successfully. But when I tested it using import torchvision, it has following error. I don't why it this? I tried pip, conda and source install method. The results are same.
>>> import torchvision
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\zha.44\AppData\Local\Continuum\anaconda3\lib\site-packages\torchvision\__init__.py", line 2, in <module>
    from torchvision import datasets
  File "C:\Users\zha.44\AppData\Local\Continuum\anaconda3\lib\site-packages\torchvision\datasets\__init__.py", line 1, in <module>
    from .lsun import LSUN, LSUNClass
  File "C:\Users\zha.44\AppData\Local\Continuum\anaconda3\lib\site-packages\torchvision\datasets\lsun.py", line 2, in <module>
    from PIL import Image
  File "C:\Users\zha.44\AppData\Local\Continuum\anaconda3\lib\site-packages\PIL\Image.py", line 58, in <module>
    from . import _imaging as core
ImportError: DLL load failed: The specified module could not be found.

**Comment by lanpa** [comment]
Look like PIL is failed.
maybe you need to `pip install pillow` first.

**Comment by fmassa** [comment]
yes, looks like importing PIL failed. Did it work for you with @lanpa suggestion of uninstalling and installing again?

**Comment by vosilov** [comment]
I, too, have the error:

```
ImportError                               Traceback (most recent call last)
<ipython-input-2-5e5a77c4feda> in <module>()
----> 1 from PIL import _imaging as core

ImportError: DLL load failed: The specified module could not be found.

```

I tried uninstalling and reinstalling pillow, but it didn't help.

**Comment by fmassa** [comment]
This is an error in PIL, and not in torchvision, so closing this.
