### ISSUE TITLE
ImageFolder to support *.JPEG (in capital letters)

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/vision#446]
```python
# mkdir foo && touch foo/foo.JPEG

import torchvision.datasets
torchvision.datasets.ImageFolder('foo')

#Traceback (most recent call last):
#  File "foo.py", line 3, in <module>
#    torchvision.datasets.ImageFolder('foo')
#  File "build/bdist.linux-x86_64/egg/torchvision/datasets/folder.py", line 103, in __init__
#RuntimeError: Found 0 images in subfolders of: foo
#Supported image extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm
```

**Comment by vadimkantorov** [comment]
My bad, it complains about absence of images in *sub*-directories
