### ISSUE TITLE
torchvision.datasets.MNIST with TypeError: expected np.ndarray (got numpy.ndarray)

### ISSUE THREAD

**Issue by pluto33** [pytorch/vision#4572]
Is there something wrong in mnist.py or my environment?
with (torch.version) 1.7.1 (torchvision.version): 0.8.2  in a remote connection jupyter notebook, the following program doesn't work:
**code**
```python
import numpy as np
import torch
import torchvision
from torchvision import datasets,transforms
from torch.autograd import Variable
import matplotlib.pyplot as plt

transform = transforms.Compose([transforms.ToTensor(),transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))])   


data_train=datasets.MNIST(root="./data/",transform=transform,train=True,download=True)
data_test=datasets.MNIST(root="./data/",transform=transform,train=False,download=True)
    
    
data_loader_train=torch.utils.data.DataLoader\
    (dataset=data_train,batch_size=64,shuffle=True)
    
data_loader_test=torch.utils.data.DataLoader\
    (dataset=data_test,batch_size=64,shuffle=True)
    
    
images,labels=next(iter(data_loader_train))
img=torchvision.utils.make_grid(images)

img=img.numpy().transpose(1,2,0)
std=[0.5,0.5,0.5]
mean=[0.5,0.5,0.5]
img=img*std+mean
print([labels[i] for i in range(64)])
plt.imshow(img)

```
**the output is** 
```python
runcell(0, 'C:/Users/ao/.spyder-py3/write1.py')
Using downloaded and verified file: ./data/MNIST\raw\train-images-idx3-ubyte.gz
Extracting ./data/MNIST\raw\train-images-idx3-ubyte.gz to ./data/MNIST\raw
Using downloaded and verified file: ./data/MNIST\raw\train-labels-idx1-ubyte.gz
Extracting ./data/MNIST\raw\train-labels-idx1-ubyte.gz to ./data/MNIST\raw
Using downloaded and verified file: ./data/MNIST\raw\t10k-images-idx3-ubyte.gz
Extracting ./data/MNIST\raw\t10k-images-idx3-ubyte.gz to ./data/MNIST\raw
Using downloaded and verified file: ./data/MNIST\raw\t10k-labels-idx1-ubyte.gz
Extracting ./data/MNIST\raw\t10k-labels-idx1-ubyte.gz to ./data/MNIST\raw
Processing...
Traceback (most recent call last):

  File "C:\Users\ao\.spyder-py3\write1.py", line 17, in <module>
    data_train=datasets.MNIST(root="./data/",transform=transform,train=True,download=True)

  File "D:\ProgramData\Anaconda3\envs\apple\lib\site-packages\torchvision\datasets\mnist.py", line 79, in __init__
    self.download()

  File "D:\ProgramData\Anaconda3\envs\apple\lib\site-packages\torchvision\datasets\mnist.py", line 152, in download
    read_image_file(os.path.join(self.raw_folder, 'train-images-idx3-ubyte')),

  File "D:\ProgramData\Anaconda3\envs\apple\lib\site-packages\torchvision\datasets\mnist.py", line 493, in read_image_file
    x = read_sn3_pascalvincent_tensor(f, strict=False)

  File "D:\ProgramData\Anaconda3\envs\apple\lib\site-packages\torchvision\datasets\mnist.py", line 480, in read_sn3_pascalvincent_tensor
    return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)

TypeError: expected np.ndarray (got numpy.ndarray)
```
**Environment**
Collecting environment information...
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 专业版
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.19.6

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] numpydoc==1.1.0
[pip3] torch==1.7.1
[pip3] torchtext==0.8.1
[pip3] torchvision==0.8.2
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               10.1.243             h74a9793_0    defaults
[conda] mkl                       2018.0.3                      1    defaults
[conda] mkl_fft                   1.0.6            py36hdbbee80_0    defaults
[conda] mkl_random                1.0.1            py36h77b88f5_1    defaults
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] numpy-base                1.15.4           py36h8128ebf_0    defaults
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1    defaults
[conda] pytorch                   1.7.1           py3.6_cuda101_cudnn7_0    pytorch
[conda] torchtext                 0.8.1                      py36    pytorch
[conda] torchvision               0.8.2                py36_cu101    pytorch

**Comment by NicolasHug** [comment]
I think the issue is happening in the data loading part before the transforms are called, so it's probably not going to fix the issue - but it's a good point though!

@pluto33 it looks like you're using some old version of pytorch and torchvision. Could you try with the latest stable versions instaed? We have made changes to the data loading since then, so it's possible that this is a bug that has been fixed a while ago
