### ISSUE TITLE
[feature request] show name of damaged file in FolderDataset

### ISSUE THREAD

**Issue by medakk** [pytorch/vision#485]
I am using DataLoader with FolderDataset to get some images from a dataset with a few bad images. It would be nice if the FolderDataset mentioned the path to the damaged image in the exception thrown:
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-10-cc88ea5f8bd3> in <module>()
      1 model_ft = train_model(model_ft, criterion, optimizer_ft, exp_lr_scheduler,
----> 2                        num_epochs=25)

<ipython-input-6-373a4f614762> in train_model(model, criterion, optimizer, scheduler, num_epochs)
     21 
     22             # Iterate over data.
---> 23             for inputs, labels in data_loaders[phase]:
     24                 inputs = inputs.to(device)
     25                 labels = labels.to(device)

~/.virtualenvs/pytorch-sandbox/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    284                 self.reorder_dict[idx] = batch
    285                 continue
--> 286             return self._process_next_batch(batch)
    287 
    288     next = __next__  # Python 2 compatibility

~/.virtualenvs/pytorch-sandbox/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _process_next_batch(self, batch)
    305         self._put_indices()
    306         if isinstance(batch, ExceptionWrapper):
--> 307             raise batch.exc_type(batch.exc_msg)
    308         return batch
    309 

OSError: Traceback (most recent call last):
  File "/home/karthik/.virtualenvs/pytorch-sandbox/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/karthik/.virtualenvs/pytorch-sandbox/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/karthik/.virtualenvs/pytorch-sandbox/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 101, in __getitem__
    sample = self.loader(path)
  File "/home/karthik/.virtualenvs/pytorch-sandbox/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 147, in default_loader
    return pil_loader(path)
  File "/home/karthik/.virtualenvs/pytorch-sandbox/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 130, in pil_loader
    return img.convert('RGB')
  File "/home/karthik/.virtualenvs/pytorch-sandbox/lib/python3.6/site-packages/PIL/Image.py", line 879, in convert
    self.load()
  File "/home/karthik/.virtualenvs/pytorch-sandbox/lib/python3.6/site-packages/PIL/ImageFile.py", line 228, in load
    "(%d bytes not processed)" % len(b))
OSError: image file is truncated (5 bytes not processed)
```

cc @pmeier

**Comment by pmeier** [comment]
Hey @medakk, I'm not sure if this is still relevant since this has been opened almost three years ago. The `DatasetFolder` and `ImageFolder` datasets have a `loader` argument. This is required for the former and defaults to loading the image with an available image backend for the latter.

Usually, one would not expect corrupt images and this is why there is no error handling implemented. In your case I would simply pass custom loader that looks something like this:

```python
from torchvision import datasets
from torchvision.datasets.folder import default_loader


def custom_loader(path):
    try:
        return default_loader(path)
    except Exception as error:
        raise RuntimeError(f"Corrupt image located in {path}") from error


dataset = datasets.ImageFolder(..., loader=custom_loader)
```

Let me know if you need further assistance.
