### ISSUE TITLE
JIT not working with `torchvision.transforms.CenterCrop`

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [pytorch/vision#4902]
## Bug

[All files here (`model.pth`, `model.zip`, `jit-load-test.py` and `test.py`)](https://drive.google.com/drive/folders/1XyEGzQSQzEu5ED78adkS3rW9UsQUhBZe?usp=sharing)

I have a semantic segmentation model which utilizes a center crop on its output (`test.py`):
```python
class UNet(nn.Module):
    def __init__(
        # ...
    ):
        # ...
        self.crop = torchvision.transforms.CenterCrop(output_size)
    def forward(self,x):
        # ...
        crop = self.crop(x)
        # ...
```
Trying to save this as a JIT model results in the error:
```
Traceback (most recent call last):
  File "test.py", line 110, in <module>
    main()
  File "test.py", line 103, in main
    net_trace = torch.jit.trace(model,example_input) # Traces using this batch
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/jit/_trace.py", line 741, in trace
    return trace_module(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/jit/_trace.py", line 958, in trace_module
    module._c._create_method_from_trace(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "test.py", line 84, in forward
    crop = torchvision.transforms.functional.center_crop(final,self.output_size)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torchvision/transforms/functional.py", line 534, in center_crop
    crop_top = int(round((image_height - crop_height) / 2.))
TypeError: type Tensor doesn't define __round__ method
```
If I replace `self.crop = torchvision.transforms.CenterCrop(output_size)` with `self.crop = torch.jit.script(torch.nn.Sequential(torchvision.transforms.CenterCrop(output_size)))` saving with JIT works.

However when trying to load this (`jit-load-test.py`):
```python
import torch
model = torch.jit.load("model.zip")
input = torch.ones([12,3,300,600])
output = model(input)
print(output)
```
Results in the error:
```
Traceback (most recent call last):
  File "jit-load-test.py", line 3, in <module>
    model = torch.jit.load("model.zip")
  File "/home/jonathan/.local/lib/python3.8/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: 
Unknown builtin op: aten::reflection_pad3d.
Here are some suggestions: 
        aten::reflection_pad1d
        aten::reflection_pad2d

The original call is:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 4199
        elif len(pad) == 6 and (input.dim() == 4 or input.dim() == 5):
            if mode == "reflect":
                return torch._C._nn.reflection_pad3d(input, pad)
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            elif mode == "replicate":
                return torch._C._nn.replication_pad3d(input, pad)
Serialized   File "code/__torch__/torch/nn/functional.py", line 93
        if _27:
          if torch.eq(mode, "reflect"):
            _32 = torch.reflection_pad3d(input, pad)
                  ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            _31 = _32
          else:
'_pad' is being compiled since it was called from 'pad'
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torchvision/transforms/functional_tensor.py", line 475
        img = img.to(torch.float32)

    img = torch_pad(img, p, mode=padding_mode, value=float(fill))
          ~~~~~~~~~ <--- HERE

    if need_squeeze:
Serialized   File "code/__torch__/torchvision/transforms/functional_tensor.py", line 79
    else:
      img1, need_cast = img0, False
    img2 = __torch__.torch.nn.functional._pad(img1, p, padding_mode1, float(fill0), )
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    if need_squeeze:
      img3 = torch.squeeze(img2, 0)
'pad' is being compiled since it was called from 'pad'
Serialized   File "code/__torch__/torchvision/transforms/functional.py", line 76
    fill: int=0,
    padding_mode: str="constant") -> Tensor:
  _26 = __torch__.torchvision.transforms.functional_tensor.pad
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
  img3 = unchecked_cast(Tensor, img)
  _27 = _26(img3, padding, fill, padding_mode, )
'pad' is being compiled since it was called from 'center_crop'
Serialized   File "code/__torch__/torchvision/transforms/functional.py", line 4
    output_size: List[int]) -> Tensor:
  _0 = __torch__.torchvision.transforms.functional.get_image_size
  _1 = __torch__.torchvision.transforms.functional.pad
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
  _2 = __torch__.torchvision.transforms.functional.crop
  _3 = uninitialized(Tensor)
'center_crop' is being compiled since it was called from 'CenterCrop.forward'
Serialized   File "code/__torch__/torchvision/transforms/transforms.py", line 9
  def forward(self: __torch__.torchvision.transforms.transforms.CenterCrop,
    img: Tensor) -> Tensor:
    _0 = __torch__.torchvision.transforms.functional.center_crop
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    size = self.size
    return _0(img, size, )

```
Full `test.py`:
```python
import torch
import torch.nn as nn
from torch.nn.modules.batchnorm import BatchNorm2d
import torchvision

class DoubleConv(nn.Module):
    def __init__(self, in_channels, out_channels):
        super(DoubleConv,self).__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3, stride=1, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, kernel_size=3, stride=1, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True)
        )
    def forward(self,x):
        return self.conv(x)

class UNet(nn.Module):
    def __init__(
        self,
        out_channels, # A channel for each label, plus 1 for background
        output_size,
        in_channels = 3,
        features = [64,128,256,512],
    ):
        super(UNet,self).__init__()
        self.ups = nn.ModuleList() # Up sampling layers
        self.downs = nn.ModuleList() # Down sampling layers
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)

        # Down part of UNet
        for feature in features:
            self.downs.append(DoubleConv(in_channels,feature))
            in_channels = feature

        # Up part of UNet
        for feature in reversed(features):
            self.ups.append(nn.ConvTranspose2d(
                in_channels=feature*2,
                out_channels=feature, 
                kernel_size=2, 
                stride=2
            ))
            self.ups.append(DoubleConv(in_channels=feature*2, out_channels=feature))
        
        self.bottleneck = DoubleConv(features[-1], features[-1]*2)
        self.final_cov = nn.Conv2d(features[0], out_channels, kernel_size=1)
        self.output_size = output_size
        self.crop = torchvision.transforms.CenterCrop(output_size)
        # self.crop = torch.jit.script(torch.nn.Sequential(torchvision.transforms.CenterCrop(output_size)))
    
    def forward(self,x):
        skip_connections = []
        # Runs downsampling
        for down in self.downs:
            x = down(x)
            skip_connections.append(x)
            x = self.pool(x)
        # Runs bottleneck
        x = self.bottleneck(x)
        skip_connections = skip_connections[::-1] # Reverse `skip_connections`
        # Runs upsampling
        for index in range(0,len(self.ups),2):
            x = self.ups[index](x)
            # Integer division to map [0,2,4,6,...]->[0,1,2,3,...].
            skip_connection = skip_connections[index//2] 
            # If upscale size does not match saved size, we resize x to match (this should only scale the image by a pixel or two)
            x = torchvision.transforms.functional.resize(x,size=skip_connection.shape[2:])
            # Concates `skip_connection` along channel dimension.
            concat_skip = torch.cat((skip_connection,x),dim=1) 

            x = self.ups[index+1](concat_skip)
        final = self.final_cov(x)

        # Crops to center (croping out padding used for context)
        crop = self.crop(final)
        # crop = torchvision.transforms.functional.center_crop(final,self.output_size)

        # Through channels dimension
        softmax = nn.functional.softmax(input = crop, dim = 1) 
        return softmax

STRIDE = [150,300] # Height, Width
WINDOW = [300,600] # Height, Width

def main():
    model = UNet(out_channels=92, output_size=STRIDE)
    print("constructed model")

    model.load_state_dict(torch.load(f"model.pth"))
    model.eval()
    print("loaded model")

    # Saves jit model (which can be used in Rust)
    example_input = torch.zeros((1,3,WINDOW[0],WINDOW[1])).type(torch.float32)
    net_trace = torch.jit.trace(model,example_input) # Traces using this batch
    print("traced model")

    torch.jit.save(net_trace,f"model.zip")
    print("saved model")

if __name__ == "__main__":
    main()
```

### Versions

I'm using the latest stable CUDA 11.3 version installed via pip:
`pip3 install torch==1.10.0+cu113 torchvision==0.11.1+cu113 torchaudio==0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html`

cc @vfdev-5 @datumbox

**Comment by fmassa** [comment]
@vfdev-5 can you have a look?

**Comment by vfdev-5** [comment]
Looks like trace does not work on center crop and we only check `torch.jit.script` on our CI
```python
    import torch
    device = "cpu"
    from torchvision import transforms as T

    tensor = torch.randint(0, 256, (3, 10, 10), dtype=torch.uint8, device=device)
    # Test torchscript of transforms.CenterCrop with size as int
    f = T.CenterCrop(size=5)
    traceed_fn = torch.jit.trace(f, tensor)
    ret = traceed_fn(tensor)
```


@JonathanWoollett-Light I tried to script your model to see if everything works but got an issue with upsampling part
```
    for index in range(0,len(self.ups),2):
            x = self.ups[index](x)
            # Integer division to map [0,2,4,6,...]->[0,1,2,3,...].
            skip_connection = skip_connections[index//2] 
            # If upscale size does not match saved size, we resize x to match (this should only scale the image by a pixel or two)
            x = torchvision.transforms.functional.resize(x,size=skip_connection.shape[2:])
            # Concates `skip_connection` along channel dimension.
            concat_skip = torch.cat((skip_connection,x),dim=1) 
```
> 
```
RuntimeError:                                                                                       
Expected integer literal for index. ModuleList/Sequential indexing is only supported with integer literals. Enumeration is supported, e.g. 'for index, v in enumerate(self): ...':
  File "center_crop_issue_4902.py", line 66                                                            
        # Runs upsampling                                                                                                     
        for index in range(0,len(self.ups),2):                                                                           
            x = self.ups[index](x)                                
                ~~~~~~~~~~~~~~~ <--- HERE                                                                                                                                         
            # Integer division to map [0,2,4,6,...]->[0,1,2,3,...].                           
            skip_connection = skip_connections[index//2] 
```

I think if you can make it jit scriptable then everything should work

**Comment by vfdev-5** [comment]
@JonathanWoollett-Light torchvision transforms supports only torch jit script, so I suggest to use `torch.jit.script` instead of tracing. If I modify your forward pass as below to make the model scriptable then we can save the model and reload it and things seem to work. I close issue as resolved. Feel free to reopen if you think we need to discuss more. Thanks!

<details>

<summary>
test.py
</summary>


```python
import torch
import torch.nn as nn
import torchvision


class DoubleConv(nn.Module):
    def __init__(self, in_channels, out_channels):
        super(DoubleConv,self).__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3, stride=1, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, kernel_size=3, stride=1, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True)
        )
    def forward(self,x):
        return self.conv(x)


class UNet(nn.Module):
    def __init__(
        self,
        out_channels, # A channel for each label, plus 1 for background
        output_size,
        in_channels = 3,
        features = [64,128,256,512],
    ):
        super(UNet,self).__init__()
        self.ups = nn.ModuleList() # Up sampling layers
        self.downs = nn.ModuleList() # Down sampling layers
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)

        # Down part of UNet
        for feature in features:
            self.downs.append(DoubleConv(in_channels,feature))
            in_channels = feature

        # Up part of UNet
        for feature in reversed(features):
            self.ups.append(nn.ConvTranspose2d(
                in_channels=feature*2,
                out_channels=feature,
                kernel_size=2,
                stride=2
            ))
            self.ups.append(DoubleConv(in_channels=feature*2, out_channels=feature))

        self.bottleneck = DoubleConv(features[-1], features[-1]*2)
        self.final_cov = nn.Conv2d(features[0], out_channels, kernel_size=1)
        self.output_size = output_size
        self.crop = torchvision.transforms.CenterCrop(output_size)
        # self.crop = torch.jit.script(torch.nn.Sequential(torchvision.transforms.CenterCrop(output_size)))

    def forward(self,x):
        skip_connections = []
        # Runs downsampling
        for down in self.downs:
            x = down(x)
            skip_connections.append(x)
            x = self.pool(x)
        # Runs bottleneck
        x = self.bottleneck(x)
        skip_connections = skip_connections[::-1] # Reverse `skip_connections`

        # Runs upsampling
        # for index in range(0, len(self.ups),2):
        for index, m in enumerate(self.ups):
            if index % 2 == 0:
                x = m(x)
                # Integer division to map [0,2,4,6,...]->[0,1,2,3,...].
                skip_connection = skip_connections[index//2]
                # If upscale size does not match saved size, we resize x to match (this should only scale the image by a pixel or two)
                x = torchvision.transforms.functional.resize(x,size=skip_connection.shape[2:])
                # Concates `skip_connection` along channel dimension.
                x = torch.cat((skip_connection, x),dim=1)
            else:
                x = m(x)

        final = self.final_cov(x)

        # Crops to center (croping out padding used for context)
        crop = self.crop(final)

        # Through channels dimension
        softmax = nn.functional.softmax(input = crop, dim = 1)
        return softmax

STRIDE = [150,300] # Height, Width
WINDOW = [300,600] # Height, Width

def main():
    model = UNet(out_channels=92, output_size=STRIDE)
    print("constructed model")

    # model.load_state_dict(torch.load(f"model.pth"))
    model_orig.eval()
    model.eval()
    print("loaded model")

    # Saves jit model (which can be used in Rust)
    example_input = torch.zeros((1,3,WINDOW[0],WINDOW[1])).type(torch.float32)

    assert o1.allclose(o2), f"{o1.mean()} vs {o2.mean()}"

    # net_trace = torch.jit.trace(model, example_input) # Traces using this batch
    # print("traced model")

    scripted_net = torch.jit.script(model)
    print("scripted model")

    torch.jit.save(scripted_net, f"model.zip")
    print("saved model")

    fn = torch.jit.load('model.zip')
    print("saved model zip")

    fn.eval()
    _ = fn(example_input)
    print("all good")


if __name__ == "__main__":
    main()
```

</details>
