### ISSUE TITLE
torchvision conda package missing requests dependency

### ISSUE THREAD

**Issue by malfet** [pytorch/vision#4917]
### 🐛 Describe the bug

torchvision depends on requests, but it is not specified as conda package dependency, which results in the following failures:
```
% python
Python 3.8.11 (default, Aug  6 2021, 08:56:27) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from torchvision import datasets
>>> calldetch_ds = datasets.Caltech101("datasets", download=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nshulga/miniconda3/envs/py_38/lib/python3.8/site-packages/torchvision/datasets/caltech.py", line 52, in __init__
    self.download()
  File "/Users/nshulga/miniconda3/envs/py_38/lib/python3.8/site-packages/torchvision/datasets/caltech.py", line 124, in download
    download_and_extract_archive(
  File "/Users/nshulga/miniconda3/envs/py_38/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 427, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/Users/nshulga/miniconda3/envs/py_38/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 135, in download_url
    return download_file_from_google_drive(file_id, root, filename, md5)
  File "/Users/nshulga/miniconda3/envs/py_38/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 204, in download_file_from_google_drive
    import requests
ModuleNotFoundError: No module named 'requests'
```

### Versions

0.11.1 on MacOS

**Comment by datumbox** [comment]
I believe the dependency is on purpose not in the mandatory list. It's considered optional (see old issue at #2618).

The only use of the `requests` is at:
https://github.com/pytorch/vision/blob/d367a01a18a3ae6bee13d8be3b63fd6a581ea46f/torchvision/datasets/utils.py#L203-L217

**Comment by malfet** [comment]
@datumbox in that case it should be add to extra_deps, same as scipy, shouldn't it?

**Comment by datumbox** [comment]
@malfet I've had a quick look to see what other optional dependencies we are using. Here is a list: 
- IO:
  - `accimage`
  - `av`
- Datasets:
  - `torchdata` (Prototype-only)
  - `scipy`
  - `pycocotools`
  - `lmdb`
  - `requests`

Judging from the discussion at #2618, it seems that there is consensus on keeping track of the optional dependencies but also maintaining lazy imports. Not sure what's the best way to achieve this in Conda, any thoughts?

**Comment by malfet** [comment]
Don't know about conda, but we can totally do it for pip. Also, a nicer error message would be great (and perhaps in case of requests, one can use urllib instead)

**Comment by fmassa** [comment]
If the only use of `requests` is in that function, I think I would go with @malfet suggestion of re-implementing that function instead using `urllib`. We already use `urllib` in most of that file.

About the dependencies on `scipy` / `pycocotools` / `lmdb` / etc, they are all dataset-dependent and in some sense fair requirements for the user to manually install those libraries if they want to use those datasets.

But for `download_file_from_google_drive`, I would indeed just re-implement this function in this case.

**Comment by datumbox** [comment]
@pmeier Could you have a look if it makes sense replacing `requests` with `urllib`? I assume you are using `requests.Session` to handle the cookies for you. I wonder how much extra code we need to maintain to replace it.

Concerning the original question at hand, do we want to declare the optional dependencies somehow? The benefit of tracking them explicitly is that we don't have to scan the code-base to find dependencies. As @malfet said, setuptools has a way to do it using the `extras_require` field. 

We could add something like the following to keep track of them:
```python
        extras_require={
            "scipy": ["scipy"],
            "pycocotools": ["pycocotools"],
            "lmdb": ["lmdb"],
            "requests": ["requests"],
            "accimage": ["accimage"],
            "av": ["av"],
        },
```

An alternative approach is to group them by usage. Something like:
```python
        extras_require={
            "datasets": ["scipy", "pycocotools", "lmdb", "requests"],
            "io": ["accimage", "av"],
        },
```

I would probably prefer the 1st approach as it gives more control but I would be OK with the latter as well. Thoughts?

**Comment by pmeier** [comment]
> Could you have a look if it makes sense replacing `requests` with `urllib`? I assume you are using `requests.Session` to handle the cookies for you. I wonder how much extra code we need to maintain to replace it.

If you look at the linked StackOverflow thread

https://github.com/pytorch/vision/blob/30f4d108319b0cd28ae5662947e300aad98c32e9/torchvision/datasets/utils.py#L202

you see that this is almost a 1-to-1 copy. I'm fairly certain it wouldn't be hard to replicate using only `urllib`.

> We could add something like the following to keep track of them:

I would prefer option 2. Going from `pip install torchvision scipy pycocotools` to `pip install torchvision[scipy, pycocotools]` isn't really much easier. Plus, if the requirements change in the future, we don't need to change the docs, since `pip install torchvision[datasets]` would still give you anything you need to run the datasets.

**Comment by datumbox** [comment]
>  I'm fairly certain it wouldn't be hard to replicate using only urllib.

Sounds great, would you mind creating a low priority issue to fix this? Until then, we could add this `requests` as an optional dependency.

> I would prefer option 2.

No strong opinions. My motivation for adding them there, is to keep an explicit list of all dependencies, because now we need to scan the code-base fo figure them out. @fmassa thoughts?

**Comment by NicolasHug** [comment]
I would go with option 2 as well

**Comment by datumbox** [comment]
@pmeier Would you be interested in sending a PR that fixes this? Perhaps taking the time to update the CI scripts from installing the dependencies separately?
