### ISSUE TITLE
read_image from torchvision.io failing

### ISSUE THREAD

**Issue by robertodessi** [pytorch/vision#5002]
### 🐛 Describe the bug

Following [this guide](https://pytorch.org/vision/master/auto_examples/plot_visualization_utils.html) I get an error when using the torchvision read_image method.

```python
from torchvision.io import read_image
p = "path_to_image"
img = read_image(Path(p)) 
```

```
Traceback (most recent call last):                                                                                           
  File "<stdin>", line 1, in <module>                                                                                        
  File "/rdessi/miniconda3/envs/egg/lib/python3.7/site-packages/torchvision/io/image.py", line 250, in read_image
    data = read_file(path)                                                                                                   
  File "/rdessi/miniconda3/envs/egg/lib/python3.7/site-packages/torchvision/io/image.py", line 80, in read_file 
    data = torch.ops.image.read_file(path)
  File "/rdessi/miniconda3/envs/egg/lib/python3.7/site-packages/torch/_ops.py", line 61, in __getattr__         
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator image::read_file 
```

### Versions

```
PyTorch version: 1.7.0
Is debug build: True

CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.10

Python version: 3.7.6 (default, Jan  8 2020, 19:59:22)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-52-generic-x86_64-with-debian-bullseye-sid
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 450.80.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A 

Versions of relevant libraries:
[pip3] mypy==0.790
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.19.2
[pip3] torch==1.7.0
[pip3] torchaudio==0.7.0a0+ac17b64
[pip3] torchvision==0.9.0   
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.2.0            py37h23d657b_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] mypy                      0.790                    pypi_0    pypi
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.19.2           py37h54aff64_0    
[conda] numpy-base                1.19.2           py37hfa32c7d_0
[conda] pytorch                   1.7.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchaudio                0.7.0                      py37    pytorch
[conda] torchvision               0.8.1                    pypi_0    pypi
```

**Comment by NicolasHug** [comment]
Thanks for the report @robertodessi , it looks like you're using an old version of torchvision. Could you please update to the latest 0.11 version and try again? Thanks

**Comment by zhiqwang** [comment]
And seems the versions of torch and torchvision are inconsistent, if you want to use torchvision 0.9.x, you could install torch 1.8.x.

**Comment by robertodessi** [comment]
Upgrading to the latest pytorch and torchvision worked. Thanks!
