### ISSUE TITLE
Installation fails using PDM

### ISSUE THREAD

**Issue by classner** [pytorch/vision#5371]
### 🐛 Describe the bug

Within a pdm project, running `pdm add torchvision` results in:

```
ERRORS:
add torchvision failed:
Traceback (most recent call last):
  File "c:\users\classner\.pyenv\pyenv-win\versions\3.9.0\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\classner\AppData\Roaming\Python\Python39\site-packages\pdm\installers\synchronizers.py", line 190, in install_candidate 
    self.manager.install(can)
  File "C:\Users\classner\AppData\Roaming\Python\Python39\site-packages\pdm\installers\manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "C:\Users\classner\AppData\Roaming\Python\Python39\site-packages\pdm\installers\installers.py", line 176, in install_wheel        
    _install_wheel(
  File "C:\Users\classner\AppData\Roaming\Python\Python39\site-packages\pdm\installers\installers.py", line 280, in _install_wheel       
    for record_elements, stream in source.get_contents():
  File "C:\Users\classner\AppData\Roaming\Python\Python39\site-packages\installer\sources.py", line 170, in get_contents
    assert record is not None, "In {}, {} is not mentioned in RECORD".format(
AssertionError: In C:\Users\classner\AppData\Local\Temp\pip-unpack-49uvth_n\torchvision-0.11.2+cu113-cp39-cp39-win_amd64.whl, torchvision/extension.py is not mentioned in RECORD
```

It seems the pip RECORD file is not correctly built for torchvision. Similar issues are being detected for other packages, too, for example: https://github.com/microsoft/playwright-python/issues/518 .

### Versions

Currently tested with 0.11.2+cu113-cp39-cp39 .

**Comment by goigle** [comment]
Still fails on 0.13.1 and 0.13.0, with a new error about the license:

```
ERRORS:
add torchvision failed:
Traceback (most recent call last):
  File "C:\Users\James\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\James\AppData\Roaming\pdm\venv\lib\site-packages\pdm\installers\synchronizers.py", line 225, in install_candidate
    self.manager.install(can)
  File "C:\Users\James\AppData\Roaming\pdm\venv\lib\site-packages\pdm\installers\manager.py", line 39, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
    _install_wheel(
  File "C:\Users\James\AppData\Roaming\pdm\venv\lib\site-packages\pdm\installers\installers.py", line 279, in _install_wheel
    install(source, destination, additional_metadata=additional_metadata or {})
  File "C:\Users\James\AppData\Roaming\pdm\venv\lib\site-packages\installer\_core.py", line 96, in install
    for record_elements, stream, is_executable in source.get_contents():
  File "C:\Users\James\AppData\Roaming\pdm\venv\lib\site-packages\pdm\installers\installers.py", line 131, in get_contents
    for element in super().get_contents():
  File "C:\Users\James\AppData\Roaming\pdm\venv\lib\site-packages\installer\sources.py", line 158, in get_contents
    assert record is not None, "In {}, {} is not mentioned in RECORD".format(
AssertionError: In C:\Users\James\AppData\Local\Temp\pdm-build-sbwxcq_b\torchvision-0.13.0-cp310-cp310-win_amd64.whl, torchvision-0.13.0.dist-info/LICENSE is not mentioned in RECORD
```

**Comment by groodt** [comment]
This error also exists with `0.14.0`

**Comment by 1e100** [comment]
Ran into this under Bazel when using `rules_python`
