### ISSUE TITLE
RecursionError is raised when calling a GraphModule created with create_feature_extractor

### ISSUE THREAD

**Issue by kzkadc** [pytorch/vision#5826]
### 🐛 Describe the bug

RecursionError is raised when calling a GraphModule created with create_feature_extractor.

I created an feature extractor with `create_feature_extractor` from resnet.
When calling it with training and eval mode alternatively in a training loop, RecursionError is raised in the middle of the loop.

Here is an example code reproducing the error:

```python
from torchvision.models import resnet18
from torchvision.models.feature_extraction import create_feature_extractor
import torch

net = resnet18()
fe = create_feature_extractor(net, {"avgpool": "feature", "fc": "logit"})

for _ in range(10000):
    x = torch.rand(1, 3, 224, 224).float()
    fe.zero_grad()
    fe.train()
    out = fe(x)

    fe.eval()
    out = fe(x)
```

And here is the trace back:

```
Traceback (most recent call last):
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\fx\graph_module.py", line 622, in wrapped_call
    return super(type(self), self).__call__(*args, **kwargs)
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.993", line 5, in forward
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\fx\graph_module.py", line 620, in wrapped_call
    return cls_call(self, *args, **kwargs)
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\fx\graph_module.py", line 626, in wrapped_call
    traceback.StackSummary.extract(traceback.walk_tb(e.__traceback__))[-1]  # type: ignore[arg-type]
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\traceback.py", line 366, in extract
    f.line
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\traceback.py", line 288, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\linecache.py", line 30, in getline
    lines = getlines(filename, module_globals)
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\tokenize.py", line 392, in open
    buffer = _builtin_open(filename, 'rb')
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\tokenize.py", line 394, in open
    encoding, lines = detect_encoding(buffer.readline)
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\tokenize.py", line 363, in detect_encoding
    first = read_or_stop()
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\tokenize.py", line 321, in read_or_stop
    return readline()
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\fx\graph_module.py", line 620, in wrapped_call
    return cls_call(self, *args, **kwargs)
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\fx\graph_module.py", line 626, in wrapped_call
    traceback.StackSummary.extract(traceback.walk_tb(e.__traceback__))[-1]  # type: ignore[arg-type]
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\traceback.py", line 366, in extract
    f.line
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\traceback.py", line 288, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\linecache.py", line 30, in getline
    lines = getlines(filename, module_globals)
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\tokenize.py", line 400, in open
    buffer.close()
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxxxxxx\Desktop\test.py", line 15, in <module>
    out = fe(x)
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\fx\graph_module.py", line 630, in wrapped_call
    raise e.with_traceback(None)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

### Versions

Collecting environment information...
PyTorch version: 1.11.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: (x86_64-posix-seh, Built by strawberryperl.com project) 8.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:52:46) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: True
CUDA runtime version: 11.5.119
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 512.15
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] pytorch-ignite==0.4.8
[pip3] torch==1.11.0+cu113
[pip3] torchaudio==0.11.0+cu113
[pip3] torchvision==0.12.0+cu113
[pip3] torchviz==0.0.2
[conda] Could not collect

**Comment by datumbox** [comment]
@kzkadc Thanks for the report. I'm able to reproduce the issue.

Here is a faster version based on your script:
```
from torchvision.models import resnet18
from torchvision.models.feature_extraction import create_feature_extractor
import torch

net = resnet18()
fe = create_feature_extractor(net, {"avgpool": "feature", "fc": "logit"})

x = torch.rand(1, 3, 33, 33).float()
for i in range(500):
	if i % 100 == 0:
		print(i)
	fe.zero_grad()
	fe.train()
	out = fe(x)

	fe.eval()
	out = fe(x)
```

@jamesr66a I had a quick look and I suspect this is on the FX side. Is this a known issue?

**Comment by jamesr66a** [comment]
Hi folks,

This is a weird interaction between torchvision's custom `GraphModule` subclass [DualGraphModule](https://github.com/pytorch/vision/blob/main/torchvision/models/feature_extraction.py) and the fact that `GraphModule` is actually a metaclass/class template that instantiates a new type for each compiled graph.

Concretely, the root cause is:
1. `fe.train()` (or `fe.eval()`) is called, which dispatches into [DualGraphModule.train](https://github.com/pytorch/vision/blob/e8cb0bacd86c49e67a7e1a5f83c6da866bc451cf/torchvision/models/feature_extraction.py#L316)
2. `DualGraphModule.train` in turn [assigns](https://github.com/pytorch/vision/blob/e8cb0bacd86c49e67a7e1a5f83c6da866bc451cf/torchvision/models/feature_extraction.py#L325) the `graph` attribute which calls into the [fx.GraphModule.graph property setter](https://github.com/pytorch/pytorch/blob/a5cb0d6be4a229bfffb6484390c3db237aab112d/torch/fx/graph_module.py#L337)
3. The `GraphModule.graph` setter calls [recompile()](https://github.com/pytorch/pytorch/blob/a5cb0d6be4a229bfffb6484390c3db237aab112d/torch/fx/graph_module.py#L346) to update the generated `forward()` function
4. `recompile()` installs the compiled `forward` function, but also [installs](https://github.com/pytorch/pytorch/blob/a5cb0d6be4a229bfffb6484390c3db237aab112d/torch/fx/graph_module.py#L634) an exception-handling `__call__` wrapper for debug purposes. HOWEVER, this `__call__` wrapper closes over the _existing_ `__call__` implementation such that if a custom class implements `__call__` we still call it, but it does not recognize that the previously-installed `__call__` is the same `wrapped_call` implementation that was installed from another call to `compile`, thus it creates an increasingly-long chain of `__call__` implementations, adding one each time `train()` or `eval()` is called (which in turn calls `recompile()`).

This is indeed an issue in `torch.fx` that has not been seen before since other users have not called `recompile()` (potentially) infinitely many times. I have pulled out an even more isolated repro for this:

```
import torch
import torch.fx

def foo(x):
    return torch.relu(x)

traced = torch.fx.symbolic_trace(foo)

x = torch.randn(5, 3)

while True:
    traced.recompile()
    traced(x)
```

I've written a quick patch to try to address this: https://gist.github.com/jamesr66a/ef1e85bbc7e9db77245bd7032d7ca971

I'll see if I can get someone to PR this into PyTorch to fix this. In the meantime, maybe the patch can be backported to torchvision to unblock?

**Comment by jamesr66a** [comment]
Put the fix in a PR https://github.com/pytorch/pytorch/pull/76068

**Comment by kzkadc** [comment]
Thank you for your prompt action!

**Comment by BadrYoubiIdrissi** [comment]
Hi ! This issue has been closed but it seems the [PR](https://github.com/pytorch/pytorch/pull/76068) that addresses this issue hasn't been merged in the end ?

**Comment by jamesr66a** [comment]
That PR was indeed merged in the following commit: https://github.com/pytorch/pytorch/commit/bf730e5039e8bf1614de6ad08ac6a24a1622dcbe


On Jun 5, 2022, at 3:44 AM, Badr YOUBI IDRISSI ***@***.***> wrote:

﻿

Hi ! This issue has been closed but it seems the PR<https://github.com/pytorch/pytorch/pull/76068> that addresses this issue hasn't been merged in the end ?
