### ISSUE TITLE
TorchVision Main branch fails with `slow_conv2d: grad_weight must be contiguous`

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#6001]
### 🐛 Describe the bug

It looks like a breakage caused by the 20220512 PyTorch Core Nightly.

Several CI jobs [fail](https://app.circleci.com/pipelines/github/pytorch/vision/17513/workflows/17907a0c-5758-4f80-a599-83dce6aecba9/jobs/1418004) with:
```
test_classification_model[cpu-convnext_base]
Traceback (most recent call last):
  File "/root/project/test/test_models.py", line 628, in test_classification_model
    _check_input_backprop(model, x)
  File "/root/project/test/test_models.py", line 181, in _check_input_backprop
    out[0].sum().backward()
  File "/root/project/env/lib/python3.10/site-packages/torch/_tensor.py", line 399, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/project/env/lib/python3.10/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: slow_conv2d: grad_weight must be contiguous
```

So far I've identified the following PRs as potential causes:
- https://github.com/pytorch/pytorch/pull/68101
- https://github.com/pytorch/pytorch/pull/70665

Given that this network uses LayerNorm changes from the following PRs are also like to have caused it:
- https://github.com/pytorch/pytorch/pull/71376
- https://github.com/pytorch/pytorch/pull/73844

cc @mingfeima @VitalyFedyunin

### Versions

Latest main branch 03bb324576d9fe86a15a7b86a43638a838234fbd

**Comment by mingfeima** [comment]
@datumbox  is there any method to run the a single failed test case, for example, `test_classification_model`? That would be easier to debug the issue.

**Comment by datumbox** [comment]
@mingfeima Thanks fore coming back to me.

You can run something like:
```
pytest test/test_models.py -k "convnext"
```

2 out of the 4 variants of convnext fail.

**Comment by mingfeima** [comment]
#77347 is submitted to fix this failure @datumbox 

My local run with -k "convnext" passed:
```
(pytorch-mingfei) [mingfeim@mlt-skx089 test]$ pytest test_models.py -k "convnext"
======================================================================== test session starts =========================================================================
platform linux -- Python 3.7.11, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/mingfeim/pytorch/vision, configfile: pytest.ini
plugins: hypothesis-6.23.3, hydra-core-1.1.1
collected 253 items / 245 deselected / 8 selected

test_models.py ....ssss                                                                                                                                        [100%]

========================================================================== warnings summary ==========================================================================
../../../anaconda3/envs/pytorch-mingfei/lib/python3.7/site-packages/torchvision-0.13.0a0+9166b67-py3.7-linux-x86_64.egg/torchvision/io/image.py:13
  /home/mingfeim/anaconda3/envs/pytorch-mingfei/lib/python3.7/site-packages/torchvision-0.13.0a0+9166b67-py3.7-linux-x86_64.egg/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension:
    warn(f"Failed to load image Python extension: {e}")

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
====================================================================== short test summary info =======================================================================
SKIPPED [4] test_models.py:595: CUDA device not available
====================================================== 4 passed, 4 skipped, 245 deselected, 1 warning in 13.90s ======================================================
```

**Comment by datumbox** [comment]
@mingfeima Thanks for the ultra prompt fix. 

Could you confirm that the test fails on your local without the patch? I ask because for some reason, the failure seems OS specific. It fails on Linux and Windows on CPU but not on Mac.

**Comment by mingfeima** [comment]
yes, they used to fail without the patch, the following is the old log (i add some log for debugging purpose):
```
(pytorch-mingfei) [mingfeim@mlt-skx089 test]$ pytest test_models.py -k "convnext"
======================================================================== test session starts =========================================================================
platform linux -- Python 3.7.11, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/mingfeim/pytorch/vision, configfile: pytest.ini
plugins: hypothesis-6.23.3, hydra-core-1.1.1
collected 253 items / 245 deselected / 8 selected

test_models.py ..FFssss                                                                                                                                        [100%]

============================================================================== FAILURES ==============================================================================
____________________________________________________________ test_classification_model[cpu-convnext_base] ____________________________________________________________
Traceback (most recent call last):
  File "/home/mingfeim/pytorch/vision/test/test_models.py", line 628, in test_classification_model
    _check_input_backprop(model, x)
  File "/home/mingfeim/pytorch/vision/test/test_models.py", line 181, in _check_input_backprop
    out[0].sum().backward()
  File "/home/mingfeim/anaconda3/envs/pytorch-mingfei/lib/python3.7/site-packages/torch/_tensor.py", line 399, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/mingfeim/anaconda3/envs/pytorch-mingfei/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: slow_conv2d: grad_weight must be contiguous
------------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------------
slow_conv2d_backward_out_cpu:
input.sizes(): [1, 512, 4, 4]; [8192, 1, 2048, 512]
grad_output.sizes(): [1, 1024, 2, 2]; [4096, 4, 2, 1]
weight.sizes(): [1024, 512, 2, 2]; [2048, 4, 2, 1]
### slow_conv2d_backward_weight_out_cpu_template
input.sizes(): [1, 512, 4, 4]; [8192, 1, 2048, 512]
grad_weight.sizes(): [1024, 512, 2, 2]; [2048, 4, 2, 1]
___________________________________________________________ test_classification_model[cpu-convnext_large] ____________________________________________________________
Traceback (most recent call last):
  File "/home/mingfeim/pytorch/vision/test/test_models.py", line 628, in test_classification_model
    _check_input_backprop(model, x)
  File "/home/mingfeim/pytorch/vision/test/test_models.py", line 181, in _check_input_backprop
    out[0].sum().backward()
  File "/home/mingfeim/anaconda3/envs/pytorch-mingfei/lib/python3.7/site-packages/torch/_tensor.py", line 399, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/mingfeim/anaconda3/envs/pytorch-mingfei/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: slow_conv2d: grad_weight must be contiguous
------------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------------
slow_conv2d_backward_out_cpu:
input.sizes(): [1, 768, 4, 4]; [12288, 1, 3072, 768]
grad_output.sizes(): [1, 1536, 2, 2]; [6144, 4, 2, 1]
weight.sizes(): [1536, 768, 2, 2]; [3072, 4, 2, 1]
### slow_conv2d_backward_weight_out_cpu_template
input.sizes(): [1, 768, 4, 4]; [12288, 1, 3072, 768]
grad_weight.sizes(): [1536, 768, 2, 2]; [3072, 4, 2, 1]
========================================================================== warnings summary ==========================================================================
../../../anaconda3/envs/pytorch-mingfei/lib/python3.7/site-packages/torchvision-0.13.0a0+9166b67-py3.7-linux-x86_64.egg/torchvision/io/image.py:13
  /home/mingfeim/anaconda3/envs/pytorch-mingfei/lib/python3.7/site-packages/torchvision-0.13.0a0+9166b67-py3.7-linux-x86_64.egg/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension:
    warn(f"Failed to load image Python extension: {e}")

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
====================================================================== short test summary info =======================================================================
SKIPPED [4] test_models.py:595: CUDA device not available
FAILED test_models.py::test_classification_model[cpu-convnext_base] - RuntimeError: slow_conv2d: grad_weight must be contiguous
FAILED test_models.py::test_classification_model[cpu-convnext_large] - RuntimeError: slow_conv2d: grad_weight must be contiguous
================================================= 2 failed, 2 passed, 4 skipped, 245 deselected, 1 warning in 13.54s =================================================
```

**Comment by datumbox** [comment]
Awesome, thanks for confirming.

**Comment by mingfeima** [comment]
i will check if i need to add more test case in pytorch (the old test cases failed to find out the code flaw)

**Comment by datumbox** [comment]
Fixed on latest nightly
