### ISSUE TITLE
pyinstaller for pytorch error:File "torch/_utils_internal.py", line 49, in get_source_lines_and_file !

### ISSUE THREAD

**Issue by tms2003** [pytorch/vision#6063]
### 🐛 Describe the bug

I use pyinstaller to package pytorch, and I got this error:
```
Traceback (most recent call last):
  File "torch/_utils_internal.py", line 49, in get_source_lines_and_file
    sourcelines, file_lineno = inspect.getsourcelines(obj)
  File "inspect.py", line 955, in getsourcelines
  File "inspect.py", line 786, in findsource
OSError: could not get source code

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "aithreadv5.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "detectv5.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "timm/__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "timm/models/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "timm/models/beit.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "timm/models/helpers.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "timm/models/fx_features.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "timm/models/layers/__init__.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "timm/models/layers/conv_bn_act.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "timm/models/layers/create_norm_act.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "timm/models/layers/norm_act.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "timm/models/layers/create_act.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "timm/models/layers/activations_jit.py", line 19, in <module>
  File "torch/jit/_script.py", line 936, in script
    ast = get_jit_def(obj, obj.__name__)
  File "torch/jit/frontend.py", line 197, in get_jit_def
    sourcelines, file_lineno, filename = get_source_lines_and_file(fn, torch._C.ErrorReport.call_stack())
  File "torch/_utils_internal.py", line 56, in get_source_lines_and_file
    raise OSError(msg) from e
OSError: Can't get source for <function swish_jit at 0x7f4937d1e4d0>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.

```

the error reason is from this code:
```
@torch.jit.script
def swish_jit(x, inplace: bool = False):
    """Swish - Described in: https://arxiv.org/abs/1710.05941
    """
    return x.mul(x.sigmoid())
```
if I use @torch.jit.script, the error is appear.

I also got the post:https://github.com/pytorch/vision/issues/1899,it told me that :

>  As such, I'm closing this issue as I believe this should be fixed with the 0.7.0 release, but please let us know if this isn't fixed when the 0.7.0 release comes out

### Versions

orch                     1.7.1              
torchaudio                0.7.2              
torchvision               0.8.2

**Comment by pmeier** [comment]
From the other issue you linked, it seems `pyinstaller` and `torch.jit.script` don't work well together. Have you tried https://github.com/pytorch/vision/issues/1899#issuecomment-598200938?

**Comment by tms2003** [comment]
@pmeier I try this:
>  We have now hopefully fix this issue by replacing instances of @torch.jit.script with @torch.jit._script_if_tracing

it's work for me,other trick is not ok .but I thank this is not so good.

**Comment by pmeier** [comment]
Sorry, I'm not sure I understand. What is your goal here? Do you want to use `torch.jit.script` or not?

- If no, the patch in https://github.com/pytorch/vision/issues/1899#issuecomment-598200938 should suffice.
- If yes, you are probably out of luck. It seems that `pyinstaller` is not compatible with `torch.jit`. `torch.jit` needs to use [`inspect.getsourcefile`](https://docs.python.org/3/library/inspect.htmlt#inspect.getsourcefile) and [`inspect.getsourcelines`](https://docs.python.org/3/library/inspect.htmlt#inspect.getsourcelines) to create the computation graph. If that is somehow not accessible through `pyinstaller` than there is nothing we can do.

**Comment by tms2003** [comment]
@pmeier 
thanks your reply,I got this point.

**Comment by raghotham007** [comment]
I also added this in main file

```
def script_method(fn, _rcb=None):
    return fn
def script(obj, optimize=True, _frames_up=0, _rcb=None):
    return obj    
import torch.jit
torch.jit.script_method = script_method 
torch.jit.script = script
```


And this in spec file
```

datas += collect_data_files('timm', include_py_files=True)
datas += collect_data_files('torchvision', include_py_files=True)
```

Then worked
