### ISSUE TITLE
Error with training Faster R-CNN 

### ISSUE THREAD

**Issue by pengwenyu** [pytorch/vision#6118]
### 🐛 Describe the bug

Hi, I am using faster r-cnn to train our own COCO datasets. However, when I pass the arguments to the train.py, it shows me the error. I checked the source code of faster rcnn and there is no weights argument. Could you please help me fix this issue?

Loading data
loading annotations into memory...
Done (t=0.09s)
creating index...
index created!
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
151
Creating data loaders
Using [0, 0.5, 0.6299605249474366, 0.7937005259840997, 1.0, 1.2599210498948732, 1.5874010519681994, 2.0, inf] as bins for aspect ratio quantization
Count of instances per bin: [5952]
Creating model
Traceback (most recent call last):
  File "train.py", line 288, in <module>
    main(args)
  File "train.py", line 200, in main
    weights=args.weights, weights_backbone=args.weights_backbone, num_classes=num_classes, **kwargs
  File "/home/liulab/anaconda3/envs/wenyu/lib/python3.6/site-packages/torchvision/models/detection/faster_rcnn.py", line 371, in fasterrcnn_resnet50_fpn
    model = FasterRCNN(backbone, num_classes, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'weights'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1)

### Versions

Collecting environment information...
PyTorch version: 1.10.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.2 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-142-generic-x86_64-with-debian-stretch-sid
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1660 Ti
Nvidia driver version: 460.27.04
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] torch==1.10.1
[pip3] torchaudio==0.9.0
[pip3] torchfile==0.1.0
[pip3] torchvision==0.11.2
[conda] numpy                     1.16.2                   pypi_0    pypi
[conda] torch                     1.10.1                   pypi_0    pypi
[conda] torchaudio                0.9.0                    pypi_0    pypi
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchvision               0.11.2                   pypi_0    pypi

**Comment by pengwenyu** [comment]
> 

Could you tell me how to install the nightly version?  I use pip and I can just get 0.11.3.
