### ISSUE TITLE
M1 unit-test fail with `not yet supported with named tensors`

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#6142]
### 🐛 Describe the bug

The M1 unit-tests [fail](https://github.com/pytorch/vision/runs/6806004576?check_suite_focus=true) with the following error:
```
self = <OpOverloadPacket(op='torchvision.roi_align')>
args = (tensor([[[[ 8.2470e+00,  1.3783e+01,  1.3401e+01,  ...,  2.4769e+00,
            2.6093e+00,  6.0664e+00],
          ...68.9164],
        [  0.0000, 175.5915, 200.8642, 382.0600, 212.2028]],
       dtype=torch.float64), 0.25, 7, 7, 2, ...)
kwargs = {}
    def __call__(self, *args, **kwargs):
        # overloading __call__ to ensure torch.ops.foo.bar()
        # is still callable from JIT
        # We save the function ptr as the `op` attribute on
        # OpOverloadPacket to access it here.
>       return self._op(*args, **kwargs or {})
E       RuntimeError: torchvision::roi_align is not yet supported with named tensors. Please drop names via `tensor = tensor.rename(None)`, call the op with an unnamed tensor, and set names on the result of the operation.
```

The last time the tests run successfully was on the 6th of June at commit d4a03fc02d0566ec97341046de58160370a35bd2. Unfortunately the days after that our CI broke for unrelated issues, so I guess it could be a commit commits from Core between the 6th and 9th of June.

### Versions

Latest main branch.

**Comment by vfdev-5** [comment]
I bit more coherent info on failing/passing tests according to the latest job from #6145 : 

https://github.com/pytorch/vision/runs/6815037410?check_suite_focus=true

TestRoiPool::test_forward is passing until dev20220520 and since May 20 the error is
```python
NotImplementedError: Could not run 'torchvision::roi_pool' with arguments from the 'MkldnnCPU' backend. 
```
and since dev20220601 it started failing with 
```
RuntimeError: torchvision::roi_pool is not yet supported with named tensors
```

**Comment by albanD** [comment]
@vfdev-5 could you set `TORCH_SHOW_CPP_STACKTRACES=1` for each of these to get the full c++ stacktrace?

**Comment by malfet** [comment]
Looks like something is wrong with how we setup cross-compilation: if both PyTorch and TorchVision are build on MacOS-12.4 machine, they work fine together, but downloading cross-compiled nightly package and building vision locally reproduces the error

**Comment by malfet** [comment]
> @vfdev-5 could you set `TORCH_SHOW_CPP_STACKTRACES=1` for each of these to get the full c++ stacktrace?

```
Traceback (most recent call last):
  File "/Users/malfet/foo.py", line 20, in <module>
    test_m1_operator()
  File "/Users/malfet/foo.py", line 16, in test_m1_operator
    y = m(x, rois)
  File "/Users/malfet/miniconda3/envs/conda-nightly-test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/malfet/miniconda3/envs/conda-nightly-test/lib/python3.9/site-packages/torchvision/ops/ps_roi_pool.py", line 64, in forward
    return ps_roi_pool(input, rois, self.output_size, self.spatial_scale)
  File "/Users/malfet/miniconda3/envs/conda-nightly-test/lib/python3.9/site-packages/torchvision/ops/ps_roi_pool.py", line 48, in ps_roi_pool
    output, _ = torch.ops.torchvision.ps_roi_pool(input, rois, spatial_scale, output_size[0], output_size[1])
  File "/Users/malfet/miniconda3/envs/conda-nightly-test/lib/python3.9/site-packages/torch/_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: torchvision::ps_roi_pool is not yet supported with named tensors. Please drop names via `tensor = tensor.rename(None)`, call the op with an unnamed tensor, and set names on the result of the operation.
Exception raised from named_not_supported_kernel at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1654758521505/work/aten/src/ATen/core/boxing/KernelFunction.cpp:41 (most recent call first):
frame #0: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 92 (0x101aec938 in libc10.dylib)
frame #1: c10::named_not_supported_kernel(c10::OperatorKernel*, c10::OperatorHandle const&, c10::DispatchKeySet, std::__1::vector<c10::IValue, std::__1::allocator<c10::IValue> >*) + 72 (0x10c875790 in libtorch_cpu.dylib)
frame #2: at::native::MathOpFallback::fallback_impl(c10::OperatorHandle const&, c10::DispatchKeySet, std::__1::vector<c10::IValue, std::__1::allocator<c10::IValue> >*) + 2968 (0x10c7918cc in libtorch_cpu.dylib)
frame #3: at::native::conjugateFallback(c10::OperatorHandle const&, c10::DispatchKeySet, std::__1::vector<c10::IValue, std::__1::allocator<c10::IValue> >*) + 148 (0x10c790cd8 in libtorch_cpu.dylib)
frame #4: c10::impl::BoxedKernelWrapper<std::__1::tuple<at::Tensor, at::Tensor> (at::Tensor const&, at::Tensor const&, double, long long, long long), void>::call(void (*)(c10::OperatorKernel*, c10::OperatorHandle const&, c10::DispatchKeySet, std::__1::vector<c10::IValue, std::__1::allocator<c10::IValue> >*), c10::OperatorKernel*, c10::OperatorHandle const&, c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, double, long long, long long) + 92 (0x10c05cd3c in _C.so)
frame #5: vision::ops::ps_roi_pool(at::Tensor const&, at::Tensor const&, double, long long, long long) + 464 (0x10c05baac in _C.so)
frame #6: c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<std::__1::tuple<at::Tensor, at::Tensor> (at::Tensor const&, at::Tensor const&, double, long long, long long), &(vision::ops::(anonymous namespace)::ps_roi_pool_autograd(at::Tensor const&, at::Tensor const&, double, long long, long long))>, std::__1::tuple<at::Tensor, at::Tensor>, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&, double, long long, long long> >, std::__1::tuple<at::Tensor, at::Tensor> (at::Tensor const&, at::Tensor const&, double, long long, long long)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, double, long long, long long) + 2328 (0x10c017e5c in _C.so)
frame #7: c10::impl::make_boxed_from_unboxed_functor<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<std::__1::tuple<at::Tensor, at::Tensor> (at::Tensor const&, at::Tensor const&, double, long long, long long), &(vision::ops::(anonymous namespace)::ps_roi_pool_autograd(at::Tensor const&, at::Tensor const&, double, long long, long long))>, std::__1::tuple<at::Tensor, at::Tensor>, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&, double, long long, long long> >, false>::call(c10::OperatorKernel*, c10::OperatorHandle const&, c10::DispatchKeySet, std::__1::vector<c10::IValue, std::__1::allocator<c10::IValue> >*) + 116 (0x10c017310 in _C.so)
frame #8: c10::Dispatcher::callBoxed(c10::OperatorHandle const&, std::__1::vector<c10::IValue, std::__1::allocator<c10::IValue> >*) const + 296 (0x10c754374 in libtorch_cpu.dylib)
frame #9: torch::jit::invokeOperatorFromPython(std::__1::vector<std::__1::shared_ptr<torch::jit::Operator>, std::__1::allocator<std::__1::shared_ptr<torch::jit::Operator> > > const&, pybind11::args, pybind11::kwargs const&) + 296 (0x103292348 in libtorch_python.dylib)
frame #10: torch::jit::_get_operation_for_overload_or_packet(std::__1::vector<std::__1::shared_ptr<torch::jit::Operator>, std::__1::allocator<std::__1::shared_ptr<torch::jit::Operator> > > const&, c10::Symbol, pybind11::args, pybind11::kwargs const&, bool) + 1416 (0x103291a08 in libtorch_python.dylib)
frame #11: void pybind11::cpp_function::initialize<torch::jit::initJITBindings(_object*)::$_147::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const::'lambda'(pybind11::args, pybind11::kwargs), pybind11::object, pybind11::args, pybind11::kwargs, pybind11::name, pybind11::doc>(torch::jit::initJITBindings(_object*)::$_147::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const::'lambda'(pybind11::args, pybind11::kwargs)&&, pybind11::object (*)(pybind11::args, pybind11::kwargs), pybind11::name const&, pybind11::doc const&)::'lambda'(pybind11::detail::function_call&)::__invoke(pybind11::detail::function_call&) + 108 (0x103297d50 in libtorch_python.dylib)
frame #12: pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3524 (0x102c954cc in libtorch_python.dylib)
frame #13: cfunction_call + 60 (0x100e64be4 in python3.9)
frame #14: _PyObject_Call + 128 (0x100e08bbc in python3.9)
frame #15: _PyEval_EvalFrameDefault + 2200 (0x100f226f0 in python3.9)
frame #16: _PyEval_EvalCode + 496 (0x100f20898 in python3.9)
frame #17: _PyFunction_Vectorcall + 192 (0x100e08ddc in python3.9)
frame #18: _PyObject_FastCallDictTstate + 112 (0x100e082c0 in python3.9)
frame #19: slot_tp_call + 188 (0x100e8def8 in python3.9)
frame #20: _PyObject_MakeTpCall + 136 (0x100e07fe8 in python3.9)
frame #21: call_function + 312 (0x100f2e88c in python3.9)
frame #22: _PyEval_EvalFrameDefault + 23340 (0x100f27984 in python3.9)
frame #23: _PyEval_EvalCode + 496 (0x100f20898 in python3.9)
frame #24: _PyFunction_Vectorcall + 192 (0x100e08ddc in python3.9)
frame #25: call_function + 128 (0x100f2e7d4 in python3.9)
frame #26: _PyEval_EvalFrameDefault + 17012 (0x100f260cc in python3.9)
frame #27: function_code_fastcall + 168 (0x100e08ec0 in python3.9)
frame #28: method_vectorcall + 288 (0x100e0c1c4 in python3.9)
frame #29: _PyEval_EvalFrameDefault + 2200 (0x100f226f0 in python3.9)
frame #30: _PyEval_EvalCode + 496 (0x100f20898 in python3.9)
frame #31: _PyFunction_Vectorcall + 192 (0x100e08ddc in python3.9)
frame #32: _PyObject_FastCallDictTstate + 112 (0x100e082c0 in python3.9)
frame #33: slot_tp_call + 188 (0x100e8def8 in python3.9)
frame #34: _PyObject_MakeTpCall + 136 (0x100e07fe8 in python3.9)
frame #35: call_function + 312 (0x100f2e88c in python3.9)
frame #36: _PyEval_EvalFrameDefault + 17012 (0x100f260cc in python3.9)
frame #37: function_code_fastcall + 168 (0x100e08ec0 in python3.9)
frame #38: call_function + 128 (0x100f2e7d4 in python3.9)
frame #39: _PyEval_EvalFrameDefault + 17012 (0x100f260cc in python3.9)
frame #40: _PyEval_EvalCode + 496 (0x100f20898 in python3.9)
frame #41: pyrun_file + 312 (0x100f84648 in python3.9)
frame #42: pyrun_simple_file + 372 (0x100f83dac in python3.9)
frame #43: PyRun_SimpleFileExFlags + 120 (0x100f83bd8 in python3.9)
frame #44: pymain_run_file + 300 (0x100faacec in python3.9)
frame #45: pymain_run_python + 360 (0x100faa0a8 in python3.9)
frame #46: Py_RunMain + 40 (0x100fa9ee8 in python3.9)
frame #47: pymain_main + 72 (0x100fab868 in python3.9)
frame #48: main + 56 (0x100da603c in python3.9)
frame #49: start + 520 (0x10123d08c in dyld)
```

**Comment by malfet** [comment]
Interestingly enough, debug build of TorchVision does not exhibit the problem...

**Comment by malfet** [comment]
Ok, so what happened on May13th, is we've added MPS and started building M1 binaries on MacOS-12 (vs 10.15), see https://github.com/pytorch/pytorch/commit/44bf440b53cc9641086ca9462f8cab52d7dbfaa3#diff-a239f908c685d3e971663ebd1464a4904431139240f8403664183c5bcd26e47b

I.e. when the build were upgraded from [clang-12](https://github.com/pytorch/pytorch/runs/6401217923?check_suite_focus=true#step:10:719) to [clang-13](https://github.com/pytorch/pytorch/runs/6425682626?check_suite_focus=true#step:10:718)

**Comment by datumbox** [comment]
@malfet Sounds like this is not a trivial issue that might require extra work to solve. Would you like me to transfer the issue to PyTorch core, or you are happy leaving it here?

**Comment by malfet** [comment]
> @malfet Sounds like this is not a trivial issue that might require extra work to solve. Would you like me to transfer the issue to PyTorch core, or you are happy leaving it here?

@datumbox it's up to you, although torchvision issues are IMO more discoverable, and so far I'm not sure where fix should be applied: i.e. whether it should be done to vision build script or to pytorch one

**Comment by vfdev-5** [comment]
@malfet I wonder what could be done on vision's side as we are building c++ ops as cpp/cuda extensions. Some specific M1 flag to specify ?

**Comment by malfet** [comment]
@vfdev-5 I suspect so. I.e. my only explanation to what is happening: some sort of compilation flag is applied when M1 PyTorch nightly packages are build, which are not applied to torchvision. Because if I build both packages on the same machine they work fine.

**Comment by malfet** [comment]
Trying to debug how dispatch key is computed by adding following change to ps_roi_pool.cpp:
```
+  auto ks = c10::DispatchKeySet(c10::DispatchKeySet::Raw::RAW, 1271310336001);
+  auto key_mask = c10::DispatchKeySet(c10::DispatchKeySet::Raw::RAW, 8931298525577215);
+  auto rc = c10::impl::computeDispatchKeySet(ks, key_mask);
+  std::cout << "rc=" << rc << std::endl;
+  auto dispatchKeySet = op.operatorDef_->op.dispatchKeyExtractor().getDispatchKeySetUnboxed(input, rois, spatial_scale, pooled_height, pooled_width);
+  std::cout << "dispatchKeySet=" << dispatchKeySet << std::endl;
```
Which results in the following output:
```
rc=DispatchKeySet(CPU)
dispatchKeySet=DispatchKeySet(MPS, IPU, Lazy, Meta, PrivateUse2, PrivateUse3, FPGA, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, CustomRNGKeyId, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, SparseCsrCPU, Python, Fake, Named, Conjugate)
```
where according to the debugger `dispatchKeyExtractor().nonFallTrhoughKeys.repr_` is `0x001fbaf7fbffffff`
```
(lldb) p op.operatorDef_->op.dispatchKeyExtractor_
(c10::DispatchKeyExtractor) $1 = {
  dispatch_arg_indices_reverse_ = (bitset_ = 24)
  nonFallthroughKeys_ = (repr_ = 8931298525577215)
```

**Comment by malfet** [comment]
One more clue that it has something to do with ABI changes: same torchvision binary can be used for May 12th and May 13th  binaries and exhibit the issue:
```
malfet@Nikitas-Mac-mini vision % conda run -n py38-wheel-may12 python foo.py
rc=DispatchKeySet(FPGA, AutogradNestedTensor)
/Users/malfet/git/pytorch/vision/torchvision/__init__.py 1.12.0.dev20220512

malfet@Nikitas-Mac-mini vision % conda run -n py38-wheel-may13 python foo.py
rc=DispatchKeySet(FPGA, AutogradNestedTensor)
/Users/malfet/git/pytorch/vision/torchvision/__init__.py 1.12.0.dev20220513

Traceback (most recent call last):
  File "foo.py", line 22, in <module>
    test_m1_operator()
  File "foo.py", line 17, in test_m1_operator
    y = m(x, rois)
  File "/Users/malfet/miniconda3/envs/py38-wheel-may13/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1144, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/malfet/git/pytorch/vision/torchvision/ops/ps_roi_pool.py", line 64, in forward
    return ps_roi_pool(input, rois, self.output_size, self.spatial_scale)
  File "/Users/malfet/git/pytorch/vision/torchvision/ops/ps_roi_pool.py", line 48, in ps_roi_pool
    output, _ = torch.ops.torchvision.ps_roi_pool(input, rois, spatial_scale, output_size[0], output_size[1])
  File "/Users/malfet/miniconda3/envs/py38-wheel-may13/lib/python3.8/site-packages/torch/_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
NotImplementedError: Could not run 'torchvision::ps_roi_pool' with arguments from the 'Fake' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torchvision::ps_roi_pool' is only available for these backends: [Dense, Metal, UNKNOWN_TENSOR_TYPE_ID, QuantizedXPU, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, SparseCPU, SparseCUDA, SparseHIP, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, SparseXPU, UNKNOWN_TENSOR_TYPE_ID, SparseVE, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, NestedTensorCUDA, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID].

CPU: registered at /Users/malfet/git/pytorch/vision/torchvision/csrc/ops/cpu/ps_roi_pool_kernel.cpp:263 [kernel]
MPS: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSDevice.mm:45 [backend fallback]
BackendSelect: fallthrough registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:133 [backend fallback]
Named: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/ConjugateFallback.cpp:18 [backend fallback]
Negative: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/NegateFallback.cpp:18 [backend fallback]
ZeroTensor: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:64 [backend fallback]
AutogradOther: registered at /Users/malfet/git/pytorch/vision/torchvision/csrc/ops/autograd/ps_roi_pool_kernel.cpp:142 [autograd kernel]
AutogradCPU: registered at /Users/malfet/git/pytorch/vision/torchvision/csrc/ops/autograd/ps_roi_pool_kernel.cpp:142 [autograd kernel]
AutogradCUDA: registered at /Users/malfet/git/pytorch/vision/torchvision/csrc/ops/autograd/ps_roi_pool_kernel.cpp:142 [autograd kernel]
UNKNOWN_TENSOR_TYPE_ID: registered at /Users/malfet/git/pytorch/vision/torchvision/csrc/ops/autograd/ps_roi_pool_kernel.cpp:142 [autograd kernel]
AutogradXLA: registered at /Users/malfet/git/pytorch/vision/torchvision/csrc/ops/autograd/ps_roi_pool_kernel.cpp:142 [autograd kernel]
AutogradMPS: registered at /Users/malfet/git/pytorch/vision/torchvision/csrc/ops/autograd/ps_roi_pool_kernel.cpp:142 [autograd kernel]
AutogradIPU: registered at /Users/malfet/git/pytorch/vision/torchvision/csrc/ops/autograd/ps_roi_pool_kernel.cpp:142 [autograd kernel]
AutogradXPU: registered at /Users/malfet/git/pytorch/vision/torchvision/csrc/ops/autograd/ps_roi_pool_kernel.cpp:142 [autograd kernel]
AutogradHPU: registered at /Users/malfet/git/pytorch/vision/torchvision/csrc/ops/autograd/ps_roi_pool_kernel.cpp:142 [autograd kernel]
UNKNOWN_TENSOR_TYPE_ID: registered at /Users/malfet/git/pytorch/vision/torchvision/csrc/ops/autograd/ps_roi_pool_kernel.cpp:142 [autograd kernel]
AutogradLazy: registered at /Users/malfet/git/pytorch/vision/torchvision/csrc/ops/autograd/ps_roi_pool_kernel.cpp:142 [autograd kernel]
AutogradPrivateUse1: registered at /Users/malfet/git/pytorch/vision/torchvision/csrc/ops/autograd/ps_roi_pool_kernel.cpp:142 [autograd kernel]
AutogradPrivateUse2: registered at /Users/malfet/git/pytorch/vision/torchvision/csrc/ops/autograd/ps_roi_pool_kernel.cpp:142 [autograd kernel]
AutogradPrivateUse3: registered at /Users/malfet/git/pytorch/vision/torchvision/csrc/ops/autograd/ps_roi_pool_kernel.cpp:142 [autograd kernel]
Tracer: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/TraceTypeManual.cpp:295 [backend fallback]
AutocastCPU: fallthrough registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/autocast_mode.cpp:481 [backend fallback]
Autocast: fallthrough registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/autocast_mode.cpp:324 [backend fallback]
Batched: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/BatchingRegistrations.cpp:1064 [backend fallback]
VmapMode: fallthrough registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
Functionalize: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/FunctionalizeFallbackKernel.cpp:89 [backend fallback]
PythonTLSSnapshot: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:137 [backend fallback]
```

**Comment by vfdev-5** [comment]
@malfet seems like a month after clang 13.0.1 release they did 14.X (https://releases.llvm.org/), maybe it worth go to 14.X hoping that it could be less buggy ?

**Comment by malfet** [comment]
Updated all our runners to Xcode_13.4 CLI tools by using following script:
```sh
hdiutil attach Command_Line_Tools_for_Xcode_13.4.dmg
pkgutil --verbose --expand-full /Volumes/Command\ Line\ Developer\ Tools/Command\ Line\ Tools.pkg tmp    
sudo mv  /Library/Developer/CommandLineTools  /Library/Developer/CommandLineTools-13.0.0
sudo mv tmp/CLTools_Executables.pkg/Payload/Library/Developer/CommandLineTools /Library/Developer/
sudo mv tmp/CLTools_macOSNMOS_SDK.pkg/Payload/Library/Developer/CommandLineTools/SDKs /Library/Developer/CommandLineTools
rm -rf tmp
hdiutil detach /Volumes/Command\ Line\ Developer\ Tools

```
