### ISSUE TITLE
Prototype tests broken

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#6143]
https://github.com/pytorch/vision/runs/6808601561?check_suite_focus=true

```
 Traceback (most recent call last):
  File "/home/runner/work/vision/vision/test/test_prototype_builtin_datasets.py", line 135, in test_data_loader
    next(iter(dl))
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 437, in __iter__
    return self._get_iterator()
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 380, in _get_iterator
    return _SingleProcessDataLoaderIter(self)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 678, in __init__
    self._dataset_kind, self._dataset, self._auto_collation, self._collate_fn, self._drop_last)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 76, in create_fetcher
    return _utils.fetch._IterableDatasetFetcher(dataset, auto_collation, collate_fn, drop_last)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 21, in __init__
    self.dataset_iter = iter(dataset)
TypeError: 'NoneType' object is not iterable
```

We'll just have to wait for https://github.com/pytorch/pytorch/pull/79124 to be in the nightlies

**Comment by NicolasHug** [comment]
[Fixed](https://giphy.com/gifs/tipsyelves-rainbow-magic-3o84U6421OOWegpQhq/fullscreen)!
