### ISSUE TITLE
build from source error

### ISSUE THREAD

**Issue by TD-GC** [pytorch/vision#6157]
### 🐛 Describe the bug

background:
I want to use the new function, which need to build torchvison from source.
"""
import torchvision
reader = torchvision.io.VideoReader(file_name, device='cuda:0')
for frame in reader:
    print(frame)
"""

information about my computer:
“”“
System: Ubuntu 18.04
Cuda: 10.2 (I also try 11.1)
GPU: RTX3090
”“”

when I run the operation：
python setup.py install

I meet a build problem:
"""
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1865, in _run_ninja_build
    subprocess.run(
  File "/civi/anaconda3/envs/torch/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/civi/Torchvision_Decoding_Note/vision/setup.py", line 514, in <module>
    setup(
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/_distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 778, in build_extensions
    build_ext.build_extensions(self)
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 593, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1544, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/civi/anaconda3/envs/torch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1881, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
“”“”

My ninja version：1.11.0
My cuda version：10.2 （I also try 11.1, but failed too）

My installation process：
①conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch-nightly
②conda install -c conda-forge ffmpeg
③git clone https://github.com/pytorch/vision.git
④cd vision
⑤python setup.py install
Then I met the above build problem
How can  I solve this problem?

### Versions

The latest ( until 2022 06 13)

**Comment by oke-aditya** [comment]
Hi @TD-GC 

Since you ran 
```
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch-nightly
```

You should already have torchvision installed. 

If you are trying to install from source, plz remove  torchvision from above. and then clone and try.
i.e do

```
conda install pytorch torchaudio cudatoolkit=10.2 -c pytorch-nightly
```

then for ffmpeg. 

```
conda install -c conda-forge ffmpeg
```

Then build from source.
```
git clone https://github.com/pytorch/vision.git
cd vision
python setup.py instal
```

**Comment by TD-GC** [comment]
@oke-aditya Thank you for your suggestion
I reinstalled as you suggested, but the problem still exists.

**Comment by TD-GC** [comment]
@oke-aditya Thank you for your suggestion
In a brand new conda environment, I reinstalled, but the above compilation problem still exists.
I ran the collect_env.py program and the output is as follows:
”“”
(torch) root@255eadfc66b7:/civi/Torchvision_Decoding_Note/pytorch/torch/utils# python collect_env.py
Collecting environment information...
PyTorch version: 1.13.0.dev20220612
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.14.0
Libc version: glibc-2.27

Python version: 3.9.12 (main, Jun  1 2022, 11:38:51)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.0.0-23-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: GeForce RTX 3090
GPU 1: GeForce RTX 3090
GPU 2: GeForce RTX 3090

Nvidia driver version: 455.23.04
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.4
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.2.0
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.0
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.0
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.0
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.0
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.0
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.13.0.dev20220612
[pip3] torchaudio==0.13.0.dev20220612
[conda] blas                      1.0                         mkl    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] cudatoolkit               10.2.89              hfd86e86_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl                       2021.4.0           h06a4308_640    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl-service               2.4.0            py39h7f8727e_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_fft                   1.3.1            py39hd3c417c_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_random                1.2.2            py39h51133e4_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] numpy                     1.22.3           py39he7a7128_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] numpy-base                1.22.3           py39hf524024_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] pytorch                   1.13.0.dev20220612 py3.9_cuda10.2_cudnn7.6.5_0    pytorch-nightly
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] torchaudio                0.13.0.dev20220612      py39_cu102    pytorch-nightly
“”“

**Comment by TD-GC** [comment]
I figured out a solution, upgrade cuda to 11.3, then install the latest version of pytorch (cudatoolkit=11.3), and then compile torchvision. This method can avoid the above error, but also conflict between torchvison and torch. Since my cuda driver version is 11.1, to install cuda11.3 means I have to uninstall the old dirver version and install a new one that match cuda11.3.
