### ISSUE TITLE
CI broken due to FX issue

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#6166]
Our unittest jobs [started failing](https://app.circleci.com/pipelines/github/pytorch/vision/18338/workflows/d017b4cb-39c8-45bd-8a82-758219affff7/jobs/1483664) with the latest nightly from core (from the 14th)  with 

```
Traceback (most recent call last):
  File "/root/project/test/test_backbone_utils.py", line 142, in test_build_fx_feature_extractor
    train_return_nodes, eval_return_nodes = self._get_return_nodes(model)
  File "/root/project/test/test_backbone_utils.py", line 130, in _get_return_nodes
    model, tracer_kwargs={"leaf_modules": self.leaf_modules}, suppress_diff_warning=True
  File "/root/project/torchvision/models/feature_extraction.py", line 253, in get_graph_node_names
    train_tracer.trace(model.train())
  File "/root/project/env/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 587, in trace
    self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
  File "/root/project/torchvision/models/swin_transformer.py", line 394, in forward
    x = self.features(x)
  File "/root/project/env/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 577, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "/root/project/torchvision/models/feature_extraction.py", line 84, in call_module
    out = forward(*args, **kwargs)
  File "/root/project/env/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 573, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "/root/project/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1131, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/project/env/lib/python3.7/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/root/project/env/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 577, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "/root/project/torchvision/models/feature_extraction.py", line 84, in call_module
    out = forward(*args, **kwargs)
  File "/root/project/env/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 573, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "/root/project/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1131, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/project/torchvision/models/swin_transformer.py", line 49, in forward
    x = F.pad(x, (0, 0, 0, W % 2, 0, H % 2))
TypeError: pad(): argument 'pad' (position 2) must be tuple of ints, not tuple
```

I'm unable to pin-point a specific PR in torch core though. Perhaps this is something  @jamesr66a  could help with? Thanks!

**Comment by datumbox** [comment]
Adding some details that @vfdev-5 found on his investigation:
```python
def foo(x) -> int:
    h = x.shape[0]
    y = int(h)
    return y

torch.fx.symbolic_trace(foo)(torch.rand(1, 2, 3))
```

Output:
```
Input In [50], in foo(x)
      1 def foo(x) -> int:
      2     h = x.shape[0]
----> 3     y = int(h)
      4     return y

TypeError: int() argument must be a string, a bytes-like object or a number, not 'Proxy'
```

**Comment by YosuaMichael** [comment]
@datumbox I think that problem is not related to the broken CI. 
My laptop use: `torch==1.13.0.dev20220531` and when I do both `pytest test_backbone_utils.py -k swin_t` and `pytest test_models.py -k swin_t` both passes the test. However I still get the same error `TypeError: int() argument must be a string, a bytes-like object or a number, not 'Proxy'` when I run the script.

**Comment by YosuaMichael** [comment]
I can't really point out which pytorch core PR that cause this problem, however I think this issue can be fixed by wrapping around the padding function with `torch.fx.wrap`. Here is a simple example to trigger the error (must use the latest nightly):
```
import torch
import torch.fx
import torch.nn.functional as F

class CustomModule(torch.nn.Module):
    def forward(self, x):
        bs, c, h, w = x.shape
        return F.pad(x, (0, w%2, 0, h%2, 0, 0))

m = CustomModule()
x = torch.rand(1, 3, 4, 4)
m_fx = torch.fx.symbolic_trace(m)
```

and here is the quick fix (although it feels hacky...)

```
import torch
import torch.fx
import torch.nn.functional as F

fx_wrapped_pad = F.pad
torch.fx.wrap("fx_wrapped_pad")

class CustomModule(torch.nn.Module):
    def forward(self, x):
        bs, c, h, w = x.shape
        return fx_wrapped_pad(x, (0, w%2, 0, h%2, 0, 0))

m = CustomModule()
x = torch.rand(1, 3, 4, 4)
m_fx = torch.fx.symbolic_trace(m)
```

**Comment by YosuaMichael** [comment]
@datumbox yeah, actually after trying to fix on the model file itself, it kinda harder to fix (the simple fix doesn't work).
Lets wait if anyone from the core team can help us on this.

**Comment by datumbox** [comment]
Given that there were no recent updates on the FX area, the problem can be on the dispatcher or modifications affecting `nn.functional.pad` which is called in this case. 

@vfdev-5 Could you please help us with a bisection to find the suspicious commit?

**Comment by vfdev-5** [comment]
Doing git bisect, it tells me that:
```
d332724071704939e1c50704f6bc62bb6c990383 is the first bad commit
commit d332724071704939e1c50704f6bc62bb6c990383
Author: Nikolay Korovaiko <korovaikon@gmail.com>
Date:   Tue Jun 14 02:17:59 2022 +0000

    Python Bindings for SymInts (#78135)
    
    This PR adds support for `SymInt`s in python. Namely,
    * `THPVariable_size` now returns `sym_sizes()`
    * python arg parser is modified to parse PyObjects into ints and `SymbolicIntNode`s
    * pybind11 bindings for `SymbolicIntNode` are added, so size expressions can be traced
    * a large number of tests added to demonstrate how to implement python symints.
    Pull Request resolved: https://github.com/pytorch/pytorch/pull/78135
    Approved by: https://github.com/ezyang
```

This commit breaks the snippet from @YosuaMichael , https://github.com/pytorch/vision/issues/6166#issuecomment-1155511441

**Comment by ezyang** [comment]
How much do you trust this repro test to capture all the breakage

**Comment by datumbox** [comment]
@ezyang it's a very new test in a very new model. So perhaps if you want to add a smoke test on your side, you can take the Yosua's snippet above. It's an issue that we haven't seen before so it's hard to tell how many other issues it can capture.

**Comment by vfdev-5** [comment]
If we replace in the [model defintion](https://github.com/pytorch/vision/blob/d1b2f4a18e0cae06b0a2288763c67b8371e65d9e/torchvision/models/swin_transformer.py#L49) offending place `x = F.pad(x, (0, 0, 0, W % 2, 0, H % 2))` with pure integers : `x = F.pad(x, (0, 0, 0, 0, 0, 0))`, FX related tests are now passing with nightly pytorch:
```
test/test_backbone_utils.py::TestFxFeatureExtraction::test_build_fx_feature_extractor[swin_t] PASSED                                                                       [ 12%]
test/test_backbone_utils.py::TestFxFeatureExtraction::test_forward_backward[swin_t] PASSED                                                                                 [ 25%]
test/test_backbone_utils.py::TestFxFeatureExtraction::test_jit_forward_backward[swin_t] PASSED   
```
So, I think this is the only place that breaks the CI
