### ISSUE TITLE
CI jobs `binary_linux_wheel_*_cu117` broken due to libcublas.so.11 dependency

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#6628]
### 🐛 Describe the bug

Multiple CI jobs of TorchVision are currently [failing](https://app.circleci.com/pipelines/github/pytorch/vision/20449/workflows/e62f0f9c-8ffb-48f0-bdd5-84d2881bb4a4/jobs/1663603) with:
```
+ python setup.py clean
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    import torch
  File "/opt/python/cp37-cp37m/lib/python3.7/site-packages/torch/__init__.py", line 191, in <module>
    _load_global_deps()
  File "/opt/python/cp37-cp37m/lib/python3.7/site-packages/torch/__init__.py", line 153, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/opt/python/cp37-cp37m/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcublas.so.11: cannot open shared object file: No such file or directory
```

The issue seems to be mainly with CUDA 11.7

### Versions

Latest torchvision main, PyTorch Core `20220922`

cc @seemethere

**Comment by syed-ahmed** [comment]
@atalman I believe this is now fixed.

**Comment by malfet** [comment]
Indeed fixed by https://github.com/pytorch/pytorch/commit/e227e3ec4897d2ce04de705423afefa028d82b34, closing
