### ISSUE TITLE
OSError: libcublas.so.11: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#7032]
### 🐛 Describe the bug

Multiple `cmake_*` CI and `unittest_linux_gpu_py3.8` jobs [fail](https://app.circleci.com/pipelines/github/pytorch/vision/22318/workflows/f36c513d-8e2b-484e-92bf-efc35fb5f78a/jobs/1797491) with:
```
OSError: libcublas.so.11: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/circleci/project/env/lib/python3.8/site-packages/torch/__init__.py", line 218, in <module>
    _load_global_deps()
  File "/home/circleci/project/env/lib/python3.8/site-packages/torch/__init__.py", line 179, in _load_global_deps
    _preload_cuda_deps()
  File "/home/circleci/project/env/lib/python3.8/site-packages/torch/__init__.py", line 159, in _preload_cuda_deps
    ctypes.CDLL(cublas_path)
UnboundLocalError: local variable 'cublas_path' referenced before assignment
```

### Versions

Latest main

cc @seemethere

**Comment by atalman** [comment]
This should be resolved now in all environments
