### ISSUE TITLE
QAT MobileNetV3 classification reference not working

### ISSUE THREAD

**Issue by MathijsNL** [pytorch/vision#7064]
### 🐛 Describe the bug

Hi there,

Using pytorch vision v0.14.1 I get the following error when running train_quantization from the classification examples:

Comman:
```
 torchrun   --nproc_per_node=1 train_quantization.py --model='mobilenet_v3_large'     --wd 0.00001 --lr 0.001 --data-path data --workers 1 --batch-size 4 --eval-batch-size 4
```

Output:
```
torchrun   --nproc_per_node=1 train_quantization.py --model='mobilenet_v3_large'     --wd 0.00001 --lr 0.001 --data-path data --workers 1 --batch-size 4 --eval-batch-size 4
| distributed init (rank 0): env://
Namespace(data_path='data', model='mobilenet_v3_large', backend='qnnpack', device='cuda', batch_size=4, eval_batch_size=4, epochs=90, num_observer_update_epochs=4, num_batch_norm_update_epochs=3, num_calibration_batches=32, workers=1, lr=0.001, momentum=0.9, weight_decay=1e-05, lr_step_size=30, lr_gamma=0.1, print_freq=10, output_dir='.', resume='', start_epoch=0, cache_dataset=False, sync_bn=False, test_only=False, post_training_quantize=False, world_size=1, dist_url='env://', interpolation='bilinear', val_resize_size=256, val_crop_size=224, train_crop_size=224, clip_grad_norm=None, weights=None, rank=0, gpu=0, distributed=True, dist_backend='nccl')
Loading data
Loading data
Loading training data
Traceback (most recent call last):
  File "/home/jovyan/work/flowervision_pytorch/vision/references/classification/train_quantization.py", line 265, in <module>
    main(args)
  File "/home/jovyan/work/flowervision_pytorch/vision/references/classification/train_quantization.py", line 38, in main
    dataset, dataset_test, train_sampler, test_sampler = load_data(train_dir, val_dir, args)
  File "/home/jovyan/work/flowervision_pytorch/vision/references/classification/train.py", line 133, in load_data
    ra_magnitude = args.ra_magnitude
AttributeError: 'Namespace' object has no attribute 'ra_magnitude'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 7654) of binary: /opt/conda/bin/python3.10
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_quantization.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-01-06_12:51:31
  host      : e368b230e587
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 7654)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

```

The train.py script which get used in the imports of train_quantization.py has the default argument values, but it still throws this error. This is also reproducable with the default command mentioned for QAT MobileNetV3

```
torchrun --nproc_per_node=8 train_quantization.py --model='mobilenet_v3_large' \
    --wd 0.00001 --lr 0.001
```

### Versions

```
Collecting environment information...
PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:36:39) [GCC 10.4.0] (64-bit runtime)
Python platform: Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1080
Nvidia driver version: 527.56
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==1.13.1+cu117
[pip3] torchaudio==0.13.1+cu117
[pip3] torchvision==0.14.1+cu117
[conda] nomkl                     1.0                  h5ca1d4c_0    conda-forge
[conda] numpy                     1.23.5          py310h53a5b5f_0    conda-forge
[conda] torch                     1.13.1+cu117             pypi_0    pypi
[conda] torchaudio                0.13.1+cu117             pypi_0    pypi
[conda] torchvision               0.14.1+cu117             pypi_0    pypi
```

**Comment by NicolasHug** [comment]
Thanks for the report @MathijsNL , I opened https://github.com/pytorch/vision/pull/7072 to fix this issue
