### ISSUE TITLE
error occurs when installing torchvision0.12.0 on jetson xazier nx

### ISSUE THREAD

**Issue by Patrick24080735** [pytorch/vision#7491]
### 🐛 Describe the bug

hi, I want to constructe an environment for pytorch and I have installed torch1.11 successfully on jetson xazier nx , but error occors when installing torchvision. First, I used command 'git clone --branch v0.12.0 https://github.com/pytorch/vision torchvision' to download torchvision. Then, I used 'python setup.py install' for installation. Here is the error：
(torch) nx@ubuntu:~/Downloads/torch11.1-torchvision0.12/torchvision$ python setup.py install --user
Building wheel torchvision-0.12.0
Traceback (most recent call last):
  File "setup.py", line 532, in <module>
    ext_modules=get_extensions(),
  File "setup.py", line 262, in get_extensions
    libpng = distutils.spawn.find_executable("libpng-config")
AttributeError: module 'distutils' has no attribute 'spawn'
I'm sincerely looking forward to your reply.

### Versions

(torch) nx@ubuntu:~/Downloads/torch11.1-torchvision0.12/torchvision$ python setup.py install --user
Building wheel torchvision-0.12.0
Traceback (most recent call last):
  File "setup.py", line 532, in <module>
    ext_modules=get_extensions(),
  File "setup.py", line 262, in get_extensions
    libpng = distutils.spawn.find_executable("libpng-config")
AttributeError: module 'distutils' has no attribute 'spawn'
I'm sincerely looking forward to your reply.

**Comment by pmeier** [comment]
What Python version are you using?

**Comment by Patrick24080735** [comment]
python3.8.10🙏🙏



---- Replied Message ----
| From | Philip ***@***.***> |
| Date | 04/04/2023 14:49 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [pytorch/vision] error occurs when installing torchvision0.12.0 on jetson xazier nx (Issue #7491) |

What Python version are you using?

**Comment by Patrick24080735** [comment]
> 

PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (aarch64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.3
Libc version: glibc-2.31

Python version: 3.8.10 | packaged by conda-forge | (default, Sep 13 2021, 22:42:03)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.10.104-tegra-aarch64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.4.239
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/aarch64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/aarch64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/aarch64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/aarch64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/aarch64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torch==1.11.0
[conda] torch                     1.11.0                   pypi_0    pypi

**Comment by pmeier** [comment]
I'd wager a guess and say this is an environment issue: Python 3.8 has a [`distutils.spawn`](https://github.com/python/cpython/blob/3.8/Lib/distutils/spawn.py) module and we are correctly importing it

https://github.com/pytorch/vision/blob/9b5a3fecc72434dbd65148723efe54b28b9728c9/setup.py#L2

Trying this in a clean conda environment also works for me

```
$ conda create -n tv-7491 -c conda-forge python=3.8
$ conda activate tv-7491
$ python -c 'import distutils.spawn; print(distutils.spawn.find_executable("libpng-config"))'
/usr/bin/libpng-config
```

Can you run the `python -c` command from above and see if that fails? If so, could you create a clean env and try again?

**Comment by Patrick24080735** [comment]
> I'd wager a guess and say this is an environment issue: Python 3.8 has a [`distutils.spawn`](https://github.com/python/cpython/blob/3.8/Lib/distutils/spawn.py) module and we are correctly importing it
> 
> https://github.com/pytorch/vision/blob/9b5a3fecc72434dbd65148723efe54b28b9728c9/setup.py#L2
> 
> Trying this in a clean conda environment also works for me
> 
> ```
> $ conda create -n tv-7491 -c conda-forge python=3.8
> $ conda activate tv-7491
> $ python -c 'import distutils.spawn; print(distutils.spawn.find_executable("libpng-config"))'
> /usr/bin/libpng-config
> ```
> 
> Can you run the `python -c` command from above and see if that fails? If so, could you create a clean env and try again?

Still the same error and below is the specific information.
(tv-7491) nx@ubuntu:~/Downloads/torch11.1-torchvision0.12/torchvision$ python -c 'import distutils.spawn; print(distutils.spawn.find_executable("libpng-config"))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'distutils' has no attribute 'spawn'

**Comment by pmeier** [comment]
Since we can reproduce the error without `torchvision`, I'm going to close this as it is not actionable for us. If I were you, I would try to find out what is up with your Python. It is super weird that import passes, but the attribute access fails right after. Maybe aarch64 was not properly supported on the 3.8 conda-forge package? Maybe try to upgrade to a higher one? Support for 3.9 and 3.10 is available for `torchvision==0.12.0`.

**Comment by Patrick24080735** [comment]
> Since we can reproduce the error without `torchvision`, I'm going to close this as it is not actionable for us. If I were you, I would try to find out what is up with your Python. It is super weird that import passes, but the attribute access fails right after. Maybe aarch64 was not properly supported on the 3.8 conda-forge package? Maybe try to upgrade to a higher one? Support for 3.9 and 3.10 is available for `torchvision==0.12.0`.

In fact, this is the third time to construct pytorch for deep learning. Things went successfully when installing torch and torchvision with python3.8 at the second time, then I met some symbolic link error and couldn't figure it out, so I reinstalled the miniforge. However, unfortunately, I met some new error in the third time installation and it really drives me crazy. Alright, I will figure out another way to solve the problem. Thanks and respect from a senior student in China~
