### ISSUE TITLE
Linux GPU tests are failing

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#7515]
- https://github.com/pytorch/vision/actions/runs/4686659677/jobs/8304998350
- https://github.com/pytorch/vision/actions/runs/4687127212/jobs/8306422795

Error message is interleaved with the regular output:

```
  Collecting torch
    Downloading https://download.pytorch.org/whl/nightly/cu117/torch-2.1.0.dev20230412%2Bcu117-cp38-cp38-linux_x86_64.whl (1833.2 MB)
  Collecting typing-extensions
    Downloading https://download.pytorch.org/whl/nightly/typing_extensions-4.4.0-py3-none-any.whl (26 kB)
  Collecting filelock
    Downloading https://download.pytorch.org/whl/nightly/filelock-3.9.0-py3-none-any.whl (9.7 kB)
  Traceback (most recent call last):
    File "/home/ec2-user/actions-runner/_work/vision/vision/test-infra/.github/scripts/run_docker_with_env_secrets.py", line 81, in <module>
  Collecting sympy
      main()
    File "/home/ec2-user/actions-runner/_work/vision/vision/test-infra/.github/scripts/run_docker_with_env_secrets.py", line 77, in main
    Downloading https://download.pytorch.org/whl/nightly/sympy-1.11.1-py3-none-any.whl (6.5 MB)
  Collecting pytorch-triton==2.1.0+46672772b4
    Downloading https://download.pytorch.org/whl/nightly/pytorch_triton-2.1.0%2B46672772b4-cp38-cp38-linux_x86_64.whl (87.2 MB)
  Collecting networkx
    Downloading https://download.pytorch.org/whl/nightly/networkx-2.6.3-py3-none-any.whl (1.9 MB)
  Collecting jinja2
    Downloading https://download.pytorch.org/whl/nightly/Jinja2-3.1.2-py3-none-any.whl (133 kB)
  Collecting MarkupSafe>=2.0
      run_cmd_or_die(f'docker exec -t {container_name} /exec')
    File "/home/ec2-user/actions-runner/_work/vision/vision/test-infra/.github/scripts/run_docker_with_env_secrets.py", line 29, in run_cmd_or_die
      raise RuntimeError(f'Command {cmd} failed with exit code {exit_code}')
  RuntimeError: Command docker exec -t cf027b021c5ddb846716095d635c6e6a3c58aa4534edb02a808be021d06d5089 /exec failed with exit code 1
    Downloading https://download.pytorch.org/whl/nightly/MarkupSafe-2.1.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
  Collecting mpmath>=0.19
    Downloading https://download.pytorch.org/whl/nightly/mpmath-1.2.1-py3-none-any.whl (532 kB)
  Installing collected packages: mpmath, typing-extensions, sympy, networkx, MarkupSafe, filelock, pytorch-triton, jinja2, torch
  Successfully installed MarkupSafe-2.1.2 filelock-3.9.0 jinja2-3.1.2 mpmath-1.2.1 networkx-2.6.3 pytorch-triton-2.1.0+46672772b4 sympy-1.11.1 torch-2.1.0.dev20230412+cu117 typing-extensions-4.4.0
```

Extracting the important parts

```
Traceback (most recent call last):
    File "/home/ec2-user/actions-runner/_work/vision/vision/test-infra/.github/scripts/run_docker_with_env_secrets.py", line 81, in <module>
      main()
    File "/home/ec2-user/actions-runner/_work/vision/vision/test-infra/.github/scripts/run_docker_with_env_secrets.py", line 77, in main
      run_cmd_or_die(f'docker exec -t {container_name} /exec')
    File "/home/ec2-user/actions-runner/_work/vision/vision/test-infra/.github/scripts/run_docker_with_env_secrets.py", line 29, in run_cmd_or_die
      raise RuntimeError(f'Command {cmd} failed with exit code {exit_code}')
  RuntimeError: Command docker exec -t cf027b021c5ddb846716095d635c6e6a3c58aa4534edb02a808be021d06d5089 /exec failed with exit code 1
```

Since this traceback print starts while we are still installing stuff and the installation finishes without issues, I guess this is not on us, but rather on the runner?

In both cases we are using

https://github.com/pytorch/vision/blob/29757104250dd088386fef1ec3d70ed0b0c1be8a/.github/workflows/test-linux.yml#L25

cc @seemethere

**Comment by weiwangmeta** [comment]
According to @atalman , PR#3956 started to cause Audio failures (on audio side this workflow passes: https://github.com/pytorch/audio/actions/runs/4678030776/jobs/8286260647, The next one that is using run_docker_with_env_secrets.py is failing).

**Comment by weiwangmeta** [comment]
Should now be fixed after Eli's fix https://github.com/pytorch/test-infra/pull/4045.  
cc @seemethere

**Comment by weiwangmeta** [comment]
https://github.com/pytorch/vision/actions/runs/4686659677 re-run of https://github.com/pytorch/vision/actions/runs/4686659677/jobs/8304998350 is green. Closing this issue. Please re-open otherwise.
