### ISSUE TITLE
container.streams.audio[0].format.name is empty

### ISSUE THREAD

**Issue by metal3d** [pytorch/vision#7534]
Hi,
There is a problem here.
https://github.com/pytorch/vision/blob/2925df7cdf349f51dbda463d59569067e8a87c43/torchvision/io/video.py#L115

The list is empty when I do:

```python
video, audio, info = read_video(...)

# convert some frames from video, then...
#

# convert frames to video with the audio
frames = np.stack(frames)
frames = torch.from_numpy(frames)
frames = frames.byte()
write_video(
    args.output_file,
    frames,
    info["video_fps"],
    video_codec="libx264",
    audio_array=audio,
    audio_fps=info["audio_fps"],
    audio_codec="mp3",
)
```

Removing the audio makes the video working (but no audio, of course).

I tried to put a breakpoint:

```
(Pdb) pp container.streams.audio
()
(Pdb) c
Traceback (most recent call last):
  File "/home/metal3d/Projects/ML/vidgan/main.py", line 74, in <module>
    write_video(
  File "/home/metal3d/.local/share/virtualenvs/vidgan-Eu9s-CW_/lib64/python3.10/site-packages/torchvision/io/video.py", line 118, in write_video
    audio_sample_fmt = container.streams.audio[0].format.name
IndexError: tuple index out of range
```

**Comment by metal3d** [comment]
OK, duplicated #6814 it seems
