### ISSUE TITLE
Dynamic ONNX export of convnext models with circular padding fails

### ISSUE THREAD

**Issue by ORippler** [pytorch/vision#7541]
### 🐛 Describe the bug

When trying to export a convnext with circular paddings, export will fail for dynamic shapes. The following MWE
```python
import torch
import torchvision
from torchvision.models.feature_extraction import (
    create_feature_extractor,
)

# circular padding works for exporting a single conv to onnx.
model = torch.nn.Conv2d(3, 6, 3, 2)
model.padding_mode = "circular"
torch.onnx.export(
    model,
    torch.zeros((1, 3, 384, 384)),
    "./model.onnx",
    input_names=["input"],
    dynamic_axes={"input": [0, 2, 3]},
)

# however, for complex models it will fail.
model = torchvision.models.convnext_small()
for module in model.modules():
    if isinstance(module, torch.nn.Conv2d):
        module.padding_mode = "circular"
model = create_feature_extractor(model, {"features.3": "output"})
torch.onnx.export(
    model,
    torch.zeros((1, 3, 384, 384)),
    "./model.onnx",
    input_names=["input"],
    output_names=["output"],
    dynamic_axes={"input": [0, 2, 3]},
)
```
errors with
```
Traceback (most recent call last):
  File "/workspaces/ml-docker-dev/sensei/mwe.py", line 25, in <module>
    torch.onnx.export(
  File "/usr/local/lib/python3.10/site-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/usr/local/lib/python3.10/site-packages/torch/onnx/utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/usr/local/lib/python3.10/site-packages/torch/onnx/utils.py", line 1117, in _model_to_graph
    graph = _optimize_graph(
  File "/usr/local/lib/python3.10/site-packages/torch/onnx/utils.py", line 665, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/usr/local/lib/python3.10/site-packages/torch/onnx/utils.py", line 1891, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
  File "/usr/local/lib/python3.10/site-packages/torch/onnx/symbolic_opset11.py", line 864, in pad
    return opset9._pad_circular(g, input, pad)
  File "/usr/local/lib/python3.10/site-packages/torch/onnx/symbolic_opset9.py", line 1919, in _pad_circular
    left = symbolic_helper._slice_helper(
  File "/usr/local/lib/python3.10/site-packages/torch/onnx/symbolic_helper.py", line 729, in _slice_helper
    return _slice10(g, input, axes, starts, ends, steps, dynamic_slice)
  File "/usr/local/lib/python3.10/site-packages/torch/onnx/symbolic_opset10.py", line 352, in _slice
    if ends[0] > _constants.INT64_MAX:
TypeError: '>' not supported between instances of 'NoneType' and 'int' 
(Occurred when translating pad).
```

Some observations from my side:

1. Exporting the model with zero padding in static as well as dynamic mode works.
2. Exporting the model with circular padding in static mode works as well. However, if you try to resize the onnx model dynamically this will fail as soon as you are bigger than the input size with some margin (I presume the margin to get to the next valid conv).
3. Exporting just a single `torch.nn.Conv2d` model works with both static and dynamic mode as well as circular and zeros padding.

Note that I did not test this for other covnext versions, but expect those to also fail the export. I presume the above error is some edge-case for the workarounds that Pytorch does to achieve circular padding in onnx currently, which was so far not officially supported/did not have an official op, see this related issue. https://github.com/pytorch/pytorch/issues/95229

### Versions

```
Versions of relevant libraries:
[pip3] mypy==1.2.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.4
[pip3] pytorch-lightning==1.9.5
[pip3] torch==2.0.0
[pip3] torchmetrics==0.10.3
[pip3] torchvision==0.15.1
[pip3] triton==2.0.0
[conda] Could not collect
```

Since onnx export is involved:
```
onnx==1.13.1
```

**Comment by NicolasHug** [comment]
Thanks for the report @ORippler 

I suspect the issue might have to do with your env, because I cannot reproduce the error on my side. I'm getting the following output:

```
/home/nicolashug/.miniconda3/envs/pt/lib/python3.9/site-packages/torch/onnx/utils.py:2049: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input input
  warnings.warn(
========== Diagnostic Run torch.onnx.export version 2.1.0.dev20230411 ==========
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

========== Diagnostic Run torch.onnx.export version 2.1.0.dev20230411 ==========
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================
```


```
(pt) ➜  vision git:(main) ✗ ipython -c "from torch.utils import collect_env; collect_env.main()"
Collecting environment information...
PyTorch version: 2.1.0.dev20230411
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Fedora release 34 (Thirty Four) (x86_64)
GCC version: (GCC) 11.3.1 20220421 (Red Hat 11.3.1-2)
Clang version: 12.0.1 (Fedora 12.0.1-1.fc34)
CMake version: version 3.23.1
Libc version: glibc-2.33

Python version: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:59)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.17.12-100.fc34.x86_64-x86_64-with-glibc2.33
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           140
Model name:                      11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
Stepping:                        1
CPU MHz:                         2600.000
CPU max MHz:                     4400.0000
CPU min MHz:                     400.0000
BogoMIPS:                        5222.40
Virtualization:                  VT-x
L1d cache:                       192 KiB
L1i cache:                       128 KiB
L2 cache:                        5 MiB
L3 cache:                        8 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l2 invpcid_single cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves split_lock_detect dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid movdiri movdir64b fsrm avx512_vp2intersect md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] mypy==0.991
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.24.2
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==2.1.0.dev20230411
[pip3] torchvision==0.16.0a0+0d75d9e
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   2.0                           0    pytorch-nightly
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] pytorch                   2.1.0.dev20230411     py3.9_cpu_0    pytorch-nightly
[conda] pytorch-mutex             1.0                         cpu    pytorch-nightly
[conda] pytorch-sphinx-theme      0.0.24                    dev_0    <develop>
[conda] torchvision               0.14.0a0+1d7d92c          pypi_0    pypi

```

**Comment by ORippler** [comment]
Well with the nightly it passes for me as well, but it fails with the stable release.

**Comment by NicolasHug** [comment]
Ah got it, looks like it has been fixed since the last release then. We just released a bugfix release yesteraday (0.15.2), I haven't checked but if we're lucky, that release may contain the fix!
