### ISSUE TITLE
FlyingThings3D test is flaky on Windows

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#7626]
I've recently seen an error like below pop up a few times in [Windows CI](https://github.com/pytorch/vision/actions/runs/5070101996):

```
Traceback (most recent call last):
  File "C:\actions-runner\_work\vision\vision\pytorch\vision\test\datasets_utils.py", line 531, in test_feature_types
    with self.create_dataset(config) as (dataset, _):
  File "C:\Jenkins\Miniconda3\envs\ci\lib\contextlib.py", line 142, in __exit__
    next(self.gen)
  File "C:\actions-runner\_work\vision\vision\pytorch\vision\test\datasets_utils.py", line 617, in create_dataset
    with super().create_dataset(
  File "C:\Jenkins\Miniconda3\envs\ci\lib\contextlib.py", line 142, in __exit__
    next(self.gen)
  File "C:\actions-runner\_work\vision\vision\pytorch\vision\test\datasets_utils.py", line 371, in create_dataset
    with get_tmp_dir() as tmpdir:
  File "C:\Jenkins\Miniconda3\envs\ci\lib\contextlib.py", line 142, in __exit__
    next(self.gen)
  File "C:\actions-runner\_work\vision\vision\pytorch\vision\test\common_utils.py", line 47, in get_tmp_dir
    shutil.rmtree(tmp_dir)
  File "C:\Jenkins\Miniconda3\envs\ci\lib\shutil.py", line 750, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Jenkins\Miniconda3\envs\ci\lib\shutil.py", line 615, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Jenkins\Miniconda3\envs\ci\lib\shutil.py", line 615, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Jenkins\Miniconda3\envs\ci\lib\shutil.py", line 615, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 2 more times]
  File "C:\Jenkins\Miniconda3\envs\ci\lib\shutil.py", line 624, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Jenkins\Miniconda3\envs\ci\lib\shutil.py", line 622, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpruvdnq3j\\FlyingThings3D\\frames_cleanpass\\TRAIN\\B\\0001'
```

This can happen on Windows if we open a file, but not close it before the test ends. We have a patch for PIL images to always load them properly

https://github.com/pytorch/vision/blob/4125d3a02b15faf4b19767a91797320151ce8bc6/test/datasets_utils.py#L623-L643

Meaning, either that doesn't work or another file type is causing this.

**Comment by pmeier** [comment]
The folder the error points to only contains PNG images. Other than them, the dataset also contains pfm files for the flow, but they are opened with a context manager so that shouldn't be an issue:

https://github.com/pytorch/vision/blob/4125d3a02b15faf4b19767a91797320151ce8bc6/torchvision/datasets/utils.py#L485

**Comment by pmeier** [comment]
I can confirm that our patch is correctly hit during tests. We currently load images in the Optical flow datasets with

https://github.com/pytorch/vision/blob/4125d3a02b15faf4b19767a91797320151ce8bc6/torchvision/datasets/_optical_flow.py#L44-L48

Since `.convert("RGB")` is a [no-op in case the input is already in RGB](https://github.com/pytorch/vision/issues/7478#issuecomment-1491414301), but will always load the data, can we maybe use

```py
def _read_img(self, file_name: str) -> Image.Image: 
     return Image.open(file_name).convert("RGB") 
```

? That is similar to other datasets as well. cc @NicolasHug for thoughts or an idea what else could cause this.
