### ISSUE TITLE
Toasted CI due to attempt at installing numpy-1.25.0rc1 which requires 3.9

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#7638]
Most CI jobs are red due to an installation issue (https://github.com/pytorch/vision/pull/5009)

```
  Searching for numpy
  Reading https://pypi.org/simple/numpy/
  Downloading https://files.pythonhosted.org/packages/26/de/437a60a69f7fd0c79264530a97787b2ac7394616e3661236201518f8a47d/numpy-1.25.0rc1.tar.gz#sha256=224e8862a1cd357eede831b270b9e6c51d2cbc2bb5cc2e2b8d0c76d52cbd1edc
  Best match: numpy 1.25.0rc1
  Processing numpy-1.25.0rc1.tar.gz
  Writing /tmp/easy_install-387ykuae/numpy-1.25.0rc1/setup.cfg
  Running numpy-1.25.0rc1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-387ykuae/numpy-1.25.0rc1/egg-dist-tmp-9r05yq36
  Traceback (most recent call last):
    File "/opt/conda/envs/ci/lib/python3.8/site-packages/setuptools/sandbox.py", line 156, in save_modules
      yield saved
    File "/opt/conda/envs/ci/lib/python3.8/site-packages/setuptools/sandbox.py", line 198, in setup_context
      yield
    File "/opt/conda/envs/ci/lib/python3.8/site-packages/setuptools/sandbox.py", line 259, in run_setup
      _execfile(setup_script, ns)
    File "/opt/conda/envs/ci/lib/python3.8/site-packages/setuptools/sandbox.py", line 46, in _execfile
      exec(code, globals, locals)
    File "/tmp/easy_install-387ykuae/numpy-1.25.0rc1/setup.py", line 22, in <module>
      return get_distribution(pkgname)
  RuntimeError: Python version >= 3.9 required.
```

@pmeier do you mind taking a look? Not sure what's causing it but we should look into why it's trying to install a RC instead of a stable numpy version.

**Comment by pmeier** [comment]
This happens because the really outdated `easy_install` that we are still using internally, does not care about required Python versions. `numpy` released `1.25.0rc1` today, which no longer has a wheel for Python 3.8. However, it has a `.tar.gz` version so it tries to compile from source. But instead of discarding the tarball as soon as it realizes the Python version is not supported, it bails out.

In contrast, doing the same with `pip` in a clean Python 3.8 environment gives

```
❯ python -VV
[GCC 11.3.0]
Python 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:55) 
❯ pip install --pre numpy
Collecting numpy
  Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Installing collected packages: numpy
Successfully installed numpy-1.24.3
```

Without `--pre`, `pip` ignores the pre-releases completely.
