### ISSUE TITLE
`resize` with `antialias=True` doesn't work if the difference of spatial size is larget

### ISSUE THREAD

**Issue by duguyue100** [pytorch/vision#7671]
### 🐛 Describe the bug

Take the following example, I want to resize a tensor from `(941, 941)` to `(10, 10)` with `antialias=True`.

```python
import torch
from torchvision.transforms import InterpolationMode
from torchvision.transforms.functional import resize

test_tensor = torch.ones((1, 941, 941), dtype=torch.float, device="cuda")
resize(
    test_tensor,
    size=(10, 10),
    interpolation=InterpolationMode.BILINEAR,
    antialias=True,
)
```

This will break with the following error:
```
Traceback (most recent call last):
  File "/home/yuhuang/.cache/junkfile/2023/06/2023-06-14-144608.py", line 6, in <module>
    resize(
  File "/home/yuhuang/miniconda3/envs/new-torchvision-bug/lib/python3.10/site-packages/torchvision/transforms/functional.py", line 492, in resize
    return F_t.resize(img, size=output_size, interpolation=interpolation.value, antialias=antialias)
  File "/home/yuhuang/miniconda3/envs/new-torchvision-bug/lib/python3.10/site-packages/torchvision/transforms/_functional_tensor.py", line 467, in resize
    img = interpolate(img, size=size, mode=interpolation, align_corners=align_corners, antialias=antialias)
  File "/home/yuhuang/miniconda3/envs/new-torchvision-bug/lib/python3.10/site-packages/torch/nn/functional.py", line 3958, in interpolate
    return torch._C._nn._upsample_bilinear2d_aa(input, output_size, align_corners, scale_factors)
RuntimeError: Provided interpolation parameters can not be handled with current algorithm implementation. Please reduce the scale factor. Too much shared memory required: 49660 vs 49152
```

We also tried the following combination

```
(940, 940) -> (10, 10): works
(941, 941) -> (10, 11): breaks
(941, 941) -> (11, 10): breaks
(9401, 9401) -> (100, 100): breaks
(941, 941) -> (10, 10) with antialias=False: works
```

I use PyTorch 2.0 to demonstrate the bug, the same bug exists in Pytorch 1.13 as well.

94 seems like a magic number, I found this out by trying many combinations.

### Versions

```
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.11 (main, May 16 2023, 00:28:57) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.0-43-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 510.108.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          24
On-line CPU(s) list:             0-23
Vendor ID:                       GenuineIntel
Model name:                      12th Gen Intel(R) Core(TM) i9-12900K
CPU family:                      6
Model:                           151
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       1
Stepping:                        2
CPU max MHz:                     5200.0000
CPU min MHz:                     800.0000
BogoMIPS:                        6374.40
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l2 invpcid_single cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdt_a rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req hfi umip pku ospke waitpkg gfni vaes vpclmulqdq tme rdpid movdiri movdir64b fsrm md_clear serialize pconfig arch_lbr ibt flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       640 KiB (16 instances)
L1i cache:                       768 KiB (16 instances)
L2 cache:                        14 MiB (10 instances)
L3 cache:                        30 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-23
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-service               2.4.0           py310h5eee18b_1  
[conda] mkl_fft                   1.3.6           py310h1128e8f_1  
[conda] mkl_random                1.2.2           py310h1128e8f_1  
[conda] numpy                     1.24.3          py310h5f9d8c6_1  
[conda] numpy-base                1.24.3          py310hb5e798b_1  
[conda] pytorch                   2.0.1           py3.10_cuda11.7_cudnn8.5.0_0    pytorch
[conda] pytorch-cuda              11.7                 h778d358_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.0.2               py310_cu117    pytorch
[conda] torchtriton               2.0.0                     py310    pytorch
[conda] torchvision               0.15.2              py310_cu117    pytorch
```

**Comment by NicolasHug** [comment]
This is probably more of a torch core issue than a torchvision issue. @duguyue100 do you mind verifying that this also fails? In which case we'll transfer the issue to pytorch

```py

import torch
from torch.nn.functional import interpolate

test_tensor = torch.ones((1, 1, 941, 941), dtype=torch.float, device="cuda")
interpolate(test_tensor, size=[10, 10], mode="bilinear", antialias=True)
```

**Comment by NicolasHug** [comment]
Also for clarity, this is only an issue on cuda, right?

**Comment by duguyue100** [comment]
Thanks for the reminder, this problem is only on CUDA. I just tried CPU tensors, and it works.

**Comment by duguyue100** [comment]
> This is probably more of a torch core issue than a torchvision issue. @duguyue100 do you mind verifying that this also fails? In which case we'll transfer the issue to pytorch
> 
> ```python
> import torch
> from torch.nn.functional import interpolate
> 
> test_tensor = torch.ones((1, 1, 941, 941), dtype=torch.float, device="cuda")
> interpolate(test_tensor, size=[10, 10], mode="bilinear", antialias=True)
> ```

Just tried, this failed as well
