### ISSUE TITLE
[reference/detection/train.py] KeyError: 'keypoints'. Error when training KeypointRCNN

### ISSUE THREAD

**Issue by pvtien96** [pytorch/vision#7720]
### 🐛 Describe the bug

I'm training a KeypointRCNN model following the official instruction.
```bash
(base) tien@p3660:~/temp/vision/references/detection$ torchrun --nproc_per_node=1 train.py --data-path ~/data/coco/ --model keypointrcnn_resnet50_fpn --weights-backbone ResNet50_Weights.IMAGENET1K_V1 --epochs 46 --lr-steps 36 43 --aspect-ratio-group-factor 3
```
Here's the output log:
```bash
| distributed init (rank 0): env://
Namespace(data_path='/home/tien/data/coco/', dataset='coco', model='keypointrcnn_resnet50_fpn', device='cuda', batch_size=2, epochs=46, workers=4, opt='sgd', lr=0.02, momentum=0.9, weight_decay=0.0001, norm_weight_decay=None, lr_scheduler='multisteplr', lr_step_size=8, lr_steps=[36, 43], lr_gamma=0.1, print_freq=20, output_dir='.', resume='', start_epoch=0, aspect_ratio_group_factor=3, rpn_score_thresh=None, trainable_backbone_layers=None, data_augmentation='hflip', sync_bn=False, test_only=False, use_deterministic_algorithms=False, world_size=1, dist_url='env://', weights=None, weights_backbone='ResNet50_Weights.IMAGENET1K_V1', amp=False, use_copypaste=False, rank=0, gpu=0, distributed=True, dist_backend='nccl')
Loading data
Loading annotations into memory...
Done (t=6.63s)
Creating index...
index created!
Loading annotations into memory...
Done (t=0.18s)
Creating index...
index created!
Creating data loaders
Using [0, 0.5, 0.6299605249474366, 0.7937005259840997, 1.0, 1.2599210498948732, 1.5874010519681994, 2.0, inf] as bins for aspect ratio quantization
Count of instances per bin: [  104   982 24236  2332  8225 74466  5763  1158]
Creating model
Start training
Traceback (most recent call last):
  File "/home/tien/temp/vision/references/detection/train.py", line 308, in <module>
    main(args)
  File "/home/tien/temp/vision/references/detection/train.py", line 283, in main
    train_one_epoch(model, optimizer, data_loader, device, epoch, args.print_freq, scaler)
  File "/home/tien/temp/vision/references/detection/engine.py", line 31, in train_one_epoch
    loss_dict = model(images, targets)
  File "/home/tien/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tien/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tien/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1517, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/home/tien/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1354, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/home/tien/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tien/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tien/anaconda3/lib/python3.9/site-packages/torchvision/models/detection/generalized_rcnn.py", line 105, in forward
    detections, detector_losses = self.roi_heads(features, proposals, images.image_sizes, targets)
  File "/home/tien/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tien/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tien/anaconda3/lib/python3.9/site-packages/torchvision/models/detection/roi_heads.py", line 751, in forward
    if not t["keypoints"].dtype == torch.float32:
KeyError: 'keypoints'
[2023-07-04 15:45:10,534] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 273601) of binary: /home/tien/anaconda3/bin/python
Traceback (most recent call last):
  File "/home/tien/anaconda3/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.1.0.dev20230614', 'console_scripts', 'torchrun')())
  File "/home/tien/anaconda3/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/tien/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 797, in main
    run(args)
  File "/home/tien/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 788, in run
    elastic_launch(
  File "/home/tien/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/tien/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-04_15:45:10
  host      : p3660
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 273601)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

### Versions

```
Collecting environment information...
PyTorch version: 2.1.0.dev20230614
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.9.13 (main, Aug 25 2022, 23:26:10)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.0-46-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060
Nvidia driver version: 535.54.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          20
On-line CPU(s) list:             0-19
Vendor ID:                       GenuineIntel
Model name:                      12th Gen Intel(R) Core(TM) i7-12700
CPU family:                      6
Model:                           151
Thread(s) per core:              2
Core(s) per socket:              12
Socket(s):                       1
Stepping:                        2
CPU max MHz:                     4900,0000
CPU min MHz:                     800,0000
BogoMIPS:                        4224.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req hfi umip pku ospke waitpkg gfni vaes vpclmulqdq tme rdpid movdiri movdir64b fsrm md_clear serialize pconfig arch_lbr ibt flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       512 KiB (12 instances)
L1i cache:                       512 KiB (12 instances)
L2 cache:                        12 MiB (9 instances)
L3 cache:                        25 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-19
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==2.1.0.dev20230614
[pip3] torchaudio==2.1.0.dev20230614
[pip3] torchprofile==0.0.4
[pip3] torchvision==0.16.0.dev20230614
[pip3] triton==2.1.0
[conda] _tflow_select             2.3.0                       mkl  
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] numpy-base                1.22.3           py39hf524024_0  
[conda] pytorch                   2.1.0.dev20230614 py3.9_cuda12.1_cudnn8.8.1_0    pytorch-nightly
[conda] pytorch-cuda              12.1                 ha16c6d3_5    pytorch-nightly
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] tensorflow                2.9.1           mkl_py39h3a96225_1  
[conda] tensorflow-base           2.9.1           mkl_py39h353358b_1  
[conda] torchaudio                2.1.0.dev20230614      py39_cu121    pytorch-nightly
[conda] torchprofile              0.0.4                    pypi_0    pypi
[conda] torchtriton               2.1.0+440fd1bf20            py39    pytorch-nightly
[conda] torchvision               0.16.0.dev20230614      py39_cu121    pytorch-nightly
```
I'm not sure if this's a bug or just an error from my side, but I haven't modified any code.

Thank you for your time and consideration!

**Comment by pmeier** [comment]
It's not well documented, but you should use `--dataset=coco_kp`:

https://github.com/pytorch/vision/blob/2d4484fba0f45637f68adadf5a056a6147642aa4/references/detection/train.py#L43-L44

**Comment by pvtien96** [comment]
@pmeier That's correct, it works with your recommendation.
Thank you.
