### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by Egorundel** [pytorch/vision#8089]
Hello! Can you help me fix this error? What's wrong with me?

```shell
(retinaNet) egorundel@egorundel:~/projects/vision/references/detection$ torchrun --nproc_per_node=1 train.py --dataset coco --model retinanet_resnet50_fpn --epochs 3 --lr-steps 16 22 --aspect-ratio-group-factor 3 --lr 0.01 --weights-backbone ResNet50_Weights.IMAGENET1K_V1

| distributed init (rank 0): env://
Namespace(amp=False, aspect_ratio_group_factor=3, backend='pil', batch_size=2, data_augmentation='hflip', data_path='/home/egorundel/projects/ultralytics_yolov8/NAMI_dataset/', dataset='coco', device='cuda', dist_backend='nccl', dist_url='env://', distributed=True, epochs=3, gpu=0, lr=0.01, lr_gamma=0.1, lr_scheduler='multisteplr', lr_step_size=8, lr_steps=[16, 22], model='retinanet_resnet50_fpn', momentum=0.9, norm_weight_decay=None, opt='sgd', output_dir='.', print_freq=20, rank=0, resume='', rpn_score_thresh=None, start_epoch=0, sync_bn=False, test_only=False, trainable_backbone_layers=None, use_copypaste=False, use_deterministic_algorithms=False, use_v2=False, weight_decay=0.0001, weights=None, weights_backbone='ResNet50_Weights.IMAGENET1K_V1', workers=4, world_size=1)
Loading data
loading annotations into memory...
Done (t=1.13s)
creating index...
index created!
loading annotations into memory...
Done (t=0.28s)
creating index...
index created!
Creating data loaders
Using [0, 0.5, 0.6299605249474366, 0.7937005259840997, 1.0, 1.2599210498948732, 1.5874010519681994, 2.0, inf] as bins for aspect ratio quantization
Count of instances per bin: []
Creating model
Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to /home/egorundel/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth
100.0%
Start training
Traceback (most recent call last):
  File "train.py", line 334, in <module>
    main(args)
  File "train.py", line 309, in main
    train_one_epoch(model, optimizer, data_loader, device, epoch, args.print_freq, scaler)
  File "/home/egorundel/projects/vision/references/detection/engine.py", line 27, in train_one_epoch
    for images, targets in metric_logger.log_every(data_loader, print_freq, header):
  File "/home/egorundel/projects/vision/references/detection/utils.py", line 200, in log_every
    print(f"{header} Total time: {total_time_str} ({total_time / len(iterable):.4f} s / it)")
ZeroDivisionError: float division by zero
[2023-11-02 14:48:48,456] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 40401) of binary: /home/egorundel/venvs/retinaNet/bin/python
Traceback (most recent call last):
  File "/home/egorundel/venvs/retinaNet/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/egorundel/venvs/retinaNet/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 351, in wrapper
    return f(*args, **kwargs)
  File "/home/egorundel/venvs/retinaNet/lib/python3.8/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/egorundel/venvs/retinaNet/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/egorundel/venvs/retinaNet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/egorundel/venvs/retinaNet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-02_14:48:48
  host      : egorundel-B560M-H
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 40401)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**MY SYSTEM:**
I have Ubuntu 20.04, CUDA 11.1 and the following versions of torch packages:
```
torch                                2.2.0.dev20231101+cu118 
torchaudio                           2.2.0.dev20231101+cu118 
torchvision                          0.17.0.dev20231101+cu118
```

**Comment by NicolasHug** [comment]
> ({total_time / len(iterable):

Check the dataset, it looks like it's empty

**Comment by Egorundel** [comment]
@NicolasHug Okay, thanks, I'll check!

**Comment by Egorundel** [comment]
@NicolasHug It's strange, because my custom dataset is definitely not empty. In the DATASET folder I have the folders TRAIN, VAL and ANNOTATIONS.

There are instances_train files in the ANNOTATIONS folder.json, instances_val.json.

There are IMAGES and LABELS folders in the TRAIN folder. There are folders in the IMAGES folder that contain images. And in the LABELS folder there are txt files with image names, inside which the images belong to the class.

In the VAL folder, almost everything is the same as in the TRAIN folder, but the sample is smaller, which refers to validation.

**Comment by NicolasHug** [comment]
make sure of that by printing the first few items of the dataset.
Are you sure it's not a generator that gets consumed after the first iteration?

Although TBH @Egorundel these are usage questions that are better directed to our discuss forum https://discuss.pytorch.org/
Here we're on a bug/issue tracker, and we can't really afford to address every users' question unfortunately

**Comment by Egorundel** [comment]
@NicolasHug Well, but could you show me where to find the dataset **datasets01/COCO/022719** that you specified in `train.py`? 
I would try to understand it and understand what is wrong with my custom dataset.

**Comment by NicolasHug** [comment]
This is the coco detection dataset as described in https://github.com/pytorch/vision/issues/8087#issuecomment-1790479970

**Comment by Egorundel** [comment]
@NicolasHug Sorry to bother you with questions, but could you watch this issue https://github.com/pytorch/vision/issues/8087 ? 

I described my dataset in detail there and I still can't do anything.
