### ISSUE TITLE
Error when training ResNet on references/classification/train.py

### ISSUE THREAD

**Issue by zhulinchng** [pytorch/vision#8288]
### 🐛 Describe the bug

Error encountered when running train.py (specifically transforms.py)
```bash
Traceback (most recent call last):
  File "F:\Documents\Code\vision\references\classification\train.py", line 528, in <module>
    main(args)
  File "F:\Documents\Code\vision\references\classification\train.py", line 224, in main
    mixup_cutmix = get_mixup_cutmix(
                   ^^^^^^^^^^^^^^^^^
  File "F:\Documents\Code\vision\references\classification\transforms.py", line 16, in get_mixup_cutmix
    transforms_module.MixUp(alpha=mixup_alpha, num_categories=num_categories)
TypeError: _BaseMixUpCutMix.__init__() got an unexpected keyword argument 'num_categories'
```

I have used the following command
```bash
python train.py --model resnet50 --batch-size 256 --lr 0.5 --lr-scheduler cosineannealinglr --lr-warmup-epochs 5 --lr-warmup-method linear --auto-augment ta_wide --epochs 600 --random-erase 0.1 --weight-decay 0.00002  --norm-weight-decay 0.0 --label-smoothing 0.1 --mixup-alpha 0.2 --cutmix-alpha 1.0 --train-crop-size 176 --model-ema --val-resize-size 232 --ra-sampler --ra-reps 4 --test-only --data-path "G:\imagenet" --device "cuda" --use-v2 --workers 16
```

### Versions

```bash
PyTorch version: 2.1.2+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home Single Language
GCC version: (Rev7, Built by MSYS2 project) 12.2.0
Clang version: Could not collect
CMake version: version 3.25.1
Libc version: N/A

Python version: 3.11.8 | packaged by Anaconda, Inc. | (main, Feb 26 2024, 21:34:05) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is CUDA available: True
CUDA runtime version: 12.1.66
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080
Nvidia driver version: 551.61
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3801
DeviceID=CPU0
Family=107
L2CacheSize=4096
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=3801
Name=AMD Ryzen 7 5700G with Radeon Graphics
ProcessorType=3
Revision=20480

Versions of relevant libraries:
[pip3] numpy==1.26.3
[pip3] torch==2.1.2+cu121
[pip3] torchaudio==2.1.2+cu121
[pip3] torchvision==0.16.2+cu121
[conda] numpy                     1.26.3                   pypi_0    pypi
[conda] torch                     2.1.2+cu121              pypi_0    pypi
[conda] torchaudio                2.1.2+cu121              pypi_0    pypi
[conda] torchvision               0.16.2+cu121             pypi_0    pypi
```

**Comment by zhulinchng** [comment]
Created fix on #8287
