### ISSUE TITLE
MD5 checksum of download file does not match the one on record

### ISSUE THREAD

**Issue by andreasfloros** [pytorch/vision#8338]
### 🐛 Describe the bug

```python

# gen_celeba.py

from torch.utils.data import DataLoader
import torchvision as tv


def main(path_to_data: str) -> None:

    dataset = tv.datasets.CelebA(root=path_to_data,
                                 split="all",
                                 target_type="attr",
                                 download=True, transform=tv.transforms.ToTensor())
    dataloader = DataLoader(dataset)
    for img, attr in dataloader:
        print(img.shape, attr.shape)
        break
    print("Ok!")


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--p2d', type=str, required=True, help='path to data')
    args = parser.parse_args()
    main(path_to_data=args.p2d)

```

Running:

```python

python gen_celeba.py --p2d data
```

Gives:

```
2422it [00:00, 3014422.64it/s]
env\Lib\site-packages\torchvision\datasets\utils.py:260: UserWarning: We detected some HTML elements in the downloaded file. This most likely means that the download triggered an unhandled API response by GDrive. Please report this to torchvision at https://github.com/pytorch/vision/issues including the response:

<!DOCTYPE html><html><head><title>Google Drive - Virus scan warning</title><meta http-equiv="content-type" content="text/html; charset=utf-8"/><style nonce="idGN89Bm7B0CI5ZK88c5aQ">.goog-link-button{position:relative;color:#15c;text-decoration:underline;cursor:pointer}.goog-link-button-disabled{color:#ccc;text-decoration:none;cursor:default}body{color:#222;font:normal 13px/1.4 arial,sans-serif;margin:0}.grecaptcha-badge{visibility:hidden}.uc-main{padding-top:50px;text-align:center}#uc-dl-icon{display:inline-block;margin-top:16px;padding-right:1em;vertical-align:top}#uc-text{display:inline-block;max-width:68ex;text-align:left}.uc-error-caption,.uc-warning-caption{color:#222;font-size:16px}#uc-download-link{text-decoration:none}.uc-name-size a{color:#15c;text-decoration:none}.uc-name-size a:visited{color:#61c;text-decoration:none}.uc-name-size a:active{color:#d14836;text-decoration:none}.uc-footer{color:#777;font-size:11px;padding-bottom:5ex;padding-top:5ex;text-align:center}.uc-footer a{color:#15c}.uc-footer a:visited{color:#61c}.uc-footer a:active{color:#d14836}.uc-footer-divider{color:#ccc;width:100%}.goog-inline-block{position:relative;display:-moz-inline-box;display:inline-block}* html .goog-inline-block{display:inline}*:first-child+html .goog-inline-block{display:inline}sentinel{}</style><link rel="icon" href="//ssl.gstatic.com/docs/doclist/images/drive_2022q3_32dp.png"/></head><body><div class="uc-main"><div id="uc-dl-icon" class="image-container"><div class="drive-sprite-aux-download-file"></div></div><div id="uc-text"><p class="uc-warning-caption">Google Drive can't scan this file for viruses.</p><p class="uc-warning-subcaption"><span class="uc-name-size"><a href="/open?id=0B7EVK8r0v71pZjFTYXZWM3FlRnM">img_align_celeba.zip</a> (1.3G)</span> is too large for Google to scan for viruses. Would you still like to download this file?</p><form id="download-form" action="https://drive.usercontent.google.com/download" method="get"><input type="submit" id="uc-download-link" class="goog-inline-block jfk-button jfk-button-action" value="Download anyway"/><input type="hidden" name="id" value="0B7EVK8r0v71pZjFTYXZWM3FlRnM"><input type="hidden" name="export" value="download"><input type="hidden" name="confirm" value="t"><input type="hidden" name="uuid" value="e6d6f025-8f92-4029-893d-a3eb6374fc53"></form></div></div><div class="uc-footer"><hr class="uc-footer-divider"></div></body></html>
  warnings.warn(
Traceback (most recent call last):
  File "gen_celeba.py", line 23, in <module>
    main(path_to_data=args.p2d)
  File "gen_celeba.py", line 7, in main
    dataset = tv.datasets.CelebA(root=path_to_data,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env\Lib\site-packages\torchvision\datasets\celeba.py", line 80, in __init__
    self.download()
  File "env\Lib\site-packages\torchvision\datasets\celeba.py", line 150, in download
    download_file_from_google_drive(file_id, os.path.join(self.root, self.base_folder), filename, md5)
  File "env\Lib\site-packages\torchvision\datasets\utils.py", line 268, in download_file_from_google_drive
    raise RuntimeError(
RuntimeError: The MD5 checksum of the download file data\celeba\img_align_celeba.zip does not match the one on record.Please delete the file and try again. If the issue persists, please report this to torchvision at https://github.com/pytorch/vision/issues.
```

### Versions

```
torch              2.1.2+cu118
torchvision        0.16.2+cu118
```

**Comment by andreasfloros** [comment]
Nevermind, just saw this was fixed in #8204. Updating fixed it, closing
