### ISSUE TITLE
M1 conda-py3_11-cpu failing

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#8479]
Apart from the usual flakyness, the M1 conda build job on 3.11 CPU has been consistently failing on the past 4 commits to `main` with

```
+ /opt/homebrew/Caskroom/miniconda/base/bin/conda run -p /Users/ec2-user/runner/_work/_temp/pytorch_pkg_helpers_9402123718_smoke python3 pytorch/vision/test/smoke_test.py
Traceback (most recent call last):
  File "/Users/ec2-user/runner/_work/vision/vision/pytorch/vision/test/smoke_test.py", line 7, in <module>
    import torchvision
  File "/Users/ec2-user/.local/lib/python3.11/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/Users/ec2-user/.local/lib/python3.11/site-packages/torchvision/_meta_registrations.py", line 163, in <module>
    @torch._custom_ops.impl_abstract("torchvision::nms")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ec2-user/runner/_work/_temp/pytorch_pkg_helpers_9402123718_smoke/lib/python3.11/site-packages/torch/library.py", line 653, in register
    use_lib._register_fake(op_name, func, _stacklevel=stacklevel + 1)
  File "/Users/ec2-user/runner/_work/_temp/pytorch_pkg_helpers_9402123718_smoke/lib/python3.11/site-packages/torch/library.py", line 153, in _register_fake
    handle = entry.abstract_impl.register(func_to_register, source)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ec2-user/runner/_work/_temp/pytorch_pkg_helpers_9402123718_smoke/lib/python3.11/site-packages/torch/_library/abstract_impl.py", line 30, in register
    if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: operator torchvision::nms does not exist

ERROR conda.cli.main_run:execute(125): `conda run python3 pytorch/vision/test/smoke_test.py` failed. (See above for error)
```

The other Python versions seem to be fine.

**Comment by NicolasHug** [comment]
No idea why, but this is now passing.
