### ISSUE TITLE
Windows conda build jobs are failing 

### ISSUE THREAD

**Issue by atalman** [pytorch/vision#8564]
### 🐛 Describe the bug

Windows conda build jobs are failing https://github.com/pytorch/vision/actions/runs/10093364122/job/27908922910

```
source tree in: C:\Jenkins\Miniconda3\conda-bld\vs2019_1721909022442\work
Packaging vs2019_win-64

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Jenkins\Miniconda3\lib\site-packages\conda\exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
      File "C:\Jenkins\Miniconda3\lib\site-packages\conda\cli\main.py", line 84, in main_subshell
        exit_code = do_call(args, parser)
      File "C:\Jenkins\Miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 176, in do_call
        result = plugin_subcommand.action(getattr(args, "_args", args))
      File "C:\Jenkins\Miniconda3\lib\site-packages\conda_build\plugin.py", line 17, in build
        return execute(args)
      File "C:\Jenkins\Miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 589, in execute
        api.build(
      File "C:\Jenkins\Miniconda3\lib\site-packages\conda_build\api.py", line 209, in build
        return build_tree(
      File "C:\Jenkins\Miniconda3\lib\site-packages\conda_build\build.py", line 3709, in build_tree
        packages_from_this = build(
      File "C:\Jenkins\Miniconda3\lib\site-packages\conda_build\build.py", line 2762, in build
        newly_built_packages = bundlers[pkg_type](
      File "C:\Jenkins\Miniconda3\lib\site-packages\conda_build\build.py", line 1741, in bundle_conda
        on_win and Path("C:\\Windows\\System32\\bash.exe").samefile(args[0])
      File "C:\Jenkins\Miniconda3\lib\pathlib.py", line 1149, in samefile
        st = self.stat()
      File "C:\Jenkins\Miniconda3\lib\pathlib.py", line 1232, in stat
        return self._accessor.stat(self)
    FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Windows\\System32\\bash.exe'
```

https://hud2.pytorch.org/hud/pytorch/vision/nightly/1?per_page=50&name_filter=windows

### Versions

0.20.0

**Comment by atalman** [comment]
Reason for failure. Windows core build failing.
This should be resolved now: https://github.com/pytorch/vision/actions/runs/10161592561/job/28130382448
