### ISSUE TITLE
Vision Nightly aarch64 builds are failing for CPU and GPU

### ISSUE THREAD

**Issue by atalman** [pytorch/vision#8591]
### 🐛 Describe the bug

All Aarch64 vision builds failed on Aug 14, 2024:
https://github.com/pytorch/vision/actions/runs/10386791010/job/28759157208

Audio seems fine:
https://hud2.pytorch.org/hud/pytorch/audio/nightly/1?per_page=50

### Versions

0.20.0 nightly

cc @NicolasHug @malfet

**Comment by malfet** [comment]
Relevant part of the log:
```
Traceback (most recent call last):
  File "/__w/vision/vision/pytorch/vision/packaging/wheel/relocate.py", line 378, in <module>
    patch_linux()
  File "/__w/vision/vision/pytorch/vision/packaging/wheel/relocate.py", line 335, in patch_linux
    relocate_elf_library(patchelf, output_dir, output_library, binary)
  File "/__w/vision/vision/pytorch/vision/packaging/wheel/relocate.py", line 216, in relocate_elf_library
    library_dependencies = binary_dependencies[binary]
KeyError: 'image.so'
```

**Comment by atalman** [comment]
Looks like the issue maybe related to 
https://pypi.org/project/setuptools/#files - Released: Aug 13, 2024
setuptools 72.2.0

I do see something like this in the log:
```
2024-08-14T17:47:49.2817611Z Collecting setuptools
2024-08-14T17:47:49.2818481Z   Downloading setuptools-72.2.0-py3-none-any.whl.metadata (6.6 kB)
2024-08-14T17:47:49.2819699Z Downloading setuptools-72.2.0-py3-none-any.whl (2.3 MB)
2024-08-14T17:47:49.2820771Z    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 97.6 MB/s eta 0:00:00
2024-08-14T17:47:49.2821626Z Installing collected packages: setuptools
2024-08-14T17:47:49.2822330Z   Attempting uninstall: setuptools
2024-08-14T17:47:49.2823044Z     Found existing installation: setuptools 72.1.0
2024-08-14T17:47:49.2823855Z     Uninstalling setuptools-72.1.0:
2024-08-14T17:47:49.2824629Z       Successfully uninstalled setuptools-72.1.0
2024-08-14T17:47:49.2825454Z Successfully installed setuptools-72.2.0
2024-08-14T17:47:49.2825935Z 
```

**Comment by atalman** [comment]
Reopened to followup why setuptools breaks our builds
