### ISSUE TITLE
torchvision.io.decode_image can not be used as document

### ISSUE THREAD

**Issue by malfet** [pytorch/vision#8698]
### 🐛 Describe the bug

By looking at https://pytorch.org/vision/0.20/generated/torchvision.io.decode_image.html
it feels like one should be able to do something like
```python
from torchvision.io import decode_image
decode_image("foo.png")
```

but it fails with
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nshulga/miniconda3/envs/py-311/lib/python3.11/site-packages/torchvision/io/image.py", line 269, in decode_image
    output = torch.ops.image.decode_image(input, mode.value, apply_exif_orientation)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nshulga/miniconda3/envs/py-311/lib/python3.11/site-packages/torch/_ops.py", line 1061, in __call__
    return self_._op(*args, **(kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: image::decode_image() Expected a value of type 'Tensor' for argument 'data' but instead found type 'str'.
Position: 0
Value: 'foo.png'
Declaration: image::decode_image(Tensor data, int mode, bool apply_exif_orientation=False) -> Tensor
Cast error details: Unable to cast foo.png to Tensor
```

But read_image works as expeted:
```python
from torchvision.io import read_image
read_image("foo.png")
```

### Versions

0.19.1

**Comment by NicolasHug** [comment]
Hi @malfet ,

This is a new feature introduced in 0.20. Can you try to update torchvision and let me know if there's any issue?

**Comment by GdoongMathew** [comment]
Hi @NicolasHug 
I think this is fixed in 0.21.0. Both `decode_image` and `read_image` works fine in my windows 11 machine.
```python
>>> from torchvision.io import read_image, decode_image
>>> image = decode_image(r"D:\dot.jpg")
>>> image2 = read_image(r"D:\dot.jpg")
```

**Comment by NicolasHug** [comment]
Thanks for the remainder @GdoongMathew , this can be closed
